variables:
  - name: containerRegistry
    ${{ if eq(variables['Build.SourceBranchName'], 'production') }}:
      value: 'ACR-DEVOPS-SICCAU-PRD'
    ${{ else }}:
      value: 'ACR-DEVOPS-SICCAU-HMG-DEV'

  - name: branchName
    ${{ if or(eq(variables['Build.SourceBranchName'], 'development'), eq(variables['Build.SourceBranchName'], 'homologation'), eq(variables['Build.SourceBranchName'], 'staging'), eq(variables['Build.SourceBranchName'], 'production')) }}:
      value: $(Build.SourceBranchName)
    ${{ else }}:
      value: 'teste'

trigger:
  - $(Build.SourceBranchName)

resources:
  - repo: self

pool:
  name: Azure Pipelines

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: $(containerRegistry)
      repository: 'caubr/eleitoral-backend'
      command: 'build'
      Dockerfile: '**/.devops/docker/Dockerfile.$(branchName)'
      tags: |
        $(Build.SourceBranchName)-$(Build.BuildId)
      buildContext: '.'

  - task: Docker@2
    displayName: Push an image
    inputs:
      containerRegistry: $(containerRegistry)
      repository: 'caubr/eleitoral-backend'
      command: 'push'
      tags: |
        $(Build.SourceBranchName)-$(Build.BuildId)

  - task: CopyFiles@2
    inputs:
      SourceFolder: '.devops/helm'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: $(Build.SourceBranchName)-eleitoral-backend'
    inputs:
      ArtifactName: 'deploy'
