FROM node:12 AS builder

WORKDIR /app

COPY .npmrc .npmrc
COPY package.json package.json

RUN npm install
RUN rm -f .npmrc

COPY ./ /app/

RUN npm run os7270 -- --output-path=./dist/out

FROM nginx:1.20-alpine

COPY --from=builder /app/dist/out/ /usr/share/nginx/html

COPY .devops/docker/nginx.conf /etc/nginx/conf.d/default.conf