import { ValidationResource } from '@cau/component';
import { MESSAGE_RESOURCE_LAYOUT } from "@cau/layout";
import { MessageResource, MESSAGE_RESOURCE_CONFIRM } from "@cau/message";

/**
 * Implementation responsible for providing as 'descriptions' and 'messages' in the application in one place.
 *
 * @author Squadra Tecnologia
 */
export class AppMessage implements MessageResource, ValidationResource {

    private resource: Object;

    /**
     * Constructor class.
     */
    constructor() {
        this.resource = {
            ...MESSAGE_RESOURCE_LAYOUT,
            ...MESSAGE_RESOURCE_CONFIRM,
            LABEL_LAYOUT_NOME_SISTEMA: 'Portal',

            LABEL_ALTERAR: 'Alterar',
            LABEL_EXCLUIR: 'Excluir',
            LABEL_ALTERAR_CURRICULO: 'Alterar Currículo',
            LABEL_MENU: 'Menu',
            LABEL_BEM_VINDO: 'Bem vindo(a)',
            LABEL_CONFIGURAR: 'Configurar',
            LABEL_NOTIFICACAO: 'Notificação',
            LABEL_SAIR: 'Sair',
            LABEL_N_CHAPA: 'N° da Chapa: ',
            LABEL_CHAPA_NUM: 'Chapa nº {0}',
            LABEL_VISUALIZAR_PLATAFORMA: 'Visualizar Plataforma/Propaganda',
            LABEL_CAU: 'CAU/BR',
            LABEL_ATUAL: 'Atual',
            LABEL_RETIFICACAO: 'Retificação',
            LABEL_COPYRIGHT: '© 2019',
            LABEL_MODULO: 'Módulo',
            LABEL_NOME_DECLARACAO: 'Nome da Declaração',
            LABEL_INCLUIR_NOVO: 'Incluir Novo',
            LABEL_NUMERO: 'Número',
            LABEL_CODIGO: 'Código',
            LABEL_ACOES: 'Ações',
            LABEL_EDITAR: 'Editar',
            LABEL_ATIVAR_DECLARACAO: 'Ativar Declaração',
            LABEL_CADASTRAR_ALEGACAO: 'Cadastrar Alegação',
            LABEL_TITULO_TEXTO_DECLARACAO: 'Título do Texto da Declaração',
            LABEL_NUM: 'Nº',
            LABEL_ETAPAS: 'Etapas',
            LABEL_HIFEN: '-',
            LABEL_FUNDAMENTACAO: 'Fundamentação',
            LABEL_OK: 'OK',
            LABEL_DECLARACAO: 'Declaração',
            LABEL_ADICIONAR_DECLARACAO: 'Adicionar Declaração',
            LABEL_REMOVER: 'Remover',
            LABEL_TIPO_RESPOSTA: 'Tipo de Resposta',
            LABEL_MULTIPLA: 'Múltipla',
            LABEL_DESCRICAO: 'Descrição',
            LABEL_MEMBRO_JULGAMENTO_FINAL: 'Resultado dos membros indicados para substituição',
            LABEL_VISUALIZAR_JULGAMENTO_FINAL: 'Visualizar Julgamento Final das Chapas - 1ª Instância',
            LABEL_UNICA: 'Única',
            LABEL_ACOMPANHAR_CHAPA: '{0} Acompanhar {1} Chapa {2}',
            LABEL_PERMITIR_USUARIO_REALIZAR_UPLOAD: 'Permitir Usuário Realizar Upload',
            LABEL_UPLOAD_OBRIGATORIO: 'Upload Obrigatório',
            LABEL_PDF: 'PDF',
            LABEL_DOC_DOCX: 'DOC/DOCX',
            LABEL_SALVAR: 'Salvar',
            LABEL_VISUALIZAR: 'Visualizar',
            LABEL_TEXTO_INICIAL: 'Texto Inicial',
            LABEL_VOLTAR: 'Voltar',
            LABEL_PESQUISAR: 'Pesquisar',
            LABEL_EU: 'Eu',
            LABEL_DECLARO: 'DECLARO',
            LABEL_QUE: 'que',
            LABEL_ARQUIVO: 'Arquivo',
            LABEL_FECHAR: 'Fechar',
            LABEL_ANO_ELEICAO: 'Ano da Eleição',
            LABEL_ELEICAO: 'Eleição',
            LABEL_ELEICOES: 'Eleições',
            LABEL_COMISSAO_ELEITORAL: 'Comissão Eleitoral',
            LABEL_UF: 'UF: ',
            LABEL_TODAS: 'Todas',
            LABEL_VISUALIZAR_MEMBROS_COMISSOES: 'Visualizar Membros das Comissões',
            LABEL_COORDENADORES: 'Coordenadores',
            LABEL_COORDENADOR: 'Coordenador',
            LABEL_COORDENADOR_COMISSAO: 'Coordenador da Comissão',
            LABEL_NOME: 'Nome',
            LABEL_TELEFONE: 'Telefone',
            LABEL_TIPO: 'Tipo',
            LABEL_CPF: 'CPF',
            LABEL_TIPO_PARTICIPACAO: 'Tipo Participação',
            LABEL_PARTICIPACAO: 'Participação',
            LABEL_EMAIL: "E-MAIL",
            LABEL_STATUS: 'Status',
            LABEL_MEMBRO: 'Membro',
            LABEL_STATUS_SUBSTITUICAO: 'Status da Substituição',
            LABEL_MEMBROS: 'Membros',
            LABEL_ACEITAR: 'Aceitar',
            LABEL_RECUSAR: 'Recusar',
            LABEL_CONFIRMAR: 'Confirmar',
            LABEL_CANCELAR: 'Cancelar',
            LABEL_VISAO_GERAL: 'Visão Geral',
            LABEL_SUBSTITUICAO_MEMBRO: 'Chapa sem indicação de substituição de membro!',
            CADASTRO_MEMBROS_COMISSAO_ELEITORAL: 'Cadastro Membros da Comissão Eleitoral',
            LABEL_DETALHES: 'Detalhes',
            LABEL_INFORMACOES_PESSOAIS: 'Informações Pessoais',
            LABEL_CARGO: 'Cargo',
            LABEL_SITUACAO: 'Situação',
            LABEL_NUMERO_MEMBROS: 'Número de Membros',
            LABEl_EMAIL_MIN: "E-mail",
            LABEL_APTO_CONSELHO: 'Apto a se tornar membro do conselho eleitoral',
            LABEL_EXISTE_PENDENCIAS: 'Existem as seguintes pendências para este membro',
            LABEL_CADASTRO_CHAPA: 'Cadastro de Chapa',
            LABEL_PLATAFORMA_ELEITORAL_REDES_SOCIAIS: 'Plataforma Eleitoral/Redes Sociais',
            LABEL_MEMBROS_CHAPA: 'Membros da Chapa',
            LABEL_CANDIDATURA: 'Candidatura',
            LABEL_TERMO_DECLARACAO: 'Termos da Declaração',
            LABEL_AGUARDANDO_CONCLUSAO: 'Aguardando Conclusão',
            LABEL_CHAPA: 'Chapa',
            LABEL_CHAPA_CONCLUIDA: 'Chapa Concluída',
            LABEL_CPF_PROFISSIONAL: 'CPF do Profissional',
            LABEL_REGISTRO: 'Registro',
            LABEL_STATUS_VALIDACAO: 'Status Validação',
            LABEL_RESPONSAVEL: 'Responsável',
            LABEL_ANTERIOR: 'Anterior',
            LABEL_PROXIMO: 'Próximo',
            LABEL_AVANCAR: 'Avançar',
            LABEL_SOLICITAR_RECURSO: 'Solicitar Recurso',
            LABEL_SOLICITAR_RECURSO_SUBSTITUICAO: 'Solicitar Recurso',
            LABEL_SOLICITAR_SUBSITUICAO: 'Solicitar Substituição',
            LABEL_SOLICITAR_RECONSIDERACAO: 'Solicitar Reconsideração',
            LABEL_SOLICITAR_RECURSO_RECONSIDERACAO: 'Solicitar {0}',
            LABEL_CADASTRAR_PLATAFORMA_ELEITORAL_UF: 'Cadastrar Plataforma Eleitoral UF',
            LABEL_CADASTRAR_PLATAFORMA_ELEITORAL_IES: 'Cadastrar Plataforma Eleitoral IES',
            LABEL_PLATAFORMA_ELEITORAL_UF: 'Plataforma Eleitoral UF',
            LABEL_PLATAFORMA_ELEITORAL_IES: 'Plataforma Eleitoral IES',
            LABEL_CADASTRAR_MEIOS_OFICIAIS_PROPAGANDAS: 'Cadastrar Meios Oficiais de Propagandas',
            LABEL_MEIOS_OFICIAIS_PROPAGANDAS: 'Meios Oficiais de Propagandas',
            LABEL_CADASTRAR_MEMBROS_CHAPA: 'Cadastrar Membros da Chapa',
            LABEL_CONSELHEIROS_ESTADUAIS: 'Conselheiros Estaduais',
            LABEL_CONSELHEIRO_FEDERAL: 'Conselheiro Federal',
            LABEL_CADASTRAR_MEMBROS_REPRESENTANTES_IES: 'Cadastrar Membros Para Representante IES',
            LABEL_REPRESENTANTE_IES: 'Representante IES',
            LABEL_CONSELHEIRO_UF_BR: 'Conselheiro UF-BR',
            LABEL_IES: 'IES',
            LABEL_OUTROS: 'Outros',
            LABEL_TITULAR: 'Titular',
            LABEL_SUPLENTE: 'Suplente',
            LABEL_OU: 'ou',
            LABEL_IMPUGANACAO_RESULTADO_ELEICAO: 'Impugnação de Resultado Eleição',
            LABEL_PARABENS_VOCE_FOI_CONVIDADO_PARTICIPAR_DAS_ELEICOES_UF: 'Parabéns, você foi convidado a participar das eleições como membro da chapa eleitoral (CAU/{0}).',
            LABEL_PARABENS_VOCE_FOI_CONVIDADO_PARTICIPAR_DAS_ELEICOES_IES: 'Parabéns, você foi convidado a participar das eleições como membro da chapa eleitoral para Representante IES.',
            LABEL_PARABENS_VOCE_FOI_CONVIDADO_PARTICIPAR_DAS_ELEICOES_UF_IES: 'Parabéns, você foi convidado a participar das eleições como membro da chapa eleitoral (CAU/{0}) e Representante IES.',
            LABEL_CONFIRMAR_PARTICIPACAO_CHAPA_ELEITORAL: "Confirmar Participação em Chapa Eleitoral",
            LABEL_VISUALIZAR_CONVITES_PARA_MEMBRO_CHAPA_ELEITORAL: "Visualizar Convite Para Membro da Chapa Eleitoral",
            LABEL_INFORMACOES_IMPORTANTES: "Informações Importantes",
            LABEL_CONVITES_RECEBIDOS: "Convites Recebidos",
            LABEL_INFORMACOES_CHAPA: "Informações da chapa",
            LABEL_INFORMACOES_CANDIDATO: "Informações do Candidato",
            LABEL_INFORMACOES_PARTICIPACAO: "Informações para participação",
            LABEL_NOME_RESPONSAVEL: "Nome do Responsável",
            LABEL_NOME_CANDIDATO: "Nome do Candidato",
            LABEL_PLATAFORMA_ELEITORAL: "Plataforma Eleitoral",
            LABEL_POSICAO_CHAPA: "Posição na Chapa",
            LABEL_POSICAO: "Posição",
            LABEL_DADOS_PROFISSIONAL_SUBISTITUIDO: "Dados do profissional a ser substituido (a)",
            LABEL_DADOS_PROFISSIONAL_IMPUGNADO: "Dados do profissional a ser impugnado (a)",
            LABEL_REJEITAR: "Rejeitar",
            LABEL_SIM: "Sim",
            LABEL_NAO: "Não",
            LABEL_INFORMACOES: "Informações",
            LABEL_INCLUA_ALTERE_SUA_FOTO: "Inclua ou altere sua foto",
            LABEL_REGRAS_FOTO_MEMBRO_CHAPA: "São permitidos fotos no formato 3x4 que sejam os tipos (JPG, BMP, PNG) de até 2MB.",
            SINTESE_CURRICULO: "Síntese do Currículo",
            LABEL_DOCUMENTOS_COMPROBATORIOS: "Documentos Comprobatórios",
            LABEL_SELECIONE: "Selecione",
            LABEL_SELECIONAR: "Selecionar",
            LABEL_SELECIONAR_RELATOR: "Selecionar Relator",
            LABEL_COMPROVANTE_VINCULO_DOCENTE_COM_IES: "Comprovante de vinculo docente com a IES",
            LABEL_CARTA_DE_INDICACAO_INSTITUICAO: "Carta de indicação da instituição",
            LABEL_MEMBROS_CHAPA_ELEITORAL: "Membros da Chapa Eleitoral",
            LABEL_CORTAR_FOTO: "Cortar Fotos",
            LABEL_CONCLUIR: "Concluir",
            LABEL_CORTA_FOTO: "Cortar Foto",
            LABEL_CONVITE_RECEBIDO: "Convite Recebido",
            LABEL_PREZADO_VOCE_NAO_POSSUI_CONVITES: "Prezado, você não possui convites para participar das eleições como membro da chapa eleitoral (CAU/{0}).",
            LABEL_INSIRA_CPF_NOME_CONSELHEIRO_FEDERAL: 'Insira um CPF ou Nome do conselheiro federal',
            LABEL_INSIRA_CPF_NOME_MEMBRO: 'Insira um CPF ou Nome do titular',
            LABEL_INSIRA_CPF_NOME_SUPLENTE: 'Insira um CPF ou Nome do suplente',
            LABEL_INSIRA_CPF_NOME_TITULAR_IES: 'Insira um CPF ou Nome do titular IES',
            LABEL_INSIRA_CPF_NOME_SUPLENTE_IES: 'Insira um CPF ou Nome do suplente IES',
            LABEL_INSIRA_CPF_NOME_PROFISSIONAL: 'Insira um Cpf ou Nome do profissional',
            LABEL_INSIRA_CPF_NOME_CANDIDATO: 'Insira um CPF ou Nome do candidato',
            LABEL_INSIRA_CPF_NOME_MEMBRO_SUBSTITUIDO: 'Insira um CPF ou Nome do membro a ser substituido',
            LABEL_STATUS_CONFIRMACAO: 'Status Confirmação',
            LABEL_STATUS_CONFIRMADO: 'Confirmado',
            LABEL_STATUS_REJEITADO: 'Rejeitado',
            LABEL_STATUS_A_CONFIRMAR: 'A confirmar',
            LABEL_ENVIAR_EMAIL_PENDENCIA: 'Enviar E-mail de pendência',
            LABEL_REENVIAR_CONVITE: 'Reenviar Convite',
            LABEL_ATUALIZAR_STATUS: 'Atualizar Status',
            LABEL_CURRICULO: 'Currículo',
            LABEL_JUSTIFICATIVA: 'Justificativa',
            LABEL_INSERIR_JUSTIFICATIVA: 'Inserir Justificativa',
            LABEL_JUSTIFICATIVA_DOCUMENTO: 'Justificativa/Inserir Documento',
            LABEL_CARTA_INDICACAO: 'Carta de Indicação',
            LABEL_DECLARACAO_VINCULO_DOCENTE: 'Declaração Vínculo Docente ',
            LABEL_VALIDACAO: 'Validação',
            LABEL_ACAO: "Ação",
            LABEL_NUMERO_CHAPA: 'Nº Chapa',
            LABEL_NOME_COMPLETO: 'Nome Completo',
            LABEL_HINT_AVISO_FOTO_CURRICULO: "Prezado (a) Arquiteto (a) e Urbanista a fotografia inserida nesse menu gerará efeitos apenas para o processo eleitoral. Não gerando efeitos e atualizações para outras modalidades no sistema.",
            LABEL_DIGITE_CPF_NOME_COMPLETO: "Digite um CPF ou Nome Completo",
            LABEL_JUSTIFICATIVA_ALTERACAO_RESPONSAVEL: "Justificativa - Alteração Responsável",
            LABEL_JUSTIFICATIVA_ALTERACAO_RESPONSAVEL_OBSERVACAO: "Sr.(a) usuário(a), para alteração do responsável, o campo justificativa é de preenchimento obrigatório:",
            LABEL_MOSTRAR: 'Mostrar',
            LABEL_REGISTROS: 'registros',
            LABEL_SINTESE_CURRICULO: 'Síntese Currículo',
            LABEL_PARABENS_VOCE_CADASTROU_CHAPA_ELEITORAL: "Parabéns! Você cadastrou a Chapa Eleitoral {0} e seus membros. Por favor, agurde a <br> confirmação dos membros da sua chapa, para continuidade do processo eleitoral.",
            LABEL_DENUNCIA: 'Denúncia',
            LABEL_NUMERO_DENUNCIA: 'Nº da Denúncia',
            LABEL_TIPO_DENUNCIA: 'Tipo de Denúncia',
            LABEL_RESULTADO: 'Resultado',
            LABEL_RESPONSAVEL_PELO_CADASTRO: "Responsável pelo Cadastro",
            LABEL_DESCRICAO_DESIGNACAO_RELATOR: 'Descrição de Designação de Relator',
            LABEL_DESCRICAO_RECURSO_RECONSIDERACAO: 'Descrição do(a) Recurso ou Reconsideração',
            LABEL_INSIRA_NOME_OU_REGISTRO: 'Insira o nome ou registro',
            LABEL_DOCUMENTOS: 'Documentos',
            LABEL_TESTEMUNHAS: 'Testemunhas',
            LABEL_ADICIONAR_TESTEMUNHAS: 'Adicionar Testemunhas',
            LABEL_DADOS_RELATOR: 'Dados do Relator',
            LABEL_RELATOR: 'Relator',
            LABEL_NARRACAO_FATOS: 'Narração dos Fatos',
            LABEL_DESCRICAO_ADMISSAO: 'Descrição da Admissão',
            LABEL_DESCRICAO_INADMISSAO: 'Descrição da Inadmissão',
            LABEL_DESCRICAO_ENCAMINHAMENTO: 'Descrição do Encaminhamento',
            LABEL_ENVIAR_PARA: 'Enviar Para',
            LABEL_SELECIONAR_DATA: 'Selecionar Data',
            LABEL_NUMERO_IMPUGACAO_RESULTADO: 'Nº Pedido de Impugação de Resultado',
            LABEL_NUMERO_PEDIDO_IMPUGACAO_RESULTADO: 'Nº Pedido de Impugação de Resultado',
            LABEL_SELECIONAR_HORARIO: 'Selecionar Horário',
            LABEL_APRESENTACAO_DEFESA: 'Apresentação da Defesa',
            LABEL_ENCAMINHAMENTO: 'Encaminhamento',
            LABEL_INFORMACOES_DENUNCIADO: 'Informações do Denunciado',
            LABEL_INFORMACOES_DENUNCIANTE: 'Informações do Denunciante',
            LABEL_CADASTRO_DENUNCIA: 'Cadastro de Denúncia',
            LABEL_ACOMPANHAR_DENUNCIA: 'Acompanhar Denúncia',
            LABEL_ANALISE_ADMISSIBILIDADE: 'Análise de Admissibilidade',
            LABEL_JULGAMENTO_ADMISSIBILIDADE: 'Julgamento de Admissibilidade',
            LABEL_CADASTRAR_DENUNCIA: 'Cadastrar Denúncia',
            LABEL_MUDANCA_STATUS_PARA_CONCLUIDA_NAO_CONDICAO_DETERMINANTE_PARA_DEFERIMENTO_CHAPA: "A mudança de status para concluída não é condição determinante para deferimento de chapa",
            LABEL_ESTADO: "Estado",
            LABEL_QUANTIDADE_PEDIDOS_DENUNCIA: 'Quantidade de Pedidos de Denúncia',
            LABEL_TOTAL_PEDIDOS_DENUNCIA: "Total de Pedidos de Denúncia",
            LABEL_DATA_HORA_CADASTRO: 'Data/Hora do Cadastro',
            LABEL_DATA_SOLICITACAO: 'Data Solicitação',
            LABEL_DESTINATARIO: 'Destinatário',
            LABEL_PRAZO_DIAS: 'Prazo (Dias)',
            LABEL_ENVIO_AGENDAMENTO: 'Envio/Agenda',
            LABEL_DENUNCIANTE: 'Denunciante',
            LABEL_DENUNCIADO: 'Denunciado',
            LABEL_MINHAS_DENUNCIAS: 'Minhas denúncias cadastradas',
            LABEL_MINHAS_DENUNCIAS_RECEBIDAS: 'Denúncias recebidas',
            LABEL_DENUNCIAS_PARA_RELATORIA: 'Denúncias para relatoria',
            LABEL_CEN: 'CEN',
            LABEL_PEDIDO_SUBSTITUICAO: 'Pedido de Substituição',
            LABEL_PEDIDO_IMPUGNACAO: 'Pedido de Impugnação',
            LABEL_QTD_PEDIDOS_SUBSTITUICAO: 'Quantidade de Pedidos de Substituição',
            LABEL_QUANTIDADE_TOTAL_CHAPAS_CADASTRADAS: 'Quantidade Total Chapas Cadastradas',
            LABEL_QTD_IMPUGNACAO_SUBSTITUICAO: 'Quantidade de Pedidos de Impugnação',
            LABEL_QTD_PEDIDOS_JULGADOS_PRIMEIRA_INSTANCIA: 'Pedidos Julgados 1ª Instância',
            LABEL_ACOMPANHAR: 'Acompanhar',
            LABEL_TOTAL_PEDIDOS_SOLICITADOS: 'Total de Pedidos de Substituições:',
            LABEL_TOTAL_PEDIDOS_IMPUG_SOLICITADOS: 'Total de Pedidos de Impugnação(ões):',
            LABEL_PROTOCOLO: 'Protocolo',
            LABEL_HORA_CADASTRO: 'Data/Hora do Cadastro',
            LABEL_NUM_CHAPA: 'Nº Chapa',
            LABEL_ENVIAR_IMPUGNACAO: 'Enviar Impugnação',
            LABEL_EM_ANDAMENTO: 'Em andamento',
            LABEL_DEFERIDO: 'Deferido',
            LABEL_INDEFERIDO: 'Indeferido',
            LABEL_NENHUM_REGISTRO_ENCONTRADO: 'Nenhum registro encontrado!',
            LABEL_PENDENCIA_ENCONTRADA_NO_TRANSCORRER_PROCESSO: 'Pendências identificados no transcorrer do processo eleitoral',
            LABEL_BUSCAR: 'Busca',
            LABEL_VISUALIZAR_SUBSTITUICAO: 'Visualizar Substituição',
            LABEL_ACAO_DETALHAR: 'Detalhar',
            LABEL_SUBSTITUIR_POR: 'Substituir por',
            LABEL_SOLICITAR_SUBSTITUICAO: 'Solicitar Substituição',
            LABEL_JUSTIFICATIVA_PEDIDO_SUBSTITUICAO: 'Justificativa do Pedido de Substituição',
            LABEL_DOCUMENTO: 'Documento',
            LABEL_UF_CHAPA: 'UF da Chapa',
            LABEL_MEMBROS_CADASTRADOS: 'Membros Cadastrados',
            LABEL_MEMBROS_SUBSTITUIDOS: 'Membros Substituídos',
            LABEL_DENUNCIA_ADMISSIBILIDADE: 'Denúncias para admissibilidade',

            LABEL_IMPEDIMENTO_SUSPEICAO: 'Visualizar Impedimento ou Suspeição',
            LABEL_DESCRICAO_IMPEDIMENTO_SUSPEICAO: 'Despacho de designação do relator',
            LABEL_DESIGNACAO_NOVO_RELATOR: 'Designação do novo relator',
            LABEL_NOVO_RELATOR: 'Novo Relator',
            LABEL_USUARIO: "Usuário",

            LABEL_VISUALIZAR_ALEGACAO_FINAL: 'Visualizar Alegações Finais',
            LABEL_SOLICITACAO_ALEGACAO_FINAL: 'Solicitação de Alegações Finais',
            LABEL_RESPOSTA: 'Resposta',


            LABEL_ADMITIR: 'Admitir',
            LABEL_ADMITIDO: 'Admitido',
            LABEL_INADIMITIR: 'Inadimitir',
            LABEL_INADMITIDO: 'Inadmitido',
            LABEL_ADMITIR_DENUNCIA: 'Admitir Denúncia',
            LABEL_INADMITIR_DENUNCIA: 'Inadmitir Denúncia',
            LABEL_APRESENTAR_DEFESA: 'Apresentar Defesa',
            LABEL_ANALISAR_DENUNCIA: 'Analisar Denúncia',
            LABEL_ALEGACOES_FINAIS: 'Alegações Finais',
            LABEL_INSERIR_ALEGACOES_FINAIS: 'Inserir Alegações Finais',
            LABEL_DESCRICAO_CONTRARRAZAO: 'Descrição da Contrarrazão',

            LABEL_INSERIR_PROVAS: 'Inserir Provas',
            LABEL_DESCRICAO_PROVAS_APRESENTADAS: 'Descrição das Provas Apresentadas',

            LABEL_DENUNCIAS: 'Denúncias',
            LABEL_DENUNCIA_SIGILOSA: 'Denúncia Sigilosa',
            LABEL_PERGUNTA_DENUNCIA_SIGILOSA: 'Denúncia Sigilosa?',
            LABEL_DESCRICAO_DEFESA: "Descrição de Defesa",
            LABEL_DESCRICAO_PEDIDO_IMPUGNACAO: 'Descrição do Pedido de Impugnação',
            LABEL_CADASTRAR: "Cadastrar",
            LABEL_CADASTRAR_DEFESA: "Cadastrar Defesa",
            LABEL_REGISTRO_IMPUGNACAO: "Registro",
            LABEL_TIPO_DE_PARTICIPACAO: "Tipo de Participação",
            LABEL_PARTICIPACAO_NA_CHAPA: "Participação na Chapa",
            LABEL_INFORMACOES_IMPUGNANTE: "Informações do Impugnante",
            LABEL_INFORMACOES_IMPUGNADO: 'Informações do Impugnado',
            LABEL_DEFESA: "Defesa",
            LABEL_PARECER: 'Parecer',
            LABEL_IMPUGNANTE: "Impugnante",
            LABEL_NAO_APLICADO: 'N/A',
            LABEL_POSICAO_NA_CHAPA: 'Posição na Chapa',
            LABEL_TOTAL_PEDIDOS_IMPUGNACAO: 'Total de Pedidos de Impugnação:',
            LABEL_JULGAMENTO_PRIMEIRA_INSTANCIA: 'Julgamento 1ª Instância',
            LABEL_JULGAMENTO_PRIMEIRA_INSTANCIA_DENUNCIA: 'Julgamento 1ª Instância',
            LABEL_JULGAMENTO_FINAL_PRIMEIRA_INSTANCIA: '{0}Julgamento{1} 1ª Instância {2}',
            LABEL_JULGAMENTO_SEGUNDA_INSTANCIA: 'Julgamento 2ª Instância',
            LABEL_PROCEDENTE: 'Procedente',
            LABEL_IMPROCEDENTE: 'Improcedente',
            LABEL_RECURSO_RESPONSAVEL: 'Recurso Responsável',
            LABEL_RECONSIDERACAO_RESPONSAVEL: 'Reconsideração Responsável',
            LABEL_RECURSO_IMPUGNANTE: 'Recurso Impugnante',
            LABEL_RECONSIDERACAO_IMPUGNANTE: 'Reconsideração Impugnante',
            LABEL_INTERPOR_RECURSO: "Interpor Recurso",
            LABEL_INTERPOR_RECURSO_RECONSIDERACAO: 'Interpor {0}',
            LABEL_INTERPOR_RECONSIDERACAO: "Interpor Reconsideração",
            LABEL_RESPONSAVEL_CADASTRO: 'Responsável pelo Cadastro',
            LABEL_SEM_MEMBRO_INCLUSAO: 'Sem inclusão de membro',
            LABEL_RECURSO: 'Recurso',
            LABEL_DO_RECURSO: 'do Recurso',
            LABEL_RECONSIDERACAO: "Reconsideração",
            LABEL_DA_RECONSIDERACAO: "da Reconsideração",
            LABEL_RECURSO_DO_JULGAMENTO: 'Recurso do Julgamento',
            LABEL_RECURSO_DO_JULGAMENTO_FINAL: 'Recurso do Julgamento Final',
            LABEL_RECONSIDERACAO_DO_JULGAMENTO_FINAL: 'Reconsideração do Julgamento Final',
            LABEL_RECONSIDERACAO_DO_JULGAMENTO: 'Reconsideração do Julgamento',
            LABEL_RECURSO_PEDIDO_IMPUGNACAO: 'Recurso - Pedido de Impugnação',
            LABEL_RECONSIDERACAO_PEDIDO_IMPUGNACAO: 'Reconsideração - Pedido de Impugnação',
            LABEL_RECURSO_JULGAMENTO: 'Recurso do Julgamento',
            LABEL_RECONSIDERACAO_JULGAMENTO: 'Reconsideração do Julgamento',
            LABEL_RECURSO_PEDIDO_IMPUGNACAO_1_INSTANCIA: 'Recurso do Pedido de Impugnação 1ª Instância',
            LABEL_RECONSIDERACAO_PEDIDO_IMPUGNACAO_1_INSTANCIA: 'Reconsideração do Pedido de Impugnação 1ª Instância',
            LABEL_PESQUISAR_CANDIDATO_SUBSTITUTO: 'Pesquisar Candidato a ser Substituto',
            LABEL_CONTRARRAZAO: "Contrarrazão",
            LABEL_RESPONSAVEL_CHAPA: "Responsável da Chapa",
            LABEL_VISUALIZAR_MEMBROS_CHAPA: 'Visualizar Membros da Chapa',
            LABEL_SEM_INCLUSAO_MEMBRO: 'Sem inclusão de membro',
            LABEL_DATA: "Data",
            LABEL_CONTRARRAZAO_RECURSO: "Contrarrazão do Recurso",
            LABEL_QUANTIDADE_CHAPAS_QUEBRA_LINHA: '{0}Quantidade de{1}Chapas{2}',
            LABEL_QUANTIDADE_CHAPAS_COM_PENDENCIA_QUEBRA_LINHA: '{0}Quantidade de{1}Chapas Com Pendência{2}',
            LABEL_QUANTIDADE_CHAPAS_SEM_PENDENCIA_QUEBRA_LINHA: '{0}Quantidade de{1}Chapas Sem Pendência{2}',
            LABEL_STATUS_CHAPA_QUEBRA_LINHA: '{0}Status da {1}Chapa{2}',
            LABEL_MEMBROS_COM_PENDENCIA: '{0}Membros com{1}Pendência{2}',
            LABEL_PEDIDOS_CADASTRADOS: '{0}Pedidos{1}Cadastrados{2}',
            LABEL_STATUS_DO_JULGAMENTO: '{0}Status do {1}Julgamento{2}',
            LABEL_PESQUISAR_ELEICAO: 'Pesquisar Eleição',
            LABEL_CHAPAS_CADASTRADAS_POR_ESTADO: 'Chapas Cadastradas por Estado',
            LABEL_RECURSO_DO_RESPONSAVEL_PELA_CHAPA: "Recurso do Responsável pela Chapa",
            LABEL_RECONSIDERACAO_DO_RESPONSAVEL_PELA_CHAPA: "Reconsideração do Responsável pela Chapa",
            LABEL_RECURSO_DO_IMPUGNANTE: "Recurso do Impugnante",
            LABEL_RECONSIDERACAO_DO_IMPUGNANTE: "Reconsideração do Impugnante",
            LABEL_RECURSO_PEDIDO_IMPUGNCAO_1_INSTANCIA: "Recurso do Pedido de Impugnação -  1ª Instância",
            LABEL_RECONSIDERACAO_PEDIDO_IMPUGNCAO_1_INSTANCIA: "Reconsideração do Pedido de Impugnação -  1ª Instância",
            LABEL_CONTRARRAZAO_DO_RECURSO: "Contrarrazão do Recurso",
            LABEL_CONTRARRAZAO_RECONSIDERACAO: "Contrarrazão do Reconsideração",
            LABEL_DADOS_CANDIDATO: 'Dados do Candidato',
            LABEL_PEDIDO_DE_SUBSTITUICAO: 'Pedido de Substituição',
            LABEL_RESPONSAVEL_IMPUGNANTE: "Responsável Impugnante",
            LABEL_STATUS_VALIDACAO_SUBSTITUICAO_IMPUGNACAO: 'Status {0} Validação',
            LABEL_STATUS_CONFIRMACAO_SUBSTITUICAO_IMPUGNACAO: 'Status {0} Confirmação',
            LABEL_JULGAR_DENUNCIA: 'Parecer da Denúnica',
            LABEL_PARECER_FINAL: 'Parecer Final',
            LABEL_JULGAMENTO: "Julgamento",
            LABEL_VALOR_PERCENT_MULTA: "Valor Percentual da Multa",
            LABEL_QUANTIDADE_DIAS: 'Qtde Dias',
            LABEL_RELACAO_ANUIDADE: '(Em relação à anuidade)',
            LABEL_INSERIR_MULTA: 'Inserir Multa?',
            LABEL_PARECER_FINAL_ALEGACAO_NAO_RESPONDIDA: 'Prezado(a) uma das partes envolvidas ainda não respondeu a alegação final',
            LABEL_RECURSO_DENUNCIADO: 'Recurso do Denunciado',
            LABEL_RECURSO_DENUNCIANTE: 'Recurso do Denunciante',
            LABEL_ABA_RECURSO_DENUNCIANTE: 'Recurso Denunciante',
            LABEL_ABA_RECURSO_DENUNCIADO: 'Recurso Denunciado',
            LABEL_CONTRARRAZAO_DENUNCIADO: 'Contrarrazão do Denunciado',
            LABEL_CONTRARRAZAO_DENUNCIANTE: 'Contrarrazão do Denunciante',
            LABEL_CADASTRAR_CONTRARRAZAO: 'Cadastrar Contrarrazão',
            LABEL_RECURSO_RECONSIDERACAO: 'Solicitar Recurso/Reconsideração',
            LABEL_ACRESCIDO_MULTA: 'acrescido de multa',
            LABEL_MULTA_ANUIDADE: 'em relação à anuidade',
            LABEL_PEDIDO_SUBSTITUICAO_JULGAMENTO_FINAL: 'Pedido Substituição',
            LABEL_RECURSO_SUBSTITUICAO_JULGAMENTO_FINAL: 'Recurso do Pedido Substituição',
            LABEL_RECONSIDERACAO_SUBSTITUICAO_JULGAMENTO_FINAL: 'Reconsideração do Pedido Substituição',
            LABEL_IMPUGNACAO_RESULTADO: '{0}Acompanhar Impugnação{1} de Resultado{2}',
            LABEL_PARAMETRIZACAO_CALENDARIO_IMPUGNACAO_RESULTADO: 'Impugnação de Resultado Eleição',
            TITLE_TOTAL_PEDIDOS_IMPUGNACAO_RESULTADO_ESTADO: 'Pedido (s) de Impugnação (ões) Cadastrado (s)',

            TITLE_PEDIDOS_CADASTRADOS: 'Pedidos Cadastrados',
            LABEL_CHAPA_PENDENCIA_VOLTAR: 'Voltar',
            LABEL_ABA_CHAPA_PENDENCIA: '{0}Acompanhar{1}Chapa{2}',
            LABEL_CHAPA_PENDENCIA_PEDIDO_DENUNCIA: '{0}Pedidos de{1}Denúncia{2}',
            LABEL_CHAPA_PENDENCIA_PEDIDO_IMPUGNACAO: '{0}Pedidos de{1}Impugnação{2}',
            LABEL_CHAPA_PENDENCIA_SEM_PEDIDO_DENUNCIA: 'Não possui pedidos de Denúncia',
            LABEL_CHAPA_PENDENCIA_PEDIDO_SUBSTITUICAO: '{0}Pedidos de{1}Substituição{2}',
            LABEL_CHAPA_PENDENCIA_SEM_PEDIDO_IMPUGNACO: 'Não possui pedidos de Impugnação',
            LABEL_CHAPA_PENDENCIA_SEM_PEDIDO_SUBSTITUICAO: 'Não possui pedidos de Substituição',

            LABEL_REGISTRAR_AUDIENCIA_INSTRUCAO: "Registrar Audiência de Instrução",
            LABEL_DATA_AUDIENCIA: "Data da audiência",
            LABEL_HORA_AUDIENCIA: "Hora da audiência",
            LABEL_DESCRICAO_AUDIENCIA_INSTRUCAO: "Descrição da  Audiência de Instrução",
            LABEL_AUDIENCIA_INSTRUCAO_REGISTRADA: "Audiência de Instrução registrada",
            LABEL_VISUALIZAR_AUDIENCIA_INSTRUCAO: "Visualizar Audiência de Instrução",
            LABEL_DATA_HORA_AUDIENCIA: "Data/Hora da Audiência",
            LABEL_MEMBRO_SOLICITACAO_RECURSO: 'Membros com Solicitação de Recurso',
            LABEL_MEMBRO_SOLICITACAO_RECONSIDERACAO: 'Membros com Solicitação de Reconsideração',
            LABEL_JULGAMENTO_FINAL: "Julgamento Final",
            LABEL_SUBSTITUICAO: "Substituição",
            LABEL_NAO_HOUVE_PEDIDO_SUBSTITUICAO: "Não houve pedido de substituição!",
            LABEL_FEDERAL: 'Federal',
            LABEL_VISUALIZAR_CHAPAS: 'Visualizar Chapas',
            LABEL_VISUALIZAR_CHAPA: 'Visualizar Chapa',

            TITLE_ARQUIVO: 'Arquivo',
            TITLE_JULGAMENTO: 'Julgamento',
            TITLE_ARQUIVOS: 'Arquivos',
            LABEL_VISUALIZAR_PRODUCAO_PROVAS: "Visualizar Produção de Provas",
            LABEL_PROVAS_INSERIDAS: "Provas inseridas",
            LABEL_NAO_HOUVE_INSERCAO_PROVAS_PELO_DESTINATARIO: "Não houve inserção de provas pelo destinatário.",
            LABEL_ENCAMINHAMENTO_FECHADO: "Encaminhamento fechado",
            LABEL_DATA_HORA_FECHAMENTO: "Data e hora do fechamento",
            LABEL_DATA_HORA_DO_CADASTRO: "Data e hora do Cadastro",

            LABEL_CADASTRADO_POR: "Cadastrado por",
            LABEL_DESCRICAO_ACAO_EXECUTADA: "Descrição da ação executada",
            LABEL_PERIODO_SUSPENSAO: "Periodo de Suspensão",
            LABEL_MULTA: "Multa",
            LABEL_PERCENTUAL_MULTA: "Percentual da Multa",
            LABEL_SENTENCA_ADVERTENCIA: "Advertência",
            LABEL_SENTENCA_SUSPENSAO: "Suspensão de propaganda",
            LABEL_SENTENCA_CASSACAO: "Cassação do registro de candidatura",
            LABEL_SENTENCA_MULTA: "Multa",
            LABEL_SENTENCA_OUTRAS: "Outras adequadas e proporcionais ao grau da infração cometida",
            
            LABEL_HISTORICO_RELATORES_DENUNCIA: 'Histórico de Relatores da Denúncia',
            LABEL_DESPACHO_DESIGNACAO: 'Despacho de Designação',
            LABEL_DESPACHO_DESIGNACAO_RELATOR: 'Despacho de Designação do Relator',
            LABEL_VISUALIZAR_HISTORICO: 'Visualizar Histórico',
            LABEL_DADOS_ADMISSIBILIDADE: 'Dados da Admissibilidade',
            LABEL_DESCRICAO_JULGAMENTO_RECURSO: 'Descrição do Julgamento do Recurso',
            LABEL_JULGAMENTO_SUBSTITUICAO: '{0}Julgamento{1} da Substituição {2}',
            LABEL_JULGAMENTO_RECURSO: '{0}Julgamento{1} {2} {3}',
            LABEL_REGISTRO_PEDIDO_SUBSTITUICAO: 'Registro do Pedido de Substituição',
            LABEL_JULGAMENTO_PEDIDO_SUBSTITUICAO: 'Julgamento do Pedido de Substituição',
            LABEL_INTERPOR_RECURSO_RECONSIDERACAO_PEDIDO_SUBISTUICAO: 'Interpor {0} - Pedido de Substituição',
            LABEL_DESCRICAO_JULGAMENTO_RECONSIDERACAO: 'Descrição do Julgamento de Reconsideração',
            LABEL_O_RECURSO: 'o Recurso',
            LABEL_A_RECONSIDERACAO: 'a Reconsideração',
            LABEL_SUBSTITUICAO_SOLICITADA_PELO_RESPONSAVEL_CHAPA: 'Substituição solicitada pelo Responsável da Chapa',
            LABEL_REGISTRO_RECURSO_PEDIDO_SUBSTITUICAO: 'Registro do Recurso do Pedido de Substituição',
            LABEL_JUSTIFICATIVA_RECURSO_PEDIDO_SUBSTITUICAO: 'Justificativa do Recurso do Pedido de Substituição',
            LABEL_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Reconsideração do Pedido de Substituição',
            LABEL_REGISTRO_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Registro da Reconsideração do Pedido de Substituição',
            LABEL_JUSTIFICATIVA_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Justificativa da Reconsideração do Pedido de Substituição',
            LABEL_HISTORICO_JULGAMENTO_PEDIDO_SUBSTITUICAO: 'Histórico do Julgamento do Pedido de Substituição',
            LABEL_REGISTRO_JULGAMENTO: 'Registro do Julgamento',
            LABEL_DESCRICAO_RECURSO_PEDIDO_SUBSTITUICAO: 'Descrição do Recurso do Pedido de Substituição',
            LABEL_DESCRICAO_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Descrição do Reconsideração do Pedido de Substituição',
            LABEL_REGISTRO_JULGAMENTO_SUBSTITUICAO: 'Registro do Julgamento da Substituição',
            LABEL_REGISTRO_JULGAMENTO_RECURSO_SUBSTITUICAO: 'Registro do Julgamento do Recurso da Substituição',
            LABEL_JULGAMENTO_RECURSO_PEDIDO_SUBSTITUICAO: 'Julgamento do Recurso do Pedido de Substituição',
            LABEL_JULGAMENTO_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Julgamento de Reconsideração do Pedido de Substituição',
            LABEL_SOLICITAR_RECURSO_RECONSIDERACAO_SUBSTITUICAO: 'Solicitar {0} da  Substituição',
            LABEL_RECURSO_PEDIDO_SUBSTITUICAO: 'Recurso do Pedido de Substituição',
            LABEL_RETIFICACAO_JULGAMENTO_FINAL: "Retificação do Julgamento Final",

            LABEL_ALEGACOES: 'Alegações',
            LABEL_CADASTRAR_RECURSO: 'Cadastrar Recurso',
            LABEL_CADASTRAR_RECONSIDERACAO: 'Cadastrar Reconsideração',
            LABEL_DATA_CADASTRO: 'Data e hora do cadastro: ',
            LABEL_DETALHAMENTO_JULGAMENTO: 'Detalhamento do julgamento',
            LABEL_NUMERO_IMPUGNACAO_RESULTADO: 'N° Pedido de Impugnação de Resultado: ',
            LABEL_ABA_JULGAMENTO_PRIMEIRA_INSTANCIA: '{0}Julgamento {1} 1ª Instância {2}',
            LABEL_JULGAMENTO_IMPUGNACAO_RESULTADO_PRIMEIRA_INSTANCIA: 'Julgamento das Alegações do Pedido de Impugnação de Resultado - 1ª instância',
            LABEL_ABA_RECURSO_JULGAMENTO_IMPUGNANTE: '{0}Recurso {1} Impugnante {2}',
            LABEL_ABA_RECONSIDERACAO_JULGAMENTO_IMPUGNANTE: '{0}Reconsideração {1} Impugnante {2}',
            LABEL_ABA_RECURSO_JULGAMENTO_IMPUGNADO: '{0}Recurso {1} Impugnado {2}',
            LABEL_ABA_RECONSIDERACAO_JULGAMENTO_IMPUGNADO: '{0}Reconsideração {1} Impugnado {2}',
            LABEL_ABA_JULGAMENTO_SEGUNDA_INSTANCIA: '{0}Julgamento {1} 2ª Instância {2}',
            LABEL_JULGAMENTO_IMPUGNACAO_RESULTADO_SEGUNDA_INSTANCIA: 'Julgamento do Pedido de Impugnação Resultado - 2ª instância',
            LABEL_INTERPOSICAO_RECONSIDERACAO: 'Não houve Interposição de Reconsideração',

            LABEL_NOTIFICACOES: 'Notificações',
            LABEL_INSERIR_RELATOR: 'Inserir Relator',
            LABEL_ARQUIVO_INVALIDO: 'Arquivo Inválido',
            LABEL_ARQUIVO_GRANDE: 'Arquivo deve ter no máximo 25MB',
            LABEL_DESCRICAO_RECURSO_ADMISSIBILIDADE: 'Descrição do Recurso',
            LABEL_RECURSO_ADMISSIBILIDADE: 'Solicitação de Recurso',
            LABEL_REALIZAR_RECURSO: 'Realizar Recurso',
            LABEL_RECURSO_DE_ADMISSIBILIDADE: 'Recurso de Admissibilidade',
            LABEL_DESCRICAO_RECURSO_JULGAMENTO_ADMISSIBILIDADE: 'Descrição do Recurso de admissibilidade',
            LABEL_JULGAMENTO_RECURSO_ADMISSIBILIDADE: 'Julgamento Recurso de Admissibilidade',
            LABEL_IMPROVIDO: 'Improvido',
            LABEL_PROVIDO: 'Provido',

            LABEL_ACOMPANHAR_IMPUGNACAO_RESULTADO: "Acompanhar Impugnação de Resultado",
            LABEL_AGUARDANDO_ALEGACOES: "Aguardando Alegações",
            LABEL_TABLE_FILTRO_VAZIO: 'Selecione o(s) filtro(s) para a nova pesquisa',

            LABEL_NUMERO_PEDIDO_IMPUGNACAO: 'Nº do Pedido de Impugnação',
            LABEL_DESCRICAO_DA_RECONSIDERACAO: 'Descrição da Reconsideração',
            LABEL_DESCRICAO_DO_RECURSO: 'Descrição do Recurso',

            LABEL_CONTRARRAZAO_RUCURSO_JULGAMENTO_1_INSTANCIA: "Contrarrazão - Recurso do Julgamento 1ª Instância",
            LABEL_CONTRARRAZAO_RECONSIDERACAO_JULGAMENTO_1_INSTANCIA: "Contrarrazão - Reconsideração do Julgamento 1ª Instância",
            LABEL_N_DO_PEDIDO_IMPUGNACAO: "Nª do pedido de impugnação",

            LABEL_DESCRICAO_DOCUMENTO: "Descrição/Documento",

            LABEL_SELECIONE_OPCAO_DESEJADA_ALTERACAO_JULGAMENTO: "Prezado(a), selecione a opção desejada para alteração do Julgamento:",
            LABEL_OPCAO_ALTERAR_DESICAO_JULGAMENTO: "Decisão do Julgamento",
            LABEL_OPCAO_ALTERAR_CONTEUDO_JULGAMENTO: "Conteúdo do Julgamento",
            LABEL_PREZADO_TEM_CERTEZA_DESEJA_ALTERAR_CONTEUDO_JULGAMENTO: "Prezado(a), tem certeza que deseja alterar o conteúdo do julgamento?",
            LABEL_PREZADO_TEM_CERTEZA_DESEJA_ALTERAR_DECISAO_JULGAMENTO: "Prezado(a), tem certeza que deseja alterar a decisão do julgamento?",
            LABEL_CONFIRMACAO_ALTERACAO_JULGAMENTO_1_INSTANCIA: "Confirmação da Alteração do Julgamento Final - 1ª Instância",
            LABEL_RETIFICAR: 'Retificar',
            LABEL_RETIFICADO: 'Retificado (s)',
            LABEL_JULGAMENTO_RETIFICADO: 'Julgamento Retificado',

            LABEL_INTERPOSICAO_RECURSO: "Não houve Interposição de Recurso",
            LABEL_RECURSO_IMPUGNADO: "Recurso Impugnado",
            LABEL_RECONSIDERACAO_IMPUGNADO: "Reconsideração Impugnado",
            LABEL_DESCRICAO_RECURSO: "Descrição do Recurso",
            LABEL_DESCRICAO_RECONSIDERACAO: "Descrição da Reconsideração",
            LABEL_QUANTIDADE_CALENDARIOS: 'Total de Calendários:  ',
            LABEL_JULGAMENTO_2_INSTANCIA: "Julgamento 2º Instância",
            LABEL_JULGAMENTO_1_INSTANCIA: "Julgamento 1º Instância",
            LABEL_CONTRARRAZAO_RECURSO_RECONSIDERACAO: 'Contrarrazão {0}',
            LABEL_N_IMPUGNACAO_DE_RESULTADO: 'Nº Impugnação de Resultado',
            LABEL_PARAMETRIZACAO_PROCESSO_ELEITORAL: 'Processo Eleitoral',
            LABEL_RECURSO_RECONSIDERACAO_DO_IMPUGNANTE:'{0} do Impugnante',
            LABEL_CONTRARRAZAO_IMPUGNANTE: "Contrarrazão Impugnante",
            LABEL_CONTRARRAZAO_IMPUGNANDO: "Contrarrazão Impugnado",
            LABEL_NAO_HOUVE_CADASTRO_CONTRARRAZAO: 'Não houve cadastro de contrarrazão.',
            LABEL_TIPO_PARTICIPACAO_REPRESENTATIVIDADE: 'Participação/Representatividade',
            LABEL_REPRESENTATIVIDADE: 'Representatividade',
            LABEL_SEM_REPRESENTATIVIDADE: 'Não integro em nenhum dos grupos de representatividade.',

            TITLE_JULGADO: 'Julgado',
            TITLE_FECHADO: 'Fechado',
            TITLE_INSERIR: 'Inserir',
            TITLE_PENDENTE: 'Pendente',
            TITLE_CONCLUIDO: 'Concluído',
            TITLE_ALEGACOES: 'Alegações',
            TITLE_QTDE_DIAS: 'Qtde Dias',
            TITLE_DECLARACAO: 'Declaração',
            TITLE_VISUALIZAR: 'Visualizar',
            TITLE_FORMULARIO: 'Formulário',
            TITLE_TRANSCORRIDO: 'Transcorrido',
            TITLE_SUBSTITUICAO: 'Substituição',
            TITLE_TEXTO_INICIAL: 'Texto Inicial',
            TITLE_JUSTIFICATIVA: 'Justificativa',
            TITLE_INSERIR_PROVAS: 'Inserir Provas',
            TITLE_INSERIR_RELATOR: 'Inserir Relator',
            TITLE_SANCAO_APLICADA: 'Sanção Aplicada',
            TITLE_NARRACAO_FATOS: 'Narração dos Fatos',
            TITLE_CADASTRO_CHAPAS: 'Cadastro de Chapa',
            TITLE_INSERIR_DOCUMENTO: 'Inserir Documento',
            TITLE_CADASTRAR_ALEGACAO: 'Cadastrar Alegação',
            TITLE_ABA_IMPUGNANTE: '{0}{1} {2}Impugnante{3}',
            TITLE_VISUALIZAR_ALEGACAO: 'Visualizar Alegação',
            TITLE_REGISTRAR_AUDIENCIA: 'Registrar Audiência',
            TITLE_ABA_RESPONSAVEL: '{0}{1} {2}Responsável{3}',
            TITLE_INFORMACOES_PESSOAIS: 'Informações Pessoais',
            TITLE_CONSULTAR_DECLARACAO: 'Consultar Declaração',
            TITLE_CADASTRAR_DECLARACAO: 'Cadastrar Declaração',
            TITLE_PEDIDO_DE_IMPUGNACAO: 'Pedido de Impugnação',
            TITLE_JULGAMENTO_COMISSAO: 'Julgamento da Comissão',
            TITLE_VISUALIZAR_DECLARACAO: 'Visualizar Declaração',
            TITLE_JULGAMENTO_DENUNCIADO: 'Julgamento Denunciado',
            TITLE_PENDECIAS_MEMBRO: 'Pendências de Membro Chapa',
            TITLE_DESCRICAO_JULGAMENTO: 'Descrição do Julgamento',
            TITLE_JULGAMENTO_DENUNCIANTE: 'Julgamento Denunciante',
            TITLE_PEDIDO_DE_SUBSTITUICAO: 'Pedido de Substituição',
            TITLE_PARAMETRIZAR_DECLARACAO: 'Parametrizar Declaração',
            TITLE_INFORMACOES_IMPORTANTES: 'Informações Importantes',
            TITLE_PEDIDO_SUBSTITUICAO: 'Pedido de <br/> Substituição',
            TITLE_VALOR_PERCENTUAL_MULTA: 'Valor Percentual de Multa',
            TITLE_DETALHAMENTO_JULGAMENTO: 'Detalhamento do Julgamento',
            TITLE_INFORMACOES_DO_SUBSTITUTO: 'Informações do Substituto',
            TITLE_ABA_PEDIDO_IMPUGNACAO: '{0}Pedido de {1}Impugnação{2}',
            TITLE_ABA_RECURSO_RESPONSAVEL: '{0}Recurso{1} {2}Responsável',
            TITLE_PARECER_JULGAMENTO_FINAL: 'Parecer do Julgamento Final',
            TITLE_INFORMACOES_DO_SUBSTITUIDO: 'Informações do Substituído',
            TITLE_INTERPOR_RECURSO_DOCUMENTO: 'Interpor Recurso/Documento',
            TITLE_SUBSTITUICAO_MEMBRO_JULGAMENTO: 'Solicitar Substituição',
            TITLE_DEFINICAO_TIPO_CANDIDATURA: 'Definição Tipo de Candidatura',
            TITLE_ABA_PEDIDO_DE_SUBSTITUICAO: '{0}Pedido de {1}Substituição{2}',
            TITLE_RECURSO_RECONSIDERACAO: 'Solicitar Recurso ou Reconsideração',
            TITLE_JULGAMENTO_RECURSO_SEGUNDA_INSTANCIA: 'Julgamento do Recurso',
            TITLE_ACOMPANHAR_PEDIDO_IMPUGNACAO: 'Acompanhar Pedidos de Impugnação',
            TITLE_PEDIDOS_IMPUGNACAO_POR_ESTADO: 'Pedidos de Impugnação por Estado',
            TITLE_RECURSO_PEDIDO_DE_SUBSTITUICAO: 'Recurso - Pedido de Substituição',
            TITLE_RECURSO_RECONSIDERACAO_JULGAMENTO_FINAL: '{0} do Julgamento Final',
            TITLE_PARECER_PEDIDO_DE_SUBSTITUICAO: 'Parecer do Pedido de Substituição',
            TITLE_CONFIRMACAO_PEDIDO_SUBSTITUICAO: 'Confirmar Pedido de Substituição',
            TITLE_CADASTRAR_IMPUGNACAO_RESULTADO: 'Cadastrar Impugnação de Resultado',
            TITLE_PEDIDO_IMPUGNACAO_CANDIDATURA: 'Pedido de Impugnação de Candidatura',
            TITLE_CONFIRMAR_PEDIDO_DE_SUBSTITUICAO: 'Confirmar Pedido de Substituição',
            TITLE_ABA_RECONSIDERACAO_RESPONSAVEL: '{0}Reconsideração{1} {2}Responsável',
            TITLE_ABA_JULGAMENTO_SEGUNDA_INSTANCIA: '{0}Julgamento {1} 2ª Instância{2}',
            TITLE_PEDIDO_SUBSTUICAO_CANDIDATURA: 'Pedido de Substituição de Candidatura',
            TITLE_INTERPOR_RECONSIDERACAO_DOCUMENTO: 'Interpor Reconsideração/Documento',
            TITLE_INTERPOR_RECURSO_IMPUGNACAO: 'Interpor Recurso - Pedido de Impugnação',
            TITLE_DECLARACAO_PREENCHIDA_COM_SUCESSO: 'Declaração preenchida com sucesso!',
            TITLE_ABA_JULGAMENTO_PRIMEIRA_INSTANCIA: '{0}Julgamento {1} 1ª Instância {2}',
            TITLE_PEDIDO_DE_SUBSTITUICAO_IMPUGNACAO: 'Pedido de Substituição - Impugnação',
            TITLE_REALIZAR_SUBSTITUICAO_DE_CANDIDATO: 'Realizar Substituição de Candidato',
            TITLE_PEDIDO_SUBSTITUICAO_CANDIDATURA: 'Pedido de Substituição de Candidatura',
            TITLE_DECLARACAO_MEMBRO_COMISSAO: 'Declaração para Membros da Comissao Eleitoral',
            TITLE_JULGAMENTO_RECONSIDERACAO_SEGUNDA_INSTANCIA: 'Julgamento da Reconsideração',
            TITLE_DECLARACAO_CONCLUSAO_CHAPA: 'Declaração para conclusão de registro de chapa',
            TITLE_ACOMPANHAR_IMPUGNACAO_RESULTADO: '{0}Acompanhar Impugnação de {1}Resultado{2}',
            TITLE_CONFIRMACAO_SOLICITACAO_IMPUGNACAO: 'Confirmação da Solicitação de Impugnação',
            TITLE_RECONSIDERACAO_PEDIDO_DE_SUBSTITUICAO: 'Reconsideração - Pedido de Substituição',
            TITLE_JULGAMENTO_FINAL_PRIMEIRA_INSTANCIA: 'Julgamento Final das Chapas - 1ª Instância',
            TITLE_CONFIRMACAO_SOLICITACAO_SUBSTITUICAO: 'Confirmação da Solicitação de Substituição',
            TITLE_PARECER_RECURSO_PEDIDO_SUBSTITUICAO: 'Parecer do Recurso do Pedido de Substituição',
            TITLE_PARECER_RECURSO_DE_SUBSTITUICAO_DOCUMENTO: 'Parecer {0} de Substituição / Documento',
            TITLE_INTERPOR_RECONSIDERACAO_IMPUGNACAO: 'Interpor Reconsideração - Pedido de Impugnação',
            TITLE_CONFIRMAR_RECURSO_RECONSIDERACAO_SUBSTITUICAO: 'Confirmar {0} do Pedido de Substituição',
            TITLE_NAO_EXISTE_DEFESA_IMPUGNACAO: 'Prezado(a), não existe nenhuma defesa cadastrada para esse pedido de impugnação.',
            TITLE_ACOMPANHAR_PEDIDO_SUBSTITUICAO_CANDIDATURA: 'Acompanhar Pedido de Substituição de Candidatura',
            TITLE_VISUALIZAR_PEDIDO_SUBSTITUICAO_CANDIDATURA: 'Visualizar Pedido de Substituição de Candidatura',
            TITLE_VISUALIZAR_PEDIDO_SUBSTITUICAO_CANDIDATURA_IES: 'Visualizar Pedido de Substituição de Candidatura IES',
            TITLE_JUSTIFICATIVA_PEDIDO_SUBSTITUICAO_DOCUMENTO: 'Justificativa Pedido de substituição / Documento',
            TITLE_PARECER_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Parecer da Reconsideração do Pedido de Substituição',
            TITLE_SELECIONE_CANDITADO_PARA_SOLICITACAO_RECURSO: 'Selecione Cantidado(s) para Solicitação de Recurso',

            TITLE_JULGAMENTO_PEDIDO_SUBSTITUICAO_PRIMEIRA_INSTANCIA: 'Julgamento do Pedido de Substituição de Candidatura - 1ª Instância',
            TITLE_JULGAMENTO_PEDIDO_IMPUGNACAO_SEGUNDA_INSTANCIA: 'Julgamento de Pedido de Impugnação - 2ª Instância',

            TITLE_JULGAMENTO_PEDIDO_IMPUGNACAO_PRIMEIRA_INSTANCIA: 'Julgamento de Pedido de Impugnação - 1ª Instância',
            TITLE_VISUALIZAR_PARECER_RECURSO_PEDIDO_SUBSTITUICAO: 'Julgamento do Recurso de Substituição de - 2ª Instância',
            TITLE_JULGAMENTO_SUBSTITUICAO_SEGUNDA_INSTANCIA: 'Julgamento do Recurso do Pedido de Substituição - 2ª instância',
            TITLE_SELECIONE_CANDITADO_PARA_SOLICITACAO_RECONSIDERACAO: 'Selecione Cantidado(s) para Solicitação de Reconsideracao',
            TITLE_JULGAMENTO_PEDIDO_IMPUGNACAO_SEGUNDA_INSTANCIA_IMPUGNACAO: 'Julgamento do {0} do Pedido de Impugnação - 2ª Instância',

            TITLE_JULGAMENTO_PEDIDO_SUBSTITUICAO_SEGUNDA_INSTANCIA: 'Julgamento do Pedido de Substituição de Candidatura - 2ª Instância',
            TITLE_VISUALIZAR_PARECER_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Julgamento do Reconsideração de Substituição de - 2ª Instância',
            TITLE_JULGAMENTO_SUBSTITUICAO_SEGUNDA_INSTANCIA_RECONSIDERACAO: 'Julgamento da Reconsideração do Pedido de Substituição - 2ª instância',

            TITLE_RECURSO_RECONSIDERACAO_JULGAMENTO_PRIMEIRA_INSTANCIA: '{0} - Julgamento 1ª Instância',

            TITLE_CADASTRAR_CONTRARRAZAO: "Cadastrar Contrarrazão",
            TITLE_VISUALIZAR_RECURSO: "Visualizar Recurso",
            TITLE_VISUALIZAR_RECONSIDERACAO: "Visualizar Reconsideração",

            TITLE_CONTRARRAZAO_IMPUGNADO: 'Contrarrazão Impugnado',

            MSG_HINT_INFORMATIVO_DOCUMENTO_DENUNCIA: 'São permitidos até 5 arquivos de 25 MB nos formatos: pdf, zip, rar, doc, docx, xls, xlsx, mp4, avi, wmv, mp3, wav, jpg, jpeg ou png.',
            MSG_HINT_INFORMATIVO_DOCUMENTO_RECURSO: 'São permitidos até 5 arquivos de 25 MB nos formatos: pdf, zip, rar, doc, docx, xls, xlsx, mp4, avi, wmv, mp3, wav, jpg, jpeg ou png.',
            MSG_NAO_ENCONTRADOS_REGISTROS_CADASTRADOS_TIPO_DENUNCIA: 'Não foram encontrados registros cadastrados para o tipo de denúncia.',
            MSG_NAO_HOUVE_APRESENTACAO_DEFESA_DENUNCIA: 'Não houve apresentação de defesa para esta denúncia.',
            MSG_ALERTA_DENUNCIA_SIGILOSA: 'Prezado(a) Arquiteto(a) e Urbanista, ao selecionar sigilo, as informações do denunciante serão ocultadas para esta denúncia no ambiente profissional do sistema.',
            MSG_PEDIDO_DENUNCIA_CADASTRADO_COM_EXITO: 'Prezado(a) Arquiteto(a) e Urbanista seu pedido de denúncia foi cadastrado com êxito e foi gerado o número {0} de acompanhamento.',
            MSG_DENUNCIA_ADMITIDA_RELATOR_SELECIONADO_COM_EXITO: 'Prezado (a), a denúncia nº {0} foi admitida com sucesso e o relator selecionado com êxito.',
            MSG_DENUNCIA_INADMITIDA_COM_EXITO: 'Prezado (a), a denúncia nº {0} foi inadmitida com sucesso.',
            MSG_DEFESA_CADASTRADA_COM_EXITO: 'Prezado (a), sua defesa foi cadastrada com êxito para a denúncia nº {0}.',
            MSG_DADOS_CADASTRADOS_COM_EXITO: 'Prezado(a), dados cadastrados com êxito para a denúncia nº {0}.',
            MSG_EXISTE_AUDIENCIA_INSTRUCAO_PENDENTE_DESEJA_CONTINUAR: 'Existe audiência de instrução pendente. Deseja continuar?',
            MSG_ENCAMINHAMENTOS_PENDENTES_DESEJA_FECHAR_CONCLUIR_SOLICITACAO: 'Prezado(a), o(s) encaminhamento(s) {0} está(ão) pendente(s). Deseja fechá-lo(s) para concluir a solicitação?',
            MSG_PREZADO_RECURSO_RECONSIDERACAO_PEDIDO_SUBSTIUTICAO_CADASTRADO: 'Prezado(a) sr(a), {0} do Pedido de Substituição foi Cadastrado com Sucesso!',

            MSG_INCLUA_DECLARACAO_FORMULARIO: 'Não foi possível realizar o cadastro, inclua uma declaração no formulário',
            MSG_DECLARACAO_CADASTRADA_SUCESSO: 'Declaração cadastrada com sucesso!',
            MSG_CONFIRMA_EXCLUIR_REGISTRO: 'Deseja realmente excluir registro?',
            MSG_NAO_HA_MEMBROS_INDICADOS_RECURSO: 'Não há membros/posição indicados para recurso',
            MSG_NAO_HA_MEMBROS_INDICADOS_RECONSIDERACAO: 'Não há membros/posição indicados para reconsideração',
            MSG_CONFIRMA_VOLTAR: 'Deseja realmente voltar? Dados não salvos serão perdidos!',
            MSG_CONFIRMA_DESEJA_CONCLUIR_DENUNCIA_ANTERIOR: 'Deseja concluir o cadastro da denúncia anterior?',
            MSG_CONFIRMA_EXCLUSAO_ARQUIVO: 'Deseja realmente excluir o arquivo?',
            MSG_DADOS_INFORMADOS_SERAO_PERDIDOS_CANCELAR: 'Os dados informados serão perdidos. Deseja realmente cancelar o cadastro?',
            MSG_CONFIRMA_MUDAR_ABA: "Deseja realmente mudar de Aba?</br> Dados não salvos serão perdidos!",
            MSG_HABILITAR_EXTENSAO_ARQUIVO: 'Por gentileza, habilite a opção de extensão de arquivo desejada!',
            MSG_CONFIRMA_DESATIVAR_DECLARACAO: 'A Declaração {0} está sendo utilizada, deseja realmente desativar?',
            MSG_DESEJA_SAIR_SISTEMA: 'Deseja sair do Sistema?',
            MSG_SELECAO_RESPOSTA: 'Por gentileza, selecione uma resposta!',
            MSG_PROTOCOLO_CADASTRO_DENUNCIA: 'Prezado(a) Arquiteto(a) e Urbanista seu pedido de denúncia foi cadastrado com êxito e foi gerado o número {0} de acompanhamento.',
            MSG_DECLARACAO_CONVITE_MEMBRO_COMISSAO: 'Parabéns, você foi convidado a participar das eleições como membro da comissão eleitoral',
            MSG_DECLARACAO_RECUSAR_CONVITE_MEMBRO_COMISSAO: 'Você deseja realmente recusar o convite para participar como membro da comissão eleitoral',
            MSG_DECLARACAO_MEMBRO_COMISSAO_ACEITAR_TERMO: 'Como membro da comissão, será necessário aceitar alguns termos para finalizar o processo de Aceite',
            MSG_DECLARACAO_PREENCHIDA_COM_SUCESSO: 'Declaração preenchida com sucesso! Parabéns! Agora você é um membro da Comissão Eleitoral',
            MSG_DECLARACAO_REJEITOU_CONVITE: 'Você rejeitou o convite para participação da Comissão Eleitoral ',
            MEMBROS_COMISSAO_ELEITORAL: 'Membros da Comissão Eleitoral',
            MSG_SEM_ACESSO: 'Prezado (a) arquiteto (a) e urbanista, você não possui acesso a esse item de menu.',
            MSG_SEM_ACESSO_CADASTRO_DENUNCIA: 'O período para Cadastro de Denúncia não está vigente para nenhum processo eleitoral.',
            MSG_NAO_ENCONTRADAS_DENUNCIAS_ATUAL_RELATOR: 'Não foram encontradas denúncias para as quais você seja o atual relator.',
            MSG_NAO_POSSIVEL_DUPLICAR_TESTEMUNHAS: 'Não é possível duplicar os dados das testemunhas. Favor revisá-los.',
            MSG_QTD_MAXIMA_UPLOAD: 'Tamanho máximo de 10 arquivos excedido!',
            MSG_QTD_MAXIMA_UPLOAD_5: 'Tamanho máximo de 5 arquivos excedido!',
            MSG_QTD_MAXIMA_UPLOAD_1: 'Permissão de Upload: um (1) arquivo!',
            MSG_SUCESSO_PARTICIPACAO: 'Participação da Comissão Eleitoral Concluída com Sucesso',
            MSG_CAMPO_OBRIGATORIO: 'Campos obrigatórios',
            MSG_LISTA_MEMBROS_PENDENCIA: 'Lista dos membros com pendência',
            MSG_SELECAO_REPRESENTACAO_CHAPA: 'Prezado(a) Arquiteto(a) e Urbanista, <br/> Para registro de candidatura de chapa de conselheiros e respectivos suplentes, por favor <br/> selecione a representação à qual deseja registrar sua chapa.',
            MSG_CANCELAR_CADASTRO_CHAPA: 'Deseja realmente cancelar?<br> Todos os dados preenchidos na(s) etapa(s) anterior(es) será(ão) excluído(s) permanentemente do Sistema Eleitoral.',
            MSG_CONFIRMAR_ENVIO_CONVITES_MEMBROS_CADASTRADOS: 'Ter ciência que os convites enviados para os membros cadatrados na etapa anterior',
            MSG_CONFIRMAR_TERMO_RESOLUCAO: 'Ter conhecimento dos termos de resolução',
            MSG_SEM_PERIODO_CADASTRO_CHAPA: 'Não existe período vigente para cadastro de chapa.',
            MSG_UF_SEM_ELEICAO_ATIVA: 'A sua UF não possui eleição Ativa, no exato momento!',
            MSG_PLATAFORMA_ELEITORAL_INCLUIDA: 'Dados da Plataforma Eleitoral incluídos com sucesso! <br/>O sr.(a) ainda necessita Confirmar a criação da Chapa, <br/>nas próximas etapas. ',
            MSG_PLATAFORMA_ELEITORAL_ALTERADO: "Dados da Plataforma Eleitoral alterados com sucesso!",
            MSG_DECLARACACAO_CRIACAO_CHAPA_ELEITORAL: 'Declaração para fins de criação da chapa eleitoral aonde os membros não ter sido condenado por improbidade administrativa por órgão do Poder Judiciário ou ter suas contas julgadas irregulares pelos Tribunais de Contas da União dos Estados, do Distrito Federal ou de Municípios em razão do exercício de qualquer cargo ou função pública nos últimos 5 (cinco) anos que antecederem a eleição',
            MSG_INFORMATIVO_ELEICAO_CHAPA_ELEITORAL_UF: 'Prezado(a) Arquiteto (a) e Urbanista, Você está participando como responsável pelo cadastramento da Chapa do CAU/{0} - {1}, conforme resolução ',
            MSG_INFORMATIVO_ELEICAO_CHAPA_ELEITORAL_IES: 'Prezado(a) Arquiteto (a) e Urbanista, Você está participando como responsável pelo cadastramento da Chapa de IES - {0}, conforme resolução ',
            MSG_CONFIRMACAO_RECURSO: 'Prezado(a) sr.(a), a sua interposição de recurso em 1ª Instância foi cadastrada com sucesso',
            MSG_CONFIRMACAO_RECONSIDERACAO: 'Prezado(a) sr.(a), a sua interposição de reconsideração em 1ª Instância foi cadastrada com sucesso',
            MSG_INFORMATIVO_ATUALIZACAO_CHAPA_ELEITORAL: 'Lembrando que durante o período de registro de candidatura de chapa, o senhor (a) poderá alterar a composição dos membros da sua chapa eleitoral.',
            MSG_CPF_NOME_NAO_ENCONTRADO_SICCAU: 'CPF Ou nome não encontrado na Base de Dados do SICCAU!',
            MSG_NOME_NAO_ENCONTRADO_SICCAU: 'Nome informado, não foi encontrado na Base de Dados do SICCAU!',
            MSG_CPF_CADASTRADO_OUTRA_CHAPA: 'CPF informado já aceitou participação em outra chapa!',
            MSG_AVISO_CURRICULO_DECLARACAO_CONVITE_CHAPA: "Após aceitar o convite o candidato deverá preencher a síntese das informações curriculares e a declaração eletrônica de conhecimento do regulamento eleitoral.",
            MSG_AVISO_REJEICAO_CHAPA: "Prezado(a) arquiteto(a) e ubanista, o senhor(a) tem certeza que deseja rejeitar o convite desta chapa?<br> Caso venha a se arrempender, será necessário entrar em contato com o responsável pela chapa para enviar um novo convite.",
            MSG_TAMANHO_MAXIMO_PERMITIDO_PARA_ARQUIVO: "O tamanho máximo permitido para o arquivo é de {0} MB!",
            MSG_TAMANHO_MAXIMO_10MB: 'Somente será aceito o arquivo no formato PDF, no tamanho máximo de 10MB!',
            MSG_TAMANHO_MAXIMO_CONJUNTO_10MB: 'Tamanho máximo permitido para o conjunto de documentos é de 10 MB.',
            MSG_DESEJA_REALMENTE_CANCELAR: "Deseja relmente cancelar?",
            MSG_TODOS_DADOS_PREENCHIDOS_SERAO_EXCLUIDOS_PERMANENTEMENTE: "Todos os dados preenchidos serão excluídos permanentemente do sistema eleitoral.",
            MSG_QUANTIDADE_MAXIMA_ARQUIVOS_EXCEDIDO: "Quantidade máxima de arquivos excedido.",
            MSG_ACEITAR_CONVITE_CHAPA_ELEITORAL: 'Declaração preenchida com sucesso!<br/> Parabéns! Agora você é um membro da Chapa Eleitoral CAU/{0}.',
            MSG_DADOS_INCLUIDOS_COM_SUCESSO: "Dados incluídos com sucesso!",
            MSG_DEFESA_INCLUIDA_COM_SUCESSO: "Defesa incluída com sucesso!",
            MSG_HINT_CADASTRO_MEMBROS_CHAPA_ELEITORAL: "Ao selecionar um membro para a chapa eleitoral, ele será salvo automaticamente pelo sistema, possibilitando a continuidade do cadastro em outro momento. Para salvar todas as ações realizadas nesta etapa, será necessário clicar no botão \"Avançar\" para continuidade do processo e conclusão do cadastro de chapa, após a inserção de todos membros, será necessário a conclusão do cadastro da chapa, clicando \"avançar\" nesta tela, realizando os próximos passos.",
            MSG_PERMISSAO_UPLOAD_N_ARQUIVOS: "Permissão de Upload: {0} ({1}) arquivos!",
            MSG_PERMISSAO_UPLOAD_UM_ARQUIVO: "Permissão de Upload: um (1) arquivo!",
            MSG_PERMISSAO_UPLOAD_CINCO_ARQUIVO: "Permissão de Upload: (5) arquivo(s)!",
            MSG_DESEJA_REALMENTE_VOLTAR: "Deseja realmente voltar?</br> Dados não salvos serão perdidos!",
            MSG_AVISO_NUMERO_MAXIMO_RESPONSAVEIS: "Só é permitido a inclusão de até {0} responsáveis!",
            MSG_SELECIONE_ICONE_PARA_DETALHAR_PENDENCIAS_PROFISSIONAL: "Selecione o ícone para detalhar as pendências do profissional.",
            MSG_NAO_EXISTE_ALEGACOES_IMPUGNACAO_RESULTADO: "Não há alegações de pedido de impugnação de resultado cadastrado",
            MSG_DADOS_ALTERADOS_COM_SUCESSO: "Dados alterados com sucesso!",
            MSG_CONFIRMAR_SUBTITUICAO_MEMBRO_CONVITE_ACEITE: "O CPF que o senhor quer substituir já aceitou o convite de participação da Chapa!</br> Deseja realmente substituir o profissional?",
            MSG_HINT_PLATAFORMA_ELEITORAL: "Permitido a Inclusão de até 2000 caracteres.",
            MSG_HINT_IMPUGNACAO: "Insira o nome do profissional e o sistema vai exibir até 5 resultados ou insira um CPF para ser mais específico",
            MSG_HINT_IMPUGNACAO_NOME_REGISTRO: "Insira o nome do profissional e o sistema vai exibir até 5 resultados ou insira um Registro para ser mais específico",
            MSG_HINT_IMPUGANCAO_RESULTADO_NARRACAO: "Os pedidos de impugnação do resultado das eleições deverão ser fundamentados exclusivamente nos critérios de distribuição proporcional das vagas",
            MSG_HINT_IMPUGNACAO_RESULTADO_ARQUIVO: "Formato permitido: PDF. Tamanho máximo permitido: 15 MB. Permite anexar 1 arquivo",
            MSG_PENDENCIA_ANUNIADADE_PROFISSIONAL: 'Pendências de Anuidade com o CAU',
            MSG_NAO_HOUVE_INTERPOSICAO: 'Não houve Interposição de {0}!',
            MGS_CONFIRMACAO_RECURSO_CHAPA: 'Caro(a) sr. (a), informe o(s) membro(s) para solicitação de recurso!',
            MGS_CONFIRMACAO_RECONSIDERACAO_CHAPA: 'Caro(a) sr. (a), informe o(s) membro(s) para solicitação de reconsideração!',
            MGS_CONFIRMACAO_RECURSO_JULGAMENTO_FINAL: 'Prezado(a) sr.(a), sua interposição de {0} do julgamento final foi cadastrada com sucesso!',
            MSG_NAO_HOUVE_INTERPOSICAO_RECURSO: 'Não houve interposição de recurso para este pedido de impugnação!',
            MSG_NAO_HOUVE_INTERPOSICAO_RECONSIDERACAO: 'Não houve interposição de reconsideração para este pedido de impugnação!',
            MSG_NAO_HOUVE_INTERPOSICAO_RECURSO_SUBSTITUICAO: 'Não houve interposição de recurso para este pedido de substituição!',
            MSG_NAO_HOUVE_INTERPOSICAO_RECONSIDERACAO_SUBSTITUICAO: 'Não houve interposição de reconsideração para este pedido de substituição!',
            MSG_HINT_MODAL_SUBSTITUICAO_IMPUGNACAO: 'A conclusão do pedido de substituição ficará sujeita à aceitação do convite pelo Arquiteto (a) e Urbanista convidado',

            MSG_PENDENCIA_REGISTRO_PROFISSIONAL: 'Profissional sem registro ativo',
            MSG_CONFIRMACAO_SUBSTITUICAO_MEMBRO_CHAPA: 'Prezado (a) Arquiteto(a) e Urbanista seu pedido de substituição foi cadastrado com êxito e foi gerado o seguinte número de acompanhamento ',
            MSG_PENDENCIA_ETICO_DISCIPLINAR_PROFISSIONAL: 'Profissional possui infração ético-disciplinar aplicada, pendente',
            MSG_PENDENCIA_INFRACAO_PROFISSIONAL: 'Profissional em cumprimento de decisão por infração no exercício da profissão',
            MSG_NAO_HA_DENUNCIAS: 'Não há denúncias cadastradas para a eleição vigente.',
            MSG_NAO_HA_DENUNCIAS_RECEBIDAS: 'Não há denúncias recebidas na eleição vigente.',
            MSG_PREZADO_ARQUITETO_RESPONSAVEL_CHAPA: 'Prezado(a) arquiteto (a) e urbanista, responsável pela chapa cadastrada, o cadastramento do pedido de substituição de membros de chapa será realizado através da pesquisa de CPF dos membros de sua chapa. Para isso o senhor deverá realizar primeiro a busca desse membro para posteriormente selecionar o CPF do membro e suplente à ser substituído. Após cadastramento, o acompanhamento poderá ser feito através do menu "acompanhar substituição".',
            MSG_PREENCHIMENTO_OBRIGATORIO_CHAPA_SUBSTITUICAO: 'Caro(a) sr(a), o preenchimento dos dois cargos (Titular e Suplente) são de preenchimento obrigatório! Caso o(a) senhor(a), queira substituir apenas 1 dos membros, por gentileza, repetir/informar novamente o CPF do membro que não deve ser substituído.',
            MSG_SEM_PEDIDO_SUBSTITUICAO_MEMBRO_RESPONSAVEL: 'Caro(a) sr.(a), não existe pedido de substituição cadastrado para a eleição que o senhor é um conselheiro CEN/BR!',
            MSG_EXCLUSAO_COM_SUCESSO: 'Exclusão realizada com sucesso!',
            MSG_ARQUIVO_INVALIDO: 'Arquivo inválido',
            MSG_PEDIDOS_IMPUGNACAO: 'Os pedidos de impugnação de registro de candidatura de chapa deverão ser fundamentados exclusivamente nas condições de elegibilidade e nas causas de inelegibilidade de candidato, previstas na resolução, conforme o caso, e deverão ser instruídas com documentos que comprovem a veracidade dos fatos alegados.',
            MSG_CONFIRMACAO_PEDIDO_IMPUGNCAO: 'Prezado(a) Arquiteto(a) e Urbanista, seu pedido de impugnação foi cadastrado e foi gerado o seguinte número de acompanhamento ',
            MSG_INTERPOSICAO_RECURSO_CADASTRADO_COM_SUCESSO: "Prezado(a) sr.(a), a sua interposição de recurso em 1ª Instância foi cadastrada com sucesso.",
            MSG_INTERPOSICAO_RECONSIDERACAO_CADASTRADO_COM_SUCESSO: "Prezado(a) sr.(a), a sua interposição de reconsideração em 1ª Instância foi cadastrada com sucesso.",
            MSG_OBRIGATORIEDADE_ITEM_DECLARACAO: 'Selecione no mínimo um item de declarações.',
            MSG_OBRIGATORIEDADE_DOCUMENTO_COMPROBATORIO: 'Inclua no mínimo um documento comprobatório.',
            MSG_CONTRARRAZAO_CADASTRADA_COM_SUCESSO: "Prezado(a) sr. (a), a sua contrarrazão foi cadastrada com sucesso!",
            MSG_CONFIRMACAO_PEDIDO_SUBSTITUICAO_IMPUGNACAO: 'Prezado (a) Arquiteto(a) e Urbanista, seu pedido de substituição foi cadastrado com êxito para o pedido de impugnação nº ',
            MSG_INSIRA_NUMERO_DE_REGISTRO_OU_NOME_CANDIDATO: 'Insira o Número de Registro ou Nome do candidato',
            MGS_N_HOUVE_CONTRARRAZAO_CADASTRADA: 'Não Houve Contrarrazão Cadastrada!',


            MSG_INSERIR_NOVO_RELATOR_COM_EXITO: 'Prezado (a), o relator foi substituído com sucesso para a denúncia nº {0}.',
            MSG_INSERIR_RECURSO_RECONSIDERACAO: 'Prezado (a), a solicitação cadastrada com sucesso para a denúnica nº {0}',
            MSG_ALEGACOES_FINAIS_COM_EXITO: 'Prezado(a), as alegações finais foram inseridas com êxito para a denúncia nº {0}.',
            MSG_HINT_UPLOAD_RELATOR: 'São permitidos até cinco (5) arquivos de 25 MB nos formatos: pdf, zip, rar, doc, docx, xls, xlsx, mp4, avi, wmv, mp3, wav, jpg, jpeg pi png.',
            MSG_RELATOR_SUCESSO: "Prezado (a), o relator foi indicado com sucesso para a denúncia nº {0}",
            MSG_PRAVAS_DENUNCIA_COM_EXITO: 'Prezado(a), provas inseridas com êxito para a denúncia nº {0}.',
            MSG_CONFIRMACAO_DATAHORA_AUDIENCIA_DIFERENTE_DO_AGENDADO: "Prezado(a), a data/hora da audiência é diferente da data/hora agendada previamente. Deseja continuar?",
            MSG_AUDIENCIA_INSTRUCAO_CADASTRADA_COM_SUCESSO: "Prezado(a), audiência de instrução registrada com êxito para a denúncia nº {0}.",
            MSG_CONTRARRAZAO_CADASTRADA_COM_EXITO: 'Prezado(a), contrarrazão cadastrada com sucesso para a denúncia nº {0}.',
            MSG_PARECER_FINAL_CADASTRADA_COM_EXITO: 'Prezado(a) Arquiteto(a) e Urbanista, parecer final realizado com êxito para a denúncia nº {0}.',
            MSG_PARECER_FINAL_DESTINATARIO_ALEGACAO_NAO_RESPONDIDO: 'Prezado(a) uma das partes envolvidas ainda não respondeu a alegação final.',
            MSG_NAO_HOUVE_CADASTRO_ALEGACAO: 'Não houve cadastro de alegações finais dentro do prazo de envio.',
            MGS_IMPEDITIVA_ATIVIDADE_SECUNDARIA_CADASTRO_IMPUGNACAO_RESULTADO: 'Caro(a) sr. (a), a atividade selecionada está fora do prazo de vigência',

            MSG_NAO_HOUVE_CADASTRO_CONTRARRAZAO_DENUNCIADO: 'Não houve cadastro de contrarrazão para o recurso do denunciante.',
            MSG_NAO_HOUVE_CADASTRO_CONTRARRAZAO_DENUNCIANTE: 'Não houve cadastro de contrarrazão para o recurso do denunciado.',
            MSG_NAO_HOUVE_APRESENTACAO_RECURSO_RECONSIDERACAO: 'Não houve apresentação de recurso ou reconsideração pelo denunciante.',
            MSG_NAO_HOUVE_APRESENTACAO_RECURSO_RECONSIDERACAO_DENUNCIADO: 'Não houve apresentação de recurso ou reconsideração pelo denunciado',


            MSG_CONFIRMAR_EXCLUIR_MEMBRO_PENDENCIA: 'Deseja realmente excluir membro com pendência?',

            LABEL_CARD_SUBSTITUICAO_MEMBRO: 'Selecione candidato(s) para solicitação de substituição',
            LABEL_SUBSTITUIDO: 'Substituído',
            LABEL_SUBSTITUTO: 'Substituto',
            LABEL_BTN_INCLUIR: 'Incluir',
            LABEL_BTN_LOAD: 'Aguarde...',
            MSG_TITULO_CANCELAR: 'Deseja realmente cancelar?',
            MSG_CANCELAR_ALTERACAO: 'Deseja realmente cancelar? Todos os dados preenchidos será(ão) perdido(s).',
            MSG_CANCELAR_SUBSTITUICAO: 'Todos os dados preenchidos será(ão) perdido(s).',
            MSG_PROFISSIONAL_JA_INCLUIDO: 'Profissional {0} informado já foi incluído nessa Chapa',
            MSG_NENHUM_CANDIDATO_INFORMADO: 'Caro(a) sr. (a), para realização de uma substituição, você deve informar o substituído e o substituto!',
            MSG_CONFIRMACAO_SUBSTITUICAO_MEMBRO_JULGAMENTO: 'Prezado(a) sr(a), seu pedido de substituição foi cadastrado com sucesso!',
            MSG_DESEJA_REALMENTE_EXCLUIR_MEMBRO_CHAPA: "Deseja realmente excluir membro da chapa?",
            MSG_CONFIRMACAO_IMPUGNACAO_RESULTADO: 'Pedido de Impugnacao de Resultado foi cadastrado com sucesso!',
            MSG_ALEGACAO_SALVA_COM_EXITO: 'Prezado(a) Arquiteto(a) e Urbanista sua alegação foi cadastrada com êxito para a impugnação de resultado nº {0}.',
            MSG_CONFIRMACAO_IMPUGNACAO_RESULTADO_NUMERO_PROTOCOLO: 'Prezado(a) Arquiteto(a) e Urbanista seu pedido de impugnação de resultado foi cadastrado com êxito e foi gerado a número {0} de acompanhamento.',
            MSG_VALIDACAO_IMPUGNACAO_RESULTADO_TIPO_1: 'Prezado (a) Arquiteto (a) e Urbanista, já existe um pedido de impugnação de resultado cadastrado por você para UF selecionada, gostaria mesmo assim de incluir um novo pedido de impugnação de resultado?',
            MSG_VALIDACAO_IMPUGNACAO_RESULTADO_TIPO_2: 'Prezado (a) Arquiteto (a) e Urbanista, já existe um pedido de impugnação de resultado cadastrado por um membro da sua chapa, gostaria mesmo assim de incluir um novo pedido de impugnação de resultado?',
            MSG_VALIDACAO_IMPUGNACAO_RESULTADO_TIPO_3: 'Prezado (a) Arquiteto (a) e Urbanista, já existe um pedido de impugnação de resultado cadastrado para UF selecionada, gostaria mesmo assim de incluir um novo pedido de impugnação de resultado? ',
            MSG_CADASTRO_RECURSO_ADMISSIBILIDADE_SUCESSO: "Prezado (a), recurso de admissibilidade foi cadastrado com êxito para a denúncia nº {0}.",
            MSG_NAO_HOUVE_APRESENTACAO_RECURSO_ADMISSIBILIDADE: 'Não houve apresentação  de recurso de admissibilidade para essa denúncia. ',
            MSG_CONFIRMAR_ALTERACAO: "Deseja realmente alterar as informações?",
            MSG_ALTERACAO_REALIZADA_COM_SUCESSO: "Alteração realizada com sucesso!",
            MSG_FORA_PERIODO_VIGENCIA_ALTERAR_PLATAFORMA: ' <p> Prezado(a) Arquiteto(a) e Urbanista o período de vigência  para alteração  econtra-se  encerrado. Será permitido apenas a alteração do campo ( outros ) para redes sociais.</p> <p>Deseja prosseguir com a alteração?</p>',
            MSG_JA_EXISTE_ALEGACAO_CADASTRADO: "Prezado (a) já existe alegação cadastrada por um responsável da sua Chapa/IES para esse pedido de impugnação.<br> Deseja cadastrar uma nova alegação? ",
            MSG_HINT_DOCUMENTO_JUGAMENTO_ALEGACAO_IMPUGNACAO_RESULTADO: "Formatos permitidos: PDF \n Tamanho máximo permitido: 15 MB",
            MSG_RECURSO_JULGAMENTO_IMPUGNACAO_RESULTADO_SALVO_COM_SUCESSO: 'Prezado(a) Arquiteto(a) e Urbanista {0} para o julgamento em 1ª instancia foi cadastrado com êxito.',
            MSG_SUCESSO_SALVAR_CONTRARRAZAO_INPUGNACAO_RESULTADO: "Prezado(a) Arquiteto(a) e Urbanista a Contrarrazão foi cadastrada com êxito.",
            MSG_CONFIRMAR_CANCELAR: "Deseja realmente cancelar?<br> Todos os dados preenchidos será(ão) perdido(s).",
            MSG_LABEL_BTN_CADASTRAR_CONTRARRAZAO_IMPUGNACAO_RESULTADO_IMPUGNADO: 'Prezado (a) já existe contrarrazão cadastrada para esse {0}',
            MSG_CHAPA_NAO_ATENDEU_MINIMO_CRITERIOS_REPRESENTATIVIDADE: 'A chapa não atendeu o mínimo de critérios de representatividade.',
            MSG_CHAPA_NAO_ATENDEU_MINIMO_COTISTAS_REPRESENTATIVIDADE: 'A chapa não atendeu a quantidade mínima de cotistas da representatividade.',
            MSG_DECLARACAO_VERIDICA: 'As informações por mim cadastradas são verídicas, sendo a minha responsabilidade o registro das informações.',
            
            //Validation
            required: 'Campo de preenchimento obrigatório',
            maxlength: 'Limite máximo de caracteres atingido',
            TimeValidator: "Prezado(a), informe uma data e/ou hora válida.",
            MaxDateValidate: "Prezado(a), a data e hora de registro da audiência não podem ser futuras."
        };
    }

    /**
     * Returns the 'description' according to the 'key' entered.
     *
     * @param key
     */
    getDescription(key: string): string {
        return this.resource[key];
    }

    /**
     * Returns the 'description' according to the 'key' entered.
     *
     * @param key
     */
    getMessage(key: string): string {
        return this.resource[key];
    }
}
