import { ValidationResource } from '@cau/component';
import { MESSAGE_RESOURCE_LAYOUT } from '@cau/layout';
import { MessageResource, MESSAGE_RESOURCE_CONFIRM } from '@cau/message';

/**
 * Implementação responsável por prover as 'descrições' e 'mensagens' utilizadas na aplicação em um único local.
 *
 * @author Squadra Tecnologia
 */
export class AppMessage implements MessageResource, ValidationResource {

  private resource: Object;

  /**
   * Construtor da classe.
   */
  constructor() {
    this.resource = {
      ...MESSAGE_RESOURCE_LAYOUT,
      ...MESSAGE_RESOURCE_CONFIRM,
      'LABEL_LAYOUT_NOME_SISTEMA': 'Processo Eleitoral',

      // Label
      LABEL_OK: 'OK',
      LABEL_DE: 'De',
      LABEL_OU: 'Ou',
      LABEL_UF: 'UF',
      LABEL_ABA: 'Aba',
      LABEL_NAO: 'Não',
      LABEL_ATE: 'Até',
      LABEL_IES: 'IES',
      LABEL_SIM: 'Sim',
      LABEL_ANO: 'Ano',
      LABEL_HIFEN: '-',
      LABEL_DATA: 'Data',
      LABEL_NOME: 'Nome',
      LABEL_TIPO: 'Tipo',
      LABEL_ACAO: 'Ação',
      LABEL_ANOS: 'Anos',
      LABEL_MENU: 'Menu',
      LABEL_ENTRE: 'Entre',
      LABEL_PRAZO: 'Prazo',
      LABEL_CAU_UF: 'CAU/UF',
      LABEL_BUSCAR: 'Buscar',
      LABEL_LIMPAR: 'Limpar',
      LABEL_FECHAR: 'Fechar',
      LABEL_ETAPAS: 'Etapas',
      LABEL_SALVAR: 'Salvar',
      LABEL_STATUS: 'Status',
      LABEL_STATUS_ELEICAO: 'Status da Eleição',
      LABEL_ATIVAR: 'Ativar',
      LABEL_OUTROS: 'Outros',
      LABEL_NENHUM: 'Nenhum',
      LABEL_DEFESA: 'Defesa',
      LABEL_PARECER: 'Parecer',
      LABEL_DEFIRIR: 'Deferir',
      LABEL_FILTRAR: 'Filtrar',
      LABEL_PERIODO: 'Período',
      LABEL_FILTROS: 'Filtros',
      LABEL_INCLUIR: 'Incluir',
      LABEL_MOSTRAR: "Mostrar",
      LABEL_ELEICAO: 'Eleição',
      LABEL_AVANCAR: 'Avançar',
      LABEL_EXCLUIR: 'Excluir',
      LABEL_ALTERAR: 'Alterar',
      LABEL_ARQUIVO: 'Arquivo',
      LABEL_TITULAR: 'Titular',
      LABEL_EXTRATO: 'Extrato',
      LABEL_DEFERIR: 'Deferir',
      LABEL_RECURSO: "Recurso",
      LABEL_ENVIO_AGENDAMENTO: 'Envio/Agenda',
      LABEL_DESTINATARIO: 'Destinatário',
      LABEL_DATA_SOLICITACAO: 'Data Solicitação',
      LABEL_SIGLA_HORAS: 'hrs',
      LABEL_QUANTIDADE: 'Quant',
      LABEL_N_CHAPA: "Nº da Chapa",
      LABEL_NAO_APLICADO: 'N/A',
      LABEL_TABS_PRAZO: 'Prazo',
      LABEL_DATA_FIM: 'Data Fim',
      LABEL_CONCLUIR: 'Concluir',
      LABEL_SUPLENTE: 'Suplente',
      LABEL_REPLICAR: 'Replicar',
      LABEL_REGISTRO: "Registro",
      LABEL_IMPORTAR: 'Importar',
      LABEL_CADASTRO: 'Cadastro',
      LABEL_DEFERIDO: 'Deferido',
      LABEL_DIA_UTIL: 'Dia Útil',
      LABEL_CANCELAR: 'Cancelar',
      LABEL_CADASTRAR: 'Cadastrar',
      LABEL_ABA_PRAZO: 'Aba Prazo',
      LABEL_INDEFIRIR: 'Indeferir',
      LABEL_VALIDACAO: 'Validação',
      LABEL_CURRICULO: 'Currículo',
      LABEL_PUBLICADO: 'Publicado',
      LABEL_DESCRICAO: 'Descrição',
      LABEL_MOSTRANDO: 'Mostrando',
      LABEL_ATIVIDADE: 'Atividade',
      LABEL_RESOLUCAO: 'Resolução',
      LABEL_DATA_HORA: 'Data/Hora',
      LABEL_PESQUISAR: 'Pesquisar',
      LABEL_HISTORICO: 'Histórico',
      LABEL_TABS_PERIODO: 'Período',
      LABEL_SELECIONAR: 'Selecione',
      LABEL_PAINEL_CHAPAS: 'Chapas',
      LABEL_PROCEDENTE: 'Procedente',
      LABEL_INDEFERIDO: 'Indeferido',
      LABEL_VISUALIZAR: 'Visualizar',
      LABEL_DO_RECURSO: "do Recurso",
      LABEL_IMPUGNANTE: "Impugnante",
      LABEL_PAINEL_MEMBROS: 'Membros',
      LABEL_SELECT_ELEICAO: 'Eleição',
      LABEL_DATA_INICIO: 'Data Início',
      LABEL_RESPONSAVEL: 'Responsável',
      LABEL_ABA_PERIODO: 'Aba Período',
      LABEL_TABS_HISTORICO: 'Histórico',
      LABEL_IMPROCEDENTE: 'Improcedente',
      LABEL_EM_ANDAMENTO: 'Em andamento',
      LABEL_QUANTIDADE_DIAS: 'Qtde Dias',
      LABEL_GERAR_COOKIE: 'Gerar Cookie',
      LABEL_PARAMETRIZAR: 'Parametrizar',
      LABEL_CONTRARRAZAO: 'Contrarrazão',
      LABEL_MANDATO: 'Período de Mandato',
      LABEL_BOAS_VINDAS: 'Bem Vindo(a), ',
      LABEL_ANO_ELEICAO: 'Ano da Eleição',
      LABEL_DURACAO_DIAS: 'Duração (dias)',
      LABEL_TIPO_CADASTRO: 'Tipo Cadastro',
      LABEL_JUSTIFICATIVA: 'Justificativa',
      LABEL_PAINEL_VISUAL: 'Painel Visual',
      LABEL_VIGENCIA: 'Período de Vigência',
      LABEL_CHAVE_ACESSO: 'Chave de acesso',
      LABEL_ACESSO_NEGADO: 'Acesso negado.',
      LABEL_ATIVAR_ELEICAO: 'Ativar Eleição',
      LABEL_JULGAR_RECURSO: 'Julgar Recurso',
      LABEL_RECONSIDERACAO: "Reconsideração",
      LABEL_PARAMETRIZACAO: 'Parametrização',
      LABEL_TIPO_PROCESSO: 'Tipo de Processo',
      LABEL_PAINEL_IMPUGNACOES: 'Impugnações',
      LABEL_GERAR_DOCUMENTO: 'Gerar Documento',
      LABEL_JULGAR_DEFERIDO: 'Julgar Deferido',
      LABEL_BAR_PROGRESS: 'Barra de Progresso',
      LABEL_PAINEL_EDITAL: 'Edital Convocações',
      LABEL_TABLE_FILTRO_VAZIO: 'Selecione o(s) filtro(s) para a nova pesquisa',
      LABEL_RESULTADO_PESQUISA: 'Resultado da Pesquisa',
      LABEL_IDADE_VOTO_OBRIGATORIO: 'Idade do Voto Obrigatório',
      LABEL_ATIVIDADE_PRINCIPAL: 'Atividade Principal',
      LABEL_INCLUIR_SUB_ATIVIDADE: 'Incluir SubAtividade',
      LABEL_INCLUIR_SUB_ATIVIDADE_PARALELA: 'Incluir SubAtividade Paralela',
      LABEL_SELECIONAR_EMAIL: 'Selecionar E-mail',
      LABEL_PAINEL_CONTROLE: 'Painel de Controle',
      LABEL_JULGAR_INDEFERIDO: 'Julgar Indeferido',
      LABEL_OBEDECER_VIGENCIA: 'Obedecer Vigência',
      LABEL_INCLUIR_ATIVIDADE: 'Incluir Atividade',
      LABEL_DA_RECONSIDERACAO: "da Reconsideração",
      LABEL_PESQUISAR_ELEICAO: "Pesquisar Eleição",
      LABEL_ATOS_PREPARATORIOS: 'Atos Preparatórios',
      LABEL_SELECIONAR_ARQUIVO: 'Selecionar Arquivo',
      LABEL_CHAPAS_CADASTRADAS: 'Chapas Cadastradas',
      LAVEL_SELECIONE_CANDIDATO: 'Selecione candidato',
      LABEL_TABS_JULGAMENTO: 'Julgamento 1ª Instância',
      LABEL_MEMBROS_CONFIRMADOS: "Membros Confirmados",
      LABEL_PARAMETRIZACAO_N_DE_MEMBROS: 'N de Membros',
      LABEL_TABS_JULGAMENTO_2: 'Julgamento 2ª Instância',
      LABEL_TIPO_DE_PARTICIPACAO: "Tipo de Participação",
      LABEL_RESPONSAVEL_DA_CHAPA: "Responsável da Chapa",
      LABEL_ATIVIDADE_SECUNDARIA: 'Atividade Secundária',
      LABEL_DATA_BARA_HORA_CADASTRO: 'Data/Hora Cadastro',
      LABEL_RECURSO_DO_JULGAMENTO: 'Recurso do Julgamento',
      LABEL_SEM_INCLUSAO_MEMBRO: 'Sem inclusão de membro',
      LABEL_SEM_MEMBRO_INCLUSAO: 'Sem inclusão de membro',
      LABEL_DATA_HORA_CADASTRO: 'Data e Hora do Cadastro',
      LABEL_JULGAR_RECONSIDERACAO: 'Julgar Reconsideração',
      LABEL_RESPONSAVEL_PELA_CHAPA: "Responsável pela Chapa",
      LABEL_RESPONSAVEL_IMPUGNANTE: "Responsável Impugnante",
      LABEL_TABS_JULGAMENTO_FINAL: 'Julgamento 1ª Instância',
      LABEL_DATA_HORA_DO_CADASTRO: "Data e hora do Cadastro",
      LABEL_RESPONSAVEL_CADASTRO: 'Responsável pelo Cadastro',
      LABEL_INFORMACOES_IMPUGNADO: "Informações do Impugnado",
      LABEL_QUANTIDADE_CALENDARIOS: 'Total de Calendários:  ',
      LABEL_JULGAMENTO_2_INSTANCIA: "Julgamento 2º Instância",
      LABEL_JULGAMENTO_1_INSTANCIA: "Julgamento 1º Instância",
      LABEL_INFORMACOES_IMPUGNANTE: "Informações do Impugnante",
      LABEL_CONTRARRAZAO_RECURSO_RECONSIDERACAO: 'Contrarrazão {0}',
      LABEL_N_IMPUGNACAO_DE_RESULTADO: 'Nº Impugnação de Resultado',
      LABEL_PARAMETRIZACAO_PROCESSO_ELEITORAL: 'Processo Eleitoral',
      LABEL_RECURSO_RECONSIDERACAO_DO_IMPUGNANTE: '{0} do Impugnante',
      LABEL_ATOS_PREPARATORIOS_CADASTRAR_MEMBROS: 'Cadastrar Membros',
      LABEL_RECONSIDERACAO_DO_JULGAMENTO: 'Reconsideração do Julgamento',
      LABEL_PARAMETRIZACAO_CALENDARIO_ELEITORAL: 'Calendário Eleitoral',
      LABEL_QUANTIDADE_CHAPAS_QUEBRA_LINHA: '{0}Quantidade de{1}Chapas{2}',
      LABEL_ATOS_PREPARATORIOS_EDITAL_DE_CONVOCACAO: 'Edital de Convocação',
      LABEL_QTD_IMPUGNACAO_SUBSTITUICAO: 'Quantidade de Pedidos de Impugnação',
      LABEL_REGISTRO_PEDIDO_SUBSTITUICAO: 'Registro do Pedido de Substituição',
      LABEL_RECURSO_RECONSIDERACAO_DO_RESPONSAVEL: '{0} do Responsável da Chapa',
      LABEL_PARAMETRIZACAO_CALENDARIO_IMPUGNACAO_RESULTADO: 'Impugnação de Resultado',
      LABEL_PARECER_PEDIDO_IMPUGNACAO_DOCUMENTO: "Parecer do Pedido de Impugnação/Documento",
      LABEL_QUANTIDADE_CHAPAS_COM_PENDENCIA_QUEBRA_LINHA: '{0}Quantidade de{1}Chapas Com Pendência{2}',
      LABEL_QUANTIDADE_CHAPAS_SEM_PENDENCIA_QUEBRA_LINHA: '{0}Quantidade de{1}Chapas Sem Pendência{2}',
      LABEL_SELEC_EMAIL_CONFIRM_CHAPA_ELEITORAL: 'Selecione E-Mail Para Confirmação da Chapa Eleitoral',
      LABEL_PARECER_RECURSO_PEDIDO_SUBISTUICAO: "Parecer da Interposição do Recurso do Pedido de Substituição",
      LABEL_STATUS_ATIVIDADE: 'Status Atividade',
      LABEL_DOCUMENTO: 'Documento',
      LABEL_MAJORITARIO: 'Majoritário',
      LABEL_CONSELHEIRO: 'Conselheiro',
      LABEL_TIPO_CONSELHEIRO: 'Tipo de conselheiro',
      LABEL_NAO_CONSELHEIRO: 'Não Conselheiro',
      LABEL_DUAS_OPCOES: '2 Opções',
      LABEL_VARIAS_OPCOES: 'Várias Oções',
      LABEL_QUANTIDADE_MINIMA_MEMBROS: 'Qtd Mínima Membros',
      LABEL_QUANTIDADE_MAXIMA_MEMBROS: 'Qtd Máxima Membros',
      LABEL_QUANTIDADE_EMAIL: 'Qtd E-mail',
      LABEL_SELECIONE_EMAIL: 'Selecione E-mail',
      LABEL_REGRA_ENVIO: 'Regra de Envio',
      LABEL_CORPO_EMAIL: 'Corpo do E-mail',
      LABEL_CONFIGURAR_ELEICAO: 'Configurar Eleição',
      LABEL_COMISSAO_ELEITORAL: 'Comissão Eleitoral',
      LABEL_DOCUMENTO_INCLUIDO: 'Documento Incluído',
      LABEL_DOCUMENTO_CONCLUIDO: 'Documento Concluído',
      LABEL_CONCLUIDA: "Concluída",
      LABEL_INFORMACOES_INICIAIS: 'Informações Iniciais',
      LABEL_INFORMACOES_INICIAIS_INCLUIDAS: 'Informações Iniciais Incluídas',
      LABEL_EMAIL_001: '01',
      LABEL_COORDENADOR_E_COORDENADOR_ADJUNTO: 'Coordenador e Coordenador Adjunto',
      LABEL_CADASTRO_INFORMACOES_QUANTIDADE_MEMBROS_COMISSAO_ANUAL: 'Cadastro das Informações da Quantidade de Membros da Comissão Eleitoral',
      LABEL_DOCUMENTO_QUANTIDADE_MEMBROS_COMISSAO_ANUAL: 'Documento da Quantidade de Membros da Comissão Eleitoral',
      LABEL_PARAMETRIZAR_CABECALHO: 'Parametrizar Cabeçalho',
      LABEL_PARAMETRIZAR_TEXTO_INICIAL: 'Parametrizar Texto Inicial',
      LABEL_QUANTIDADE_MEMBROS: 'Quantidade de Membros',
      LABEL_PARAMETRIZAR_TEXTO_FINAL: 'Parametrizar Texto Final',
      LABEL_PARAMETRIZAR_RODAPE: 'Parametrizar Rodapé',
      LABEL_ATOS_PREPARATORIOS_MEMBROS_COMISSAO: 'Membros da Comissão',
      LABEL_CADASTRO_INFORMACOES_MEMBROS_COMISSAO: 'Definir Membros da Comissão',
      LABEL_NUMERO_MEMBROS: 'Número de Membros',
      LABEL_NUMERO_CONSELHEIRO: 'Número de Conselheiro',
      LABEL_CADASTRAR_MEMBROS_COMISSAO: 'Cadastrar Membros da Comissão',
      LABEL_COORDENADORES: 'Coordenadores',
      LABEL_COORDENADOR: 'Coordenador',
      LABEL_SUBSTITUTO: 'Substituto',
      LABEL_COORDENADOR_COMISSAO: 'Coordenador da Comissão',
      LABEL_EMAIL: 'E-mail',
      LABEL_TIPO_PARTICIPACAO: 'Tipo Participação',
      LABEL_MEMBROS: 'Membros',
      LABEL_CPF_PROFISSIONAL: 'CPF do Profissional',
      LABEL_TABS_INCLUIR_MEMBROS: 'Incluir Membros',
      LABEL_TABS_ALTERAR_MEMBROS: 'Alterar Membros',
      LABEL_HISTORICO_ALTERACOES: 'Histórico de Alterações',
      LABEL_HISTORICO_RETIFICACAO: 'Histórico de Retificação',
      LABEL_INCLUIR_MEMBROS_COMISSAO: 'Incluir Membros da Comissão',
      LABEL_VISUALIZAR_MEMBROS_COMISSAO: 'Visualizar Membros da Comissão',
      LABEL_VISUALIZAR_MEMBROS_COMISSOES: 'Visualizar Membros das Comissões',
      LABEL_VISUALIZAR_CORPO_EMAIL: 'Visualizar Corpo do E-mail',
      LABEL_VISUALIZAR_CABECALHO_RODAPE_EMAIL: "Visualizar Cabeçalho e Rodapé do E-mail",
      LABEL_AGUARDANDO_PARAMETRIZACAO: "Aguardando Parametrização",
      LABEL_AGUARDANDO_DOCUMENTO: "Aguardando Documento",
      LABEL_PARAMETRIZACAO_CONCLUIDA: "Parametrização Concluída",
      LABEL_DEFINIR_EMAIL: "Definir E-mail",
      LABEL_DEFINIR_EMAIL_ENVIADO_PARA_MEMBROS_COMISSAO: "Definir E-Mail enviado para os Membros da Comissao",
      LABEL_PUBLICAR_COMISSAO_ELEITORAL: "Publicar Comissão Eleitoral",
      LABEL_DOCUMENTO_QUANTIDADE_MEMBROS_COMISSAO_ELEITORAL: "Documento da Quantidade de Membros da Comissão Eleitoral",
      LABEL_PUBLICAR_QUANTIDADE_MEMBROS_COMISSAO_ELEITORAL: "Publicar Quantidade de Membros da Comissão Eleitoral",
      LABEL_PUBLICAR_QUANTIDADE_MEMBROS: 'Publicar Qtd Membros',
      LABEL_GERAR_PDF: "Gerar PDF",
      LABEL_GERAR_DOC: "Gerar DOC",
      LABEL_PUBLICAR: "Publicar",
      LABEL_DATAHORA_PUBLICACAO: "Data/Hora Publicação",
      LABEL_DATAHORA_CADASTRADO: "Data/Hora Cadastrado",
      LABEL_USUARIO: "Usuário",
      LABEL_ARQUIVO_PUBLICADO: "Arquivo(s) Publicado(s)",
      LABEL_TODAS: 'Todas',
      LABEL_TODOS: 'Todos',
      LABEL_CPF: 'CPF',
      LABEL_JUSTIFICATIVA_MEMBROS_COMISSAO: 'Sr(a) usuário(a), para inclusão das informações. O campo justificativa é de preenchimento obrigatório',
      LABEL_EM_PRENCHIMENTO: 'Em Prenchimento',
      LABEL_PARAMETRIZAR_CABECALHO_RODAPE_EMAIL: "Parametrizar Cabeçalho e Rodapé do E-Mail",
      LABEL_TITULO: "Título",
      LABEL_PARAMETRIZAR_CABECALHO_EMAIL: "Parametrizar Cabeçalho do E-Mail",
      LABEL_PARAMETRIZAR_RODAPE_EMAIL: "Parametrizar Rodapé do E-Mail",
      LABEL_INSERIR_FIGURA: "Inserir Figura",
      LABEL_PROCURAR: "Procurar",
      LABEL_N: "Nº",
      LABEL_ATIVO: "Ativo",
      LABEL_CABECALHO_RODAPE: "Cabeçalho e Rodapé",
      LABEL_PARAMETRIZAR_CORPO_EMAIL: "Parametrizar Corpo do E-Mail",
      LABEL_ASSUNTO: "Assunto",
      LABEL_SELECIONE_TODOS: "Selecione Todos",
      LABEL_SELECIONE_ABAS_DESEJA_GERAR_DOCUMENTO: 'Selecione as abas que deseja gerar documento',
      LABEL_REMOVER_TODOS: "Remove Todos",
      LABEL_ARGUARDE: "Aguarde...",
      LABEL_ATIVAR_EMAIL: "Ativar E-mail.",
      LABEL_ACOMPANHAR_CHAPA: "Acompanhar Chapa",
      LABEL_VISAO_GERAL: "Visão Geral",
      LABEL_CHAPAS_CADASTRADAS_POR_ESTADO: "Chapas Cadastradas por Estado",
      LABEL_ESTADO: "Estado",
      LABEL_QUANTIDADE_CHAPAS: "Quantidade de Chapas",
      LABEL_QUANTIDADE_CHAPAS_COM_PENDENCIA: "Quantidade de Chapas com Pendência",
      LABEL_QUANTIDADE_CHAPAS_CONCLUIDA: "Quantidade de Chapas Concluída",
      LABEL_TOTAL_CHAPAS_CADASTRADAS: "Total Chapas Cadastradas",
      LABEL_VISUALIZAR_CHAPAS_POR_UF: "Visualizar Chapas Por UF",
      LABEL_VISUALIZAR_CHAPAS_POR_IES: "Visualizar Chapa IES",
      LABEL_VISUALIZAR_CHAPAS: "Visualizar Chapas",
      LABEL_STATUS_CHAPA: "Status da Chapa",
      LABEL_STATUS_CHAPA_QUEBRA_LINHA: "{0}Status da {1}Chapa{2}",
      LABEL_UF_CHAPA: "UF da Chapa",
      LABEL_COM_PENDENCIA: "Com Pendência",
      LABEL_ACESSAR_CHAPA: "Acessar Chapa",
      LABEL_ALTERAR_STATUS_CHAPA: "Alterar Status da Chapa",
      LABEL_EXCLUIR_CHAPA: "Excluir Chapa",
      LABEL_ACOMPANHAR_CHAPAS: "Acompanhar Chapas",
      LABEL_CHAPAS: "Chapas",
      LABEL_CONFIRMAR: "Confirmar",
      LABEL_MESSAGE_JUSTIFICATIVA_ALTERACAO_STATUS: "Sr. (a) usuário(a), para alteração do Status da Chapa, o campo justificativa é de preenchimento obrigatório: ",
      LABEL_JUSTIFICATIVA_ALTERAR_STATUS_CHAPA: "Justificativa - Alterar Status da Chapa",
      LABEL_ORIGEM: "Origem",
      LABEL_CONFIRMAR_PARTICIPACAO_CHAPA_ELEITORAL: "Confirmar Participação em Chapa Eleitoral",
      LABEL_VISUALIZAR_CONVITES_PARA_MEMBRO_CHAPA_ELEITORAL: "Visualizar Convite Para Membro da Chapa Eleitoral",
      LABEL_INFORMACOES_IMPORTANTES: "Informações Importantes",
      LABEL_CONVITES_RECEBIDOS: "Convites Recebidos",
      LABEL_INFORMACOES_CHAPA: "Informações da chapa",
      LABEL_INFORMACOES_PARTICIPACAO: "Informações para participação",
      LABEL_NOME_RESPONSAVEL: "Nome do Responsável",
      LABEL_PLATAFORMA_ELEITORAL: "Plataforma Eleitoral",
      LABEL_POSICAO_CHAPA: "Posição na Chapa",
      LABEL_ACOES: "Ações",
      LABEL_SELECIONAR_DECLARACAO: "Selecionar Declaração",
      LABEL_SELEC_DECLARA_PARTIC_CHAPA_ELEITORAL: 'Selecione Declaração Para Participação na Chapa Eleitoral',
      LABEL_DEFINIR_EMAIL_DECLARACAO: "Definir E-Mail/Declaração",
      LABEL_DEFINIR_EMAIL_PARTICIPACAO_COMISSAO: "Definir Declaração/E-Mail Para Fins de Participação da Comissão Eleitoral",
      LABEL_DEFINIR_EMAIL_DECLARACAO_REGISTRO_CHAPA: "Definir E-Mail/Declaração Para Registrar Chapa",
      LABEL_DEFINIR_EMAIL_DECLARACAO_CONFIRMAR_PARTICIPACAO: "Definir E-Mail/Declaração Para Confirmar Participação",
      LABEL_DEFINIR_EMAIL_PEDIDO_SUBSTITUICAO_CHAPA: "Definir E-Mail do Pedido de Substituição",
      LABEL_DEFINIR_EMAIL_JULGAMENTO_SUBSTITUICAO: "Definir E-Mail do Julgamento do Pedido de Substituição",
      LABEL_DEFINIR_EMAIL_JULGAMENTO_IMPUGNACAO: "Definir E-Mail do Julgamento do Pedido de Impugnação",
      LABEL_DEFINIR_EMAIL_JULGAMENTO_IMPUGNACAO_PRIMEIRA_INSTANCIA: "Definir E-Mail do Julgamento Pedido de Impugnação - 1ª Instância",
      LABEL_DEFINIR_EMAIL_RECURSO_SUBSTITUICAO: "Definir E-Mail do Recurso da Substituição",
      LABEL_DEFINIR_EMAIL_JULGAMENTO_RECURSO_SUBSTITUICAO: "Definir E-Mail do Julgamento do Recurso da Substituição - 2ª Instância",
      LABEL_DEFINIR_EMAIL_DECLARACAO_PEDIDO_IMPUGNACAO: "Definir E-Mail e Declaração para Cadastrar Pedido de Impugnação",
      LABEL_DEFINIR_EMAIL_RECURSO_JULGAMENTO: "Definir E-Mail Recurso Julgamento",
      LABEL_DEFINIR_EMAIL_JULGAMENTO_ADMISSIBILIDADE: "Definir E-Mail Julgamento Recurso Admissibilidade",
      LABEL_DEFINIR_EMAIL_RECURSO_IMPUGNACAO: "Definir E-Mail do Recurso do Julgamento Impugnação",
      LABEL_DEFINIR_EMAIL_RECURSO_JULG_IMPUGNACAO_PRIMEIRA_INSTANCIA: "Definir E-Mail do Recurso do Julgamento do Pedido de Impugnação – 1ª Instância",
      LABEL_DEFINIR_EMAIL_DEFESA_PEDIDO_IMPUGNACAO: "Definir E-Mail e Declaração para Defesa",
      LABEL_DEFINIR_EMAIL_JULG_RECURSO_IMPUGNACAO: "Definir E-Mail do Julgamento do Recurso do Pedido de Impugnação",
      LABEL_DEFINIR_EMAIL_JULG_RECURSO_IMPUGNACAO_SEG_INSTANCIA: "Definir E-Mail do Julgamento do Recurso do Pedido de Impugnação – 2ª Instância",
      LABEL_DEFINIR_EMAIL_CONTRARRAZAO_IMPUGNACAO: "Definir E-Mail da Contrarrazão do Pedido de Impugnação",
      LABEL_DEFINIR_EMAIL_JULG_FINAL: "Definir E-Mail do Julgamento Final das Chapas",
      LABEL_DEFINIR_EMAIL_JULG_FINAL_PRIMEIRA_INSTANCIA: "Definir E-Mail do Julgamento Final das Chapas - 1ª Instância",
      LABEL_DEFINIR_EMAIL_RECURSO_JULG_FINAL: "Definir E-Mail do Recurso do Julgamento Final",
      LABEL_DEFINIR_EMAIL_RECURSO_JULG_FINAL_PRIMEIRA_INSTANCIA: "Definir E-Mail do Recurso do Julgamento Final - 1ª Instância",
      LABEL_DEFINIR_EMAIL_SUBST_JULG_FINAL: "Definir E-Mail do Pedido de Substituição no Julgamento Final",
      LABEL_DEFINICAO_EMAIL_JA_REALIZADA: "Já existe definição de e-mail cadastrada para a atividade principal '{0}' e atividade secundária '{1}'. Para realizar a alteração é necessário remover a definição de  e-mail.",
      LABEL_DEFINIR_EMAIL_JULG_FINAL_SEGUNDA_INSTANCIA: 'Definir E-Mail do Julgamento Final das Chapas - 2ª Instância',
      LABEL_DEFINIR_EMAIL_RECURSO_SUBST_JULG_FINAL: 'Definir E-Mail do Recurso do Pedido de Substituição',
      LABEL_DEFINIR_EMAIL_ADMISSIBILIDADE_DENUNCIA: 'Definir E-Mail da admissibilidade da denúncia',
      LABEL_DEFINIR_EMAIL_INSERIR_RELATOR: 'Definir E-Mail da inserção de relator',
      LABEL_DEFINIR_EMAIL_IMPUGNACAO_RESULT: 'Definir E-Mail Cadastrar Pedido de Impugnação de Resultado',
      LABEL_DEFINIR_EMAIL_ALEGACAO_IMPUGNACAO_RESULT: 'Definir E-Mail Cadastrar Alegação para o Pedido de Impugnação de Resultado',
      LABEL_DEFINIR_EMAIL_JULG_ALEGACAO_IMPUGNACAO_RESULT: 'Cadastrar Julgamento em 1ª Instancia da Alegação do Pedido de Impugnação de Resultado',
      LABEL_DEFINIR_EMAIL_RECURSO_IMPUGNACAO_RESULT: 'Definir E-Mail para Cadastrar Recurso do Julgamento em 1ª Instância da Alegação do Pedido de Impugnação de Resultado',
      LABEL_DEFINIR_EMAIL_CONTRARRAZAO_IMPUGNACAO_RESULT: 'Definir E-Mail para Cadastrar Contrarrazão do Recurso do Julgamento em 1ª Instância da Alegação do Pedido de Impugnação de Resultado',
      LABEL_DEFINIR_EMAIL_JULG_RECURSO_IMPUGNACAO_RESULT: 'Definir E-Mail para Cadastrar Julgamento em 2ª Instancia do Pedido de Impugnação de Resultado',
      LABEL_QUANTIDADE_DECLARACAO: 'Qtd Declaração',
      LABEL_SELECIONE_DECLARACAO: 'Selecione Declaração',
      LABEL_REGRA_DECLARACAO: 'Regra da Declaração',
      LABEL_TEXTO_DECLARACAO: 'Texto da Declaração',
      LABEL_EU: 'Eu',
      LABEL_DECLARO: 'DECLARO',
      LABEL_QUE: 'que',
      LABEL_DOCUMENTOS: 'Documentos',
      LABEL_PUBLICAR_DOCUMENTOS: 'Publicar Documentos',
      LABEL_LOCAL_PUBLICACAO: 'Local de Publicação',
      LABEL_ELEITORAL_CORPORATIVO: 'Eleitoral Corporativo',
      LABEL_ELEITORAL_PROFISSIONAL: 'Eleitoral Profissional',
      LABEL_ELEITORAL_PUBLICO: 'Eleitoral Público',
      LABEL_PUBLICADO_POR: 'Publicado Por',
      LABEL_DATA_HORA_PUBLICACAO: 'Data/Hora Publicação',
      LABEL_HRS: 'Hrs',
      LABEL_BAIXAR: 'Baixar',
      LABEL_DOCUMENTOS_PUBLICADOS: 'Documentos Publicados',
      LABEL_UPLOAD: 'Upload',
      LABEL_CORPORATIVO: 'Corporativo',
      LABEL_DATA_GERACAO_EXTRATO: 'Data da Geração do Extrato',
      LABEL_PROFISSIONAL: 'Profissional',
      LABEL_PUBLICO: 'Público',
      LABEL_AGUARDANDO_ATUALIZACAO: "Aguardando Atualização",
      LABEL_ATUALIZACAO_REALIZADA: "Atualização Realizada",
      LABEL_INFORMAR_NUMERO_CONSELHEIRO: 'Informar Número de Conselheiro',
      LABEL_INFORMACOES_IMPORTANTE: 'Informações Importante',
      LABEL_SELECIONE: 'Selecione',
      LABEL_TOTAL_PROFISSIONAIS: 'Total de Profissionais',
      LABEL_EDITADO: 'Editado',
      LABEL_LEI_12378: 'Lei 12378, art 32',
      LABEL_PROPORCAO_CONSELHEIRO: 'Proporção Conselheiro',
      LABEL_CONFIRM_OK: 'Ok',
      LABEL_CONFIRM_NO: 'Não',
      LABEL_CONFIRM_YES: 'Sim',
      LABEL_DADOS_PERDIDOS: '',
      LABEL_DESCRICAO_DEFESA: 'Descrição da Defesa',
      LABEL_DESCRICAO_JULGAMENTO: 'Descrição do Julgamento',
      LABEL_PROGRESSBAR_NIVEL_PRAZO: 'Prazo(s) Definido(s)',
      LABEL_ATIVOS: 'Ativos',
      LABEL_ATUALIZAR: 'Atualizar',
      LABEL_QTD_PROFISSIONAL_ATIVO: 'Qtd Profissional Ativo',
      LABEL_GERAR_XLSX: 'Gerar XLSX',
      LABEL_INFORME_PROPORCAO_CONSELHEIRO: 'Informe a Proporção de Conselheiro',
      LABEL_ATUALIZACAO_REALIZADA_SUCESSO: 'Atualização realizada com sucesso!',
      LABEL_EXTRATO_PROFISSIONAIS: 'Extrato dos Profissionais',
      LABEL_ALTEAR: 'Alterar',
      LABEL_REPRESENTANTES_IES: "Representates IES",
      LABEL_CONSELHEIRO_FEDERAL: "Conselheiro Federal",
      LABEL_CONSELHEIROS_ESTADUAIS: "Conselheiros Estaduais",
      LABEL_VISUALIZAR_MEMBROS_CHAPA: "Visualizar Membros da Chapa",
      LABEL_IMPUGNACAO_RESULTADO: '{0}Acompanhar Impugnação{1} de Resultado{2}',
      LABEL_STATUS_CONFIRMACAO: 'Status Confirmação',
      LABEL_STATUS_CONFIRMADO: 'Confirmado',
      LABEL_STATUS_REJEITADO: 'Rejeitado',
      LABEL_STATUS_A_CONFIRMAR: 'A confirmar',
      LABEL_STATUS_VALIDACAO: 'Status Validação',
      LABEL_STATUS_VALIDACAO_SUBSTITUICAO_IMPUGNACAO: 'Status {0} Validação',
      LABEL_STATUS_CONFIRMACAO_SUBSTITUICAO_IMPUGNACAO: 'Status {0} Confirmação',
      LABEL_ALTERAR_MEMBRO: 'Alterar Membro',
      LABEL_ALTERAR_STATUS_CONFIRMACAO: "Alterar Status de Confirmação",
      LABEL_ALTERAR_STATUS_VALIDACAO: "Alterar Status de Validação",
      LABEL_ENVIAR_EMAIL_PENDENCIA: "Enviar E-Mail de Pendência",
      LABEL_EXCLUIR_MEMBRO: "Excluir Membro",
      LABEL_REENVIAR_CONVITE: "Reenviar Convite",
      LABEL_DESCRICAO_JUSTIFICATIVA_ALTERAR_MEMBRO_CHAPA: "Sr.(a) usuário, para alteração de um membro na chapa, o campo justificativa é de preenchimento obrigatório:",
      LABEL_JUSTIFICATIVA_ALTERAR_MEMBRO_CHAPA: "Justificativa - Alterar Membro da Chapa",
      LABEL_DESCRICAO_JUSTIFICATIVA_ALTERAR_RESPONSAVEL_MEMBRO_CHAPA: "Sr.(a) usuário, para alteração da situação responsável, o campo justificativa é de preenchimento obrigatório:",
      LABEL_JUSTIFICATIVA_ALTERAR_ALTERAR_RESPONSAVEL_MEMBRO_CHAPA: "Justificativa - Alterar Situação Responsável Membro da Chapa",
      LABEL_DESCRICAO_JUSTIFICATIVA_ALTERAR_STATUS_CONFIRMACAO_MEMBRO_CHAPA: "Sr.(a) usuário, para alteração do status de confirmação do membro na chapa, o campo justificativa é de preenchimento obrigatório:",
      LABEL_JUSTIFICATIVA_ALTERAR_STATUS_CONFIRMACAO_MEMBRO_CHAPA: "Justificativa - Alterar Status de Confirmação Membro da Chapa",
      LABEL_ALTERAR_STATUS_CONFIRMACAO_MEMBRO_CHAPA: "Alterar Status de Confirmação",
      LABEL_DESCRICAO_JUSTIFICATIVA_ALTERAR_STATUS_VALIDACAO_MEMBRO_CHAPA: "Sr.(a) usuário, para alteração do status de validação do membro na chapa, o campo justificativa é de preenchimento obrigatório:",
      LABEL_JUSTIFICATIVA_ALTERAR_STATUS_VALIDACAO_MEMBRO_CHAPA: "Justificativa - Alterar Status de Validação Membro da Chapa",
      LABEL_DESCRICAO_JUSTIFICATIVA_EXCLUIR_MEMBRO_CHAPA: "Sr.(a) usuário, para excluir membro na chapa, o campo justificativa é de preenchimento obrigatório:",
      LABEL_JUSTIFICATIVA_ALTERAR_EXCLUIR_MEMBRO_CHAPA: "Justificativa - Excluir Membro da Chapa",
      LABEL_ALTERAR_STATUS_VALIDACAO_MEMBRO_CHAPA: "Alterar Status de Validação",
      LABEL_PENDENTE: "Pendente",
      LABEL_SEM_PENDENCIA: "Sem Pendência",
      LABEL_PLATAFORMA_ELEITORAL_REDES_SOCIAIS: 'Plataforma Eleitoral/Redes Sociais',
      LABEL_AGUARDANDO_CONCLUSAO: 'Aguardando Conclusão',
      LABEL_CHAPA_CONCLUIDA: 'Chapa Concluída',
      LABEL_NUM: 'Nº',
      LABEL_CADASTRAR_PLATAFORMA_ELEITORAL_UF: 'Cadastrar Plataforma Eleitoral UF',
      LABEL_CADASTRAR_PLATAFORMA_ELEITORAL_IES: 'Cadastrar Plataforma Eleitoral IES',
      LABEL_CADASTRAR_MEIOS_OFICIAIS_PROPAGANDAS: 'Cadastrar Meios Oficiais de Propagandas',
      LABEL_CADASTRAR_MEMBROS_CHAPA: 'Cadastrar Membros da Chapa',
      LABEL_CADASTRAR_MEMBROS_REPRESENTANTES_IES: 'Cadastrar Membros Para Representante IES',
      LABEL_REPRESENTANTE_IES: 'Representante IES',
      LABEL_CONSELHEIRO_UF_BR: 'Conselheiro UF-BR',
      LABEL_CARTA_INDICACAO: 'Carta de Indicação',
      LABEL_DECLARACAO_VINCULO_DOCENTE: 'Declaração Vínculo Docente ',
      LABEL_SINTESE_CURRICULO: 'Síntese Currículo',
      LABEL_INSIRA_CPF_NOME_CONSELHEIRO_FEDERAL: 'Insira um CPF ou Nome do conselheiro federal',
      LABEL_INSIRA_CPF_NOME_MEMBRO: 'Insira um CPF ou Nome do titular',
      LABEL_INSIRA_CPF_NOME_SUPLENTE: 'Insira um CPF ou Nome do suplente',
      LABEL_INSIRA_CPF_NOME_TITULAR_IES: 'Insira um CPF ou Nome do titular IES',
      LABEL_INSIRA_CPF_NOME_SUPLENTE_IES: 'Insira um CPF ou Nome do suplente IES',
      LABEL_DEFINIR_EMAIL_CADASTRAR_DENUNCIA: 'Definir email Cadastrar Denúncia',
      LABEL_DEFINIR_EMAIL_APRESENTAR_DEFESA: 'Definir E-mail Apresentar Defesa',
      LABEL_DEFINIR_EMAIL_PRODUCAO_PROVAS: 'Definir E-mail Produção de Provas',
      LABEL_DEFINIR_EMAIL_IMPEDIMENTO_SUSPEICAO: 'Definir E-mail Impedimento ou Suspeição',
      LABEL_DEFINIR_EMAIL_INSERIR_PROVAS: 'Definir E-mail Inserir Provas',
      LABEL_DEFINIR_EMAIL_AGENDAMENTO_AUDIENCIA_INSTRUCAO: 'Definir E-mail Audiência de Instrução',
      LABEL_DEFINIR_EMAIL_REALIZACAO_AUDIENCIA_INSTRUCAO: 'Definir E-mail Registrar Audiência de Instrução',
      LABEL_DEFINIR_EMAIL_ALEGACOES_FINAIS: 'Definir E-mail Alegações Finais',
      LABEL_DEFINIR_EMAIL_INSERIR_ALEGACOES_FINAIS: 'Definir E-mail Inserir Alegações Finais',
      LABEL_DEFINIR_EMAIL_INSERIR_NOVO_RELATOR: 'Definir E-mail Inserir Novo Relator',
      LABEL_DEFINIR_EMAIL_PARECER_FINAL: 'Definir E-mail Parecer Final',
      LABEL_DEFINIR_EMAIL_JULGAMENTO_PRIMEIRA_INSTANCIA: 'Definir E-mail Julgamento 1ª Instância',
      LABEL_DEFINIR_EMAIL_JULGAMENTO_SEGUNDA_INSTANCIA: 'Definir E-mail Julgamento 2ª Instância',
      LABEL_DEFINIR_EMAIL_RECURSO_RECONSIDERACAO: 'Definir E-mail Recurso ou Reconsideração',
      LABEL_DEFINIR_EMAIL_CADASTRO_CONTRARRAZAO: 'Definir E-mail Cadastro de Contrarrazão',
      LABEL_RETIFICACAO_JULGAMENTO_FINAL: "Retificação do Julgamento Final",
      LABEL_GERAR_EXTRATO: "Gerar Extrato",
      LABEL_ELEITO: 'Eleito',
      LABEL_UF_COMISSAO: 'UF comissão',

      // Alterar Julgamento Final Segunda Instância
      LABEL_ALTERAR_JULGAMENTO: 'Alterar Julgamento',
      LABEL_ALTERAR_DECISAO_JULGAMENTO: 'Decisão do julgamento',
      LABEL_ALTERAR_JULGAMENTO_FINAL: 'Alterar Julgamento Final',
      LABEL_ALTERAR_CONTEUDO_JULGAMENTO: 'Conteúdo do julgamento',
      LABEL_OPCAO_DESEJADA: 'Prezado(a), selecione a opção desejada para alteração do julgamento: ',
      LABEL_TITLE_CONFIRMAR_ALTERACAO: 'Confirmação da Alteração do Julgamento Final - Pedido de Substituição',
      LABEL_CONFIRMAR_ALTERACAO_DESICAO: 'Prezado(a), tem certeza que deseja alterar a Decisão do julgamento? ',
      LABEL_CONFIRMAR_ALTERACAO_CONTEUDO: 'Prezado(a), tem certeza que deseja alterar o conteúdo do julgamento? ',

      LABEL_NUMERO_DENUNCIA: 'Nº Denúncia',
      LABEL_HISTORICO_INADMISSAO_DENUNCIA: 'Histórico de Inadmissão da Denúncia',
      LABEL_DENUNCIANTE: 'Denunciante',
      LABEL_DENUNCIADO: 'Denunciado',
      LABEL_DENUNCIA: 'Denuncia',
      LABEL_INSERIR_MULTA: 'Inserir Multa?',
      LABEL_EXISTE_SANCAO: 'Existe Sanção?',
      LABEL_TODAS_ABAS_DENUNCIA: 'Todas as Abas da Denúncia',
      LABEL_DOCUMENTO_DENUNCIA: 'documento_denuncia_{0}.pdf',
      LABEL_APRESENTACAO_DEFESA: 'Apresentação da Defesa',

      LABEL_ADMITIDO: 'Admitido',
      LABEL_INADMITIDO: 'Inadmitido',
      LABEL_ADMISSAO: 'Admissão',
      LABEL_INADMISSAO: 'Inadmissão',

      LABEL_QUANTIDADE_PEDIDOS_DENUNCIA: 'Quantidade de Pedidos de Denúncia',
      LABEL_ACOMPANHAR_DENUNCIA: "Acompanhar Denúncia",
      LABEL_TOTAL_PEDIDOS_DENUNCIA: "Total de Pedidos de Denúncia",

      LABEL_NOME_COMPLETO: "Nome Completo",
      LABEL_INFORMACOES_DENUNCIADO: "Informações do Denunciado ",
      LABEL_INFORMACOES_DENUNCIANTE: "Informações do Denunciante",
      LABEL_NARRACAO_FATOS: "Narração dos Fatos",
      LABEL_RESPONSAVEL_PELO_CADASTRO: "Responsável pelo Cadastro",
      LABEL_TESTEMUNHAS: "Testemunhas",
      LABEL_TELEFONE: "Telefone",
      LABEL_EXTRATO_QUANTIDADE_CHAPA: 'Extrato quantidade chapa',
      LABEL_GERAR_EXTATO_PDF: "Gerar Extrato PDF",
      LABEL_GERAR_EXTRATO_NAVEGAVEL: "Gerar Extrato Navegável",
      LABEL_ALTERAR_N_CHAPA: "Alterar Nº Chapa",
      LABEL_PEDIDO_SUBSTITUICAO: 'Pedido de Substituição',
      LABEL_PEDIDO_IMPUGNACAO: 'Pedido de Impugnação',
      LABEL_NOME_CANDIDATO: "Nome do Candidato",
      LABEL_REGISTRO_IMPUGNACAO: "Registro",
      LABEL_PARTICIPACAO_NA_CHAPA: "Participação na Chapa",
      LABEL_QTD_PEDIDOS_SUBSTITUICAO: 'Quantidade de Pedidos de Substituição',
      LABEL_QTD_PEDIDOS_JULGADOS_PRIMEIRA_INSTANCIA: 'Pedidos Julgados 1ª Instância',
      LABEL_INFORMACOES_CANDIDATO: "Informações do Candidato",
      LABEL_VISUALIZAR_SUBSTITUICAO: 'Visualizar Substituição',
      LABEL_TOTAL_PEDIDOS_SOLICITADOS: 'Total de Pedidos de Impugnação:',
      LABEL_TOTAL_PEDIDOS_SUBSTITUICAO: 'Total de Pedidos de substituição:',

      LABEL_PROTOCOLO: 'Protocolo',
      LABEL_PEDIDO_SUBSTITUICAO_JULGAMENTO_FINAL: 'Pedido Substituição',
      LABEL_RECURSO_SUBSTITUICAO_JULGAMENTO_FINAL: 'Recurso do Pedido Substituição',
      LABEL_RECONSIDERACAO_SUBSTITUICAO_JULGAMENTO_FINAL: 'Reconsideração do Pedido Substituição',
      LABEL_MESSAGE_JUSTIFICATIVA_PROPORCAO_CONSELHEIRO: 'Sr(a) usuário(a), para alteração/exclusão das informações da proporção de conselheiros, o campo justificativa é de preenchimento obrigatório.',
      LABEL_MESSAGE_JUSTIFICATIVA_ATUALIZA_CONSELHEIRO: 'Sr(a) usuário(a), para ATUALIZAÇÃO MANUAL, o campo Justificativa é de preenchimento obrigatório.',
      LABEL_MESSAGE_JUSTIFICATIVA_PREENCHIMENTO_EXCLUSAO_CHAPA: 'Sr(a) usuário(a), para exclusão de uma chapa, o campo justificativa é de preenchimento obrigatório.',
      LABEL_MESSAGE_JUSTIFIQUE_ALTERACAO: 'Justifique Alteração ',
      LABEL_MESSAGE_JUSTIFIQUE_ATUALIZACAO: 'Justifique a Atualização Manual',
      LABEL_HORA_CADASTRO: 'Data/Hora do Cadastro',
      LABEL_NUM_CHAPA: 'Nº Chapa',
      LABEL_STATUS_SUBSTITUICAO: 'Status da Substituição',
      LABEL_MESSAGE_JUSTIFICATIVA_EXCLUSAO_CHAPA: 'Justificativa - Exclusão da Chapa',
      LABEL_ACAO_DETALHAR: 'Detalhar',
      LABEL_EXTRATO_PDF: "Extrato PDF",
      LABEL_SITUACAO_CHAPA: "Situação da Chapa",
      LABEL_DADOS_PESSOAIS_MEMBROS_CHAPA_ELEITORAL: "Dados Pessoais dos Membros da Chapa Eleitoral.",
      LABEL_REPRESENTACAO: "Representação",
      LABEL_A_DEFINIR: "A definir",
      LABEL_MEIOS_OFICIAIS_PROPAGANDAS: "Meios Oficiais de Propagandas",
      LABEL_DIVUGACAO_CHAPAS_PROCESSO_ELEITORAL_CAU: "DIVULGAÇÃO DE CHAPAS NO PROCESSO ELEITORAL DO CAU",
      LABEL_PROXIMO: "Próximo",
      LABEL_PROGRESSBAR_NIVEL_CADASTRO: 'Cadastro Realizado',
      LABEL_PROGRESSBAR_NIVEL_CONCLUIDO: 'Calendário Concluído',
      LABEL_EXCLUIR_ARQUIVO: 'Deseja realmente excluir o arquivo?',
      LABEL_DADOS_INCLUIDOS_SUCESSO: 'Dados incluídos com sucesso!',
      LABEL_DADOS_INCLUIDOS_SUCESSO_ELEICAO: 'Dados incluídos com sucesso: Eleição {0}',
      LABEL_EXCLUIR_ATIVIDADE: 'Deseja realmente excluir Atividade?',
      LABEL_CONFIRMACAO_EXCLUIR: 'Confirma a exclusão do registro ?',
      LABEL_DADOS_ALTERADOS_SUCESSO: 'Dados alterados com sucesso! ',
      LABEL_PROGRESSBAR_NIVEL_ATIVIDADES: 'Atividade(s) Definida(s)',
      LABEL_NENHUM_REGISTRO_ENCONTRADO: 'Nenhum registro encontrado!',
      LABEL_PENDENCIA_ENCONTRADA_NO_TRANSCORRER_PROCESSO: 'Pendências identificados no transcorrer do processo eleitoral',
      LABEL_SELECIONAR_EXCECAO: 'Selecione um Calendário, Por Favor!',
      LABEL_MESSAGE_JUSTIFICATIVA_ALTERACAO: 'Justificativa Alteração ',
      LABEL_EXCLUIR_SUB_ATIVIDADE: 'Deseja realmente excluir Sub Atividade?',
      LABEL_CONFIRMAR_PARTICIPACAO_COMISSAO: 'Confirmar Participação Comissão',
      LABEL_VOLTAR: 'Deseja realmente voltar?<br> Dados não salvos serão perdidos!',
      LABEL_QUANTIDADE_MAX_PERMITIDA_ARQUIVOS: 'Permissão de Upload: dois (2) arquivos!',
      LABEL_MUDAR_ABA: 'Deseja realmente mudar de Aba?<br>Dados não salvos serão perdidos!',
      LABEL_VALIDAR_ARQUIVO_OBRIGATORIO: 'O arquivo com a “Resolução do Processo Eleitoral” é obrigatório!',
      LABEL_INATIVAR_CALENDARIO: 'Deseja realmente Inativar o Calendário? Após inativação, o calendário não poderá ser ativado novamente!',
      LABEL_MESSAGE_JUSTIFICATIVA: 'Sr(a) usuário(a), para alteração/exclusão das informações, o campo justificativa é de preenchimento obrigatório.',
      LABEL_PERIODO_VIGENCIA_MESSAGE: 'Período de vigência foi iniciado!<br> Alterações serão permitidas mediante a “Conclusão do Calendário”.<br> Deseja concluir calendário?',
      LABEL_REPLICAR_CALENDARIO_MESSAGE: 'Ao importar os dados do ano selecionado,<br> os dados do calendário preenchidos serão substituídos!<br>Deseja realmente importar dados?',
      LABEL_FEDERAL: "Federal",
      LABEL_ESTADUAL: "Estadual",
      LABEL_VISUALIZAR_CHAPA: "Visualizar Chapa",
      LABEL_POSICAO: "Posição",
      LABEL_SUBSTITUIR_POR: 'Substituir Por',
      LABEL_JULGAR_SUBSTITUICAO: 'Julgar Substituição',
      LABEL_DESCRICAO_EXTRATO: '{0}_Extrato Conselheiros {1}',
      LABEL_NUMERO_CHAPA: 'Nº Chapa',
      LABEL_FUNDAMENTACAO: 'Fundamentação',
      LABEL_MEMBRO_JULGAMENTO_FINAL: 'Resultado dos Membros com Pendência',
      LABEL_JUSTIFICATIVA_PEDIDO_SUBSTITUICAO: 'Justificativa',
      LABEL_JUSTIFICATIVA_RECURSO_PEDIDO_SUBSTITUICAO: 'Justificativa do Recurso do Pedido de Substituição',
      LABEL_JUSTIFICATIVA_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Justificativa da Reconsideração do Pedido de Substituição',
      LABEL_DOCUMENTOS_COMPROBATORIOS: "Documentos Comprobatórios",
      LABEL_SUBSTITUICAO_MEMBRO: 'Chapa sem indicação de substuição de membros!',
      LABEL_DESCRICAO_PEDIDO_IMPUGNACAO: 'Descrição do Pedido de Impugnação',
      LABEL_JULGAR_IMPUGNACAO: "Julgar Impugnação",
      LABEL_MSG_CONFIRMAR_DATA_INICIO_JULGAMENTO: "Data de Início para o Julgamento ainda não foi Iniciada! <br> Deseja iniciar o julgamento?",
      LABEL_EM_ANALISE_PELO_MEMBRO: "Em análise pelo membro",
      LABEL_MEMBRO_CONFIRMADO: "Membro confirmado",
      LABEL_MEMBRO_REJEITOU_PARTICIPACAO: "O Membro rejeitou a participação",
      LABEL_CLIQUE_VISUALIZAR_PENDENCIAS: "Clique para visualizar as pendências",
      LABEL_MSG_CONFIRMAR_DATA_FIM_JULGAMENTO: "Data Fim para o Julgamento foi finalizada! <br> Deseja realizar o julgamento?",
      LABEL_CONFIRMAR_JULGAMENTO_IMPUGNACAO: "Confirmar Julgamento Pedido Impugnação",
      LABEL_MSG_CONFIRMACAO_JULGAMENTO: "Prezado(a), o senhor(a) tem certeza que deseja julgar {0} o pedido de impugnação de número {1}?",
      LABEL_RECURSO_RESPONSAVEL: "Recurso Responsável",
      LABEL_RECONSIDERACAO_RESPONSAVEL: "Reconsideração Responsável",
      LABEL_RECURSO_IMPUGNANTE: "Recurso Impugnante",
      LABEL_RECONSIDERACAO_IMPUGNANTE: "Reconsideração Impugnante",
      LABEL_JULGAMENTO_IMPUGNACAO: "Julgamento Impugnação",
      LABEL_QUANTIDADE_TOTAL_CHAPAS_CADASTRADAS: 'Quantidade Total Chapas Cadastradas',
      LABEL_MEMBROS_COM_PENDENCIA: '{0}Membros com{1}Pendência{2}',
      LABEL_PEDIDOS_CADASTRADOS: '{0}Pedidos{1}Cadastrados{2}',
      LABEL_STATUS_DO_JULGAMENTO: '{0}Status do {1}Julgamento{2}',
      LABEL_LISTA_MEMBROS_COMPOEM_CHAPA: 'Lista dos membros que compõem a chapa em questão',
      LABEL_RESULTADO_DOS_MEMBROS_COM_PENDENCIA: 'Resultado dos membros indicados para substituição',
      LABEL_CONTRARRAZAO_RECONSIDERACAO: 'Contrarrazao do Reconsideração',
      LABEL_DADOS_CANDIDATO: 'Dados do Candidato',
      LABEL_PEDIDO_DE_SUBSTITUICAO: 'Pedido de Substituição',
      LABEL_MEMBRO_SOLICITACAO_RECURSO: 'Membros com Solicitação de Recurso',
      LABEL_RECONSIDERACAO_DO_JULGAMENTO_FINAL: 'Reconsideração do Julgamento Final',
      LABEL_RECURSO_DO_JULGAMENTO_FINAL: 'Recurso do Julgamento Final',
      LABEL_MEMBRO_SOLICITACAO_RECONSIDERACAO: 'Membros com Solicitação de Reconsideração',
      LABEL_JULGAMENTO_FINAL: "Julgamento Final",
      LABEL_SUBSTITUICAO: "Substituição",
      LABEL_NAO_HOUVE_PEDIDO_SUBSTITUICAO: "Não houve pedido de substituição cadastrado!",

      LABEL_VISUALIZAR_QUANTIDADE_CHAPAS_CRIADAS: "Visualizar Quantidade de Chapas Criadas",
      LABEL_JULGAMENTO: "Julgamento",
      LABEL_JULGAMENTO_COMISSAO: "Julgamento da Comissão",
      LABEL_JULGAR_DENUNCIADO: "Julgar Recurso Denunciado",
      LABEL_JULGAR_DENUNCIANTE: "Julgar Recurso Denunciante",
      LABEL_VALOR_PERCENT_MULTA: "Valor Percentual da Multa",
      LABEL_JULGAMENTO_ADMISSIBILIDADE: 'Julgamento de Admissibilidade',
      LABEL_PROVIMENTO: 'Provimento (Acatar denúncia)',
      LABEL_IMPROVIMENTO: 'Improvimento (Não acatar a denúncia)',
      LABEL_ARQUIVO_INVALIDO: 'Tipo do arquivo é inválido',
      LABEL_ARQUIVO_GRANDE: 'O arquivo deve ter até 25MB',

      LABEL_ANALISE_ADMISSIBILIDADE: 'Análise de Admissibilidade',
      LABEL_RELATOR: "Relator",
      LABEL_DADOS_RELATOR: "Dados do Relator",
      LABEL_DADOS_CADASTRO: "Dados de Cadastro",
      LABEL_DESCRICAO_ADMISSAO: "Descrição da Admissão",
      LABEL_DESCRICAO_INADMISSAO: "Descrição da Inadmissão",
      LABEL_JULGAR_ADMISSIBILIDADE: 'Julgar Admissibilidade',
      LABEL_INSERIR_RELATOR: 'Inserir Relator',
      LABEL_DESPACHO_DESIGNACAO_RELATOR: 'Despacho de designação de relator',
      LABEL_SELECIONAR_RELATOR: 'Selecionar Relator',
      LABEL_RESULTADO: 'Resultado',


      LABEL_JULGAR_DENUNCIA: 'Julgar Denúncia',
      LABEL_JULGAR_DENUNCIA_SEGUNDA_INSTANCIA: 'Julgar Denúncia 2ª Instância',
      LABEL_RELACAO_ANUIDADE: '(Em relação à anuidade)',
      LABEL_JULGAMENTO_PRIMEIRA_INSTANCIA: 'Julgamento 1ª Instância',
      LABEL_JULGAMENTO_SEGUNDA_INSTANCIA: 'Julgamento 2ª Instância',
      LABEL_ACRESCIDO_MULTA: 'acrescido de multa',
      LABEL_MULTA_ANUIDADE: 'em relação à anuidade',

      LABEL_RECURSO_DENUNCIADO: 'Recurso do Denunciado',
      LABEL_RECURSO_DENUNCIANTE: 'Recurso do Denunciante',
      LABEL_CONTRARRAZAO_DENUNCIADO: 'Contrarrazão do Denunciado',
      LABEL_CONTRARRAZAO_DENUNCIANTE: 'Contrarrazão do Denunciante',
      LABEL_DESCRICAO_RECURSO_RECONSIDERACAO: 'Descrição do(a) Recurso ou Reconsideração',
      LABEL_DESCRICAO_CONTRARRAZAO: 'Descrição da Contrarrazão',
      LABEL_ABA_RECURSO_DENUNCIANTE: 'Recurso Denunciante',
      LABEL_ABA_RECURSO_DENUNCIADO: 'Recurso Denunciado',

      LABEL_VISUALIZAR_PRODUCAO_PROVAS: "Visualizar Produção de Provas",
      LABEL_PROVAS_INSERIDAS: "Provas inseridas",
      LABEL_NAO_HOUVE_INSERCAO_PROVAS_PELO_DESTINATARIO: "Não houve inserção de provas pelo destinatário.",
      LABEL_ENCAMINHAMENTO_FECHADO: "Encaminhamento fechado",
      LABEL_DATA_HORA_FECHAMENTO: "Data e hora do fechamento",
      LABEL_DESCRICAO_ENCAMINHAMENTO: 'Descrição do Encaminhamento',
      LABEL_DESCRICAO_PROVAS_APRESENTADAS: "Descrição das Provas Apresentadas",

      LABEL_AUDIENCIA_INSTRUCAO_REGISTRADA: "Audiência de Instrução registrada",
      LABEL_VISUALIZAR_AUDIENCIA_INSTRUCAO: "Visualizar Audiência de Instrução",
      LABEL_DATA_HORA_AUDIENCIA: "Data/Hora da Audiência",
      LABEL_DESCRICAO_AUDIENCIA_INSTRUCAO: "Descrição da  Audiência de Instrução",

      LABEL_IMPEDIMENTO_SUSPEICAO: 'Visualizar Impedimento ou Suspeição',
      LABEL_DESCRICAO_IMPEDIMENTO_SUSPEICAO: 'Despacho de designação do relator',
      LABEL_DESIGNACAO_NOVO_RELATOR: 'Designação do novo relator',
      LABEL_NOVO_RELATOR: 'Novo Relator',
      LABEL_RECURSO_DE_ADMISSIBILIDADE: 'Recurso de Admissibilidade',
      LABEL_DESCRICAO_RECURSO_JULGAMENTO_ADMISSIBILIDADE: 'Descrição do Recurso de admissibilidade',
      LABEL_JULGAR_RECURSO_ADMISSIBILIDADE: 'Julgar Recurso',
      LABEL_DESCRICAO_JULGAR_RECURSO_ADMISSIBILIDADE: 'Descrição da Solicitação',
      LABEL_PARECER_COMISSAO: 'Parecer da Comissão',
      LABEL_JULGAMENTO_RECURSO_ADMISSIBILIDADE: 'Julgamento Recurso de Admissibilidade',

      LABEL_VISUALIZAR_ALEGACAO_FINAL: 'Visualizar Alegações Finais',
      LABEL_SOLICITACAO_ALEGACAO_FINAL: 'Solicitação de Alegações Finais',
      LABEL_RESPOSTA: 'Resposta',
      LABEL_ALEGACOES_FINAIS: 'Alegações Finais',

      LABEL_CADASTRADO_POR: 'Cadastrado por',
      LABEL_DESCRICAO_ACAO_EXECUTADA: 'Descrição da ação executada',
      LABEL_PARECER_FINAL: 'Parecer Final',
      LABEL_PERIODO_SUSPENSAO: 'Periodo de Suspensão',
      LABEL_MULTA: 'Multa',
      LABEL_PERCENTUAL_MULTA: 'Percentual da Multa',
      LABEL_SENTENCA_ADVERTENCIA: 'Advertência',
      LABEL_SENTENCA_SUSPENSAO: 'Suspensão de propaganda',
      LABEL_SENTENCA_CASSACAO: 'Cassação do registro de candidatura',
      LABEL_SENTENCA_MULTA: 'Multa',
      LABEL_SENTENCA_OUTRAS: 'Outras adequadas e proporcionais ao grau da infração cometida',

      LABEL_HISTORICO_RELATORES_DENUNCIA: 'Histórico de Relatores da Denúncia',
      LABEL_DESPACHO_DESIGNACAO: 'Despacho de Designação',
      LABEL_VISUALIZAR_HISTORICO: 'Visualizar Histórico',
      LABEL_DADOS_ADMISSIBILIDADE: 'Dados da Admissibilidade',
      LABEL_IMPROVIDO: 'Improvido',
      LABEL_PROVIDO: 'Provido',
      LABEL_DESCRICAO_DOCUMENTO: "Descrição/Documento",

      LABEL_CHAPA_PENDENCIA_VOLTAR: 'Voltar',
      LABEL_CHAPA_PENDENCIA_PEDIDO_DENUNCIA: '{0}Pedidos de{1}Denúncia{2}',
      LABEL_CHAPA_PENDENCIA_PEDIDO_IMPUGNACAO: '{0}Pedidos de{1}Impugnação{2}',
      LABEL_CHAPA_PENDENCIA_SEM_PEDIDO_DENUNCIA: 'Não possui pedidos de Denúncia',
      LABEL_CHAPA_PENDENCIA_PEDIDO_SUBSTITUICAO: '{0}Pedidos de{1}Substituição{2}',
      LABEL_CHAPA_PENDENCIA_SEM_PEDIDO_IMPUGNACO: 'Não possui pedidos de Impugnação',
      LABEL_CHAPA_PENDENCIA_SEM_PEDIDO_SUBSTITUICAO: 'Não possui pedidos de Substituição',

      LABEL_DENUNCIA_SIGILOSA: 'Denúncia Sigilosa',

      LABEL_SELECIONE_OPCAO_DESEJADA_ALTERACAO_JULGAMENTO: "Prezado(a), selecione a opção desejada para alteração do Julgamento:",
      LABEL_OPCAO_ALTERAR_DESICAO_JULGAMENTO: "Decisão do Julgamento",
      LABEL_OPCAO_ALTERAR_CONTEUDO_JULGAMENTO: "Conteúdo do Julgamento",
      LABEL_PREZADO_TEM_CERTEZA_DESEJA_ALTERAR_CONTEUDO_JULGAMENTO: "Prezado(a), tem certeza que deseja alterar o conteúdo do julgamento?",
      LABEL_PREZADO_TEM_CERTEZA_DESEJA_ALTERAR_DECISAO_JULGAMENTO: "Prezado(a), tem certeza que deseja alterar a decisão do julgamento?",
      LABEL_CONFIRMACAO_ALTERACAO_JULGAMENTO_1_INSTANCIA: "Confirmação da Alteração do Julgamento Final - 1ª Instância",
      LABEL_ATUAL: 'Atual',
      LABEL_RETIFICAR: 'Retificar',
      LABEL_RETIFICADO: 'Retificado (s)',
      LABEL_JULGAMENTO_RETIFICADO: 'Julgamento Retificado',
      LABEL_RETIFICACAO: "Retificação",

      LABEL_ABA_RECURSO_JULGAMENTO_IMPUGNANTE: '{0}Recurso {1} Impugnante {2}',
      LABEL_ABA_RECONSIDERACAO_JULGAMENTO_IMPUGNANTE: '{0}Reconsideração {1} Impugnante {2}',
      LABEL_ABA_RECURSO_JULGAMENTO_IMPUGNADO: '{0}Recurso {1} Impugnado {2}',
      LABEL_ABA_RECONSIDERACAO_JULGAMENTO_IMPUGNADO: '{0}Reconsideração {1} Impugnado {2}',
      LABEL_INTERPOSICAO_RECURSO: 'Não há Interposição de Recurso',
      LABEL_INTERPOSICAO_RECONSIDERACAO: 'Não há Interposição de Reconsideração',
      LABEL_RECURSO_IMPUGNADO: 'Recurso Impugnado',
      LABEL_RECONSIDERACAO_IMPUGNADO: 'Reconsideração Impugnado',
      LABEL_DESCRICAO_RECURSO: 'Descrição do Recurso',
      LABEL_DESCRICAO_RECONSIDERACAO: 'Descrição do Recurso',
      LABEL_TITULO_CONTRARRAZAO: 'Contrarrazão Impugnado',
      LABEL_TITULO_CONTRARRAZAO_IMPUGNANTE: 'Contrarrazão Impugnante',
      LABEL_NAO_HOUVE_CONTRARRAZAO: 'Não houve cadastro de contrarrazão!',
      LABEL_NUMERO_PEDIDO_IMPUGNACAO: 'N° do Pedido de Impugnação: ',
      LABEL_RESPONSAVEL_CADASTRO_CONTRARRAZAO: 'Responsável pelo cadastro: ',
      LABEL_CHAPA_NUMERO: 'Chapa n° ',
      LABEL_CHAPA_NUM: 'Chapa nº {0}',
      LABEL_CONTRARRAZAO_IMPUGNANTE: "Contrarrazão Impugnante",
      LABEL_NAO_HOUVE_CADASTRO_CONTRARRAZAO: 'Não houve cadastro de contrarrazão.',

      LABEL_ACOMPANHAR_IMPUGNACAO_RESULTADO: "Acompanhar Impugnação de Resultado",
      LABEL_AGUARDANDO_ALEGACOES: "Aguardando Alegações",

      LABEL_N_DO_PEDIDO_IMPUGNACAO: "Nª do pedido de impugnação",

      TITLE_ALTERAR_JULGAMENTO: "Alterar <br> Julgamento",
      TITLE_FECHADO: 'Fechado',
      TITLE_PENDENTE: 'Pendente',
      TITLE_CONCLUIDO: 'Concluído',
      TITLE_TRANSCORRIDO: 'Transcorrido',
      LABEL_JULGAMENTO_EDITADO: 'Julgamento Editado',
      TITLE_PEDIDOS_CADASTRADOS: 'Pedidos Cadastrados',
      LABEL_JULGAMENTO_PEDIDO_SUBSTITUICAO: 'Julgamento do Pedido de Substituição',
      LABEL_SUBSTITUICAO_SOLICITADA_PELO_RESPONSAVEL_CHAPA: 'Substituição solicitada pelo Responsável da Chapa',
      LABEL_REGISTRO_JULGAMENTO: 'Registro do Julgamento',
      LABEL_RECURSO_PEDIDO_SUBSTITUICAO: 'Recurso do Pedido de Substituição',
      LABEL_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Reconsideração do Pedido de Substituição',
      LABEL_REGISTRO_RECURSO_PEDIDO_SUBSTITUICAO: 'Registro do Recurso do Pedido de Substituição',
      LABEL_REGISTRO_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Registro da Reconsideração do Pedido de Substituição',
      LABEL_JULGAMENTO_RECURSO: '{0}Julgamento{1} {2} {3}',
      LABEL_JULGAMENTO_SUBSTITUICAO: '{0}Julgamento{1} da Substituição {2}',
      LABEL_DESCRICAO_JULGAMENTO_RECONSIDERACAO: 'Descrição do Julgamento de Reconsideração',
      LABEL_DESCRICAO_JULGAMENTO_RECURSO: 'Descrição do Julgamento do Recurso',
      LABEL_JULGAMENTO_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Julgamento de Reconsideração do Pedido de Substituição',
      LABEL_JULGAMENTO_RECURSO_PEDIDO_SUBSTITUICAO: 'Julgamento do Recurso do Pedido de Substituição',
      LABEL_HISTORICO_JULGAMENTO_PEDIDO_SUBSTITUICAO: 'Histórico do Julgamento do Pedido de Substituição',
      LABEL_REGISTRO_JULGAMENTO_SUBSTITUICAO: 'Registro do Julgamento da Substituição',
      LABEL_REGISTRO_JULGAMENTO_RECURSO_SUBSTITUICAO: 'Registro do Julgamento do Recurso da Substituição',
      LABEL_EXPORTAR_CHAPA_XML: 'Exportar XML',
      LABEL_EXPORTAR_CHAPA_CSV: 'Exportar CSV',
      LABEL_EXPORTAR_CHAPA_DEFERIDA: 'Deferidas',
      LABEL_EXPORTAR_CHAPA_INDEFERIDA: 'Indeferidas',
      LABEL_EXPORTAR_TRE: 'Exportar TRE',
      LABEL_JUSTIFICATIVA_RETIFICACAO: "Justificativa da Retificação",
      LABEL_REGISTRO_JULGAMENTO_FINAL_1_INSTANCIA: "Registro do Julgamento Final - 1ª Instância:{0}",
      LABEL_JUSTIFICATIVA_DA_RETIFICACAO: 'Justificativa da Retificação',
      LABEL_EXCLUIR_TODOS: "Excluir Todos",
      LABEL_PLATAFORMA_REDES_EDITADA: 'Plataforma/Redes Editada',
      LABEL_REGISTRO_PLATAFORMA_ELEITORAL_REDES_SOCIAIS: 'Registro da Plataforma Eleitoral/Redes Sociais',
      LABEL_EXTRATO_CHAPA_POR_UF: 'Extrato_Chapa_{0}.csv',

      LABEL_NUMERO_IMPUGNACAO_RESULTADO: 'N° Pedido de Impugnação de Resultado: ',
      LABEL_DETALHAMENTO_JULGAMENTO: 'Detalhamento do julgamento',
      LABEL_DATA_CADASTRO: 'Data e hora do cadastro: ',
      LABEL_ALEGACOES: 'Alegações',
      LABEL_ABA_JULGAMENTO_PRIMEIRA_INSTANCIA: '{0}Julgamento {1} 1ª Instância {2}',
      LABEL_ABA_JULGAMENTO_SEGUNDA_INSTANCIA: '{0}Julgamento {1} 2ª Instância {2}',
      LABEL_JULGAMENTO_IMPUGNACAO_RESULTADO_PRIMEIRA_INSTANCIA: 'Julgamento do Pedido de Impugnação Resultado - 1ª instância',
      LABEL_JULGAMENTO_IMPUGNACAO_RESULTADO_SEGUNDA_INSTANCIA: 'Julgamento do Pedido de Impugnação Resultado - 2ª instância',
      LABEL_CADASTRAR_JULGAMENTO: "Cadastrar Julgamento",
      LABEL_JULGAMENTO_RECURSO_IMPUGNACAO_RESULTADO: 'Julgamento de Recurso',
      LABEL_JULGAMENTO_RECONSIDERACAO_IMPUGNACAO_RESULTADO: 'Julgamento de Reconsideração',
      LABEL_CONTRARRAZAO_RUCURSO_RECONSIDERACAO_JULGAMENTO_1_INSTANCIA: "Contrarrazão - Recurso/Reconsideração do Julgamento 1ª Instância",
      LABEL_HOMOLOGAR_JULGAMENTO: 'Homologar Julgamento',
      LABEL_SALVAR_RASCUNHO: 'Salvar rascunho',
      LABEL_TIPO_PARTICIPACAO_REPRESENTATIVIDADE: 'Participação/Representatividade',
      LABEL_REPRESENTATIVIDADE: 'Representatividade',
      LABEL_TIPO_FINALIZACAO_MANDATO: "Tipo de Finalização de Mandato",
      LABEL_CODIGO: 'Código',
      LABEL_MODULO: 'Módulo',
      LABEL_PESQUISAR_FILTRO: 'Filtros Aplicados:',
      LABEL_ORDENAR_POR: 'Ordenar por',
      LABEL_EMITIR_TERMO: 'Emitir Termo de posse',
      LABEL_ALTERAR_TERMO: 'Alterar Termo de posse',
      LABEL_BAIXAR_TERMO: 'Baixar Termo de posse',
      LABEL_EMITIR_DIPLOMA: 'Emitir Diploma',
      LABEL_ALTERAR_DIPLOMA: 'Alterar Diploma',
      LABEL_BAIXAR_DIPLOMA: 'Baixar Diploma',
      LABEL_ORDENAR_UF: 'Ordenar por UF',
      LABEL_ORDENAR_REPRESENTACAO: 'Ordernar por representação',
      LABEL_ORDENAR_TIPO_CONSELHEIRO: 'Ordernar por tipo de conselheiro',
      LABEL_EMITIR_TERMO_DE_POSSE: 'Emitir Termo de Posse',
      LABEL_DIA: 'Dia',
      LABEL_MES: 'Mês',
      LABEL_NUMERO: 'Número',
      LABEL_CPF_ARQUITETO: 'CPF do Arquiteto e Urbanista/Conselheiro',
      LABEL_NOME_ARQUITETO: 'Nome do Arquiteto e Urbanista/Conselheiro',
      LABEL_CPF_COORDENADOR: 'CPF do Coordenador',
      LABEL_NOME_COORDENADOR: 'Nome do Coordenador',
      LABEL_CIDADE: 'Cidade',
      LABEL_ANEXAR_ASSINATUTA: 'Anexar Assinatura',
      LABEL_PREPOSICAO: 'Preposição cidade',
      LABEL_CPF_PRESIDENTE: 'CPF do Presidente',
      LABEL_NOME_PRESIDENTE: 'Nome do Presidente',

      TITLE_ARQUIVO: 'Arquivo',
      TITLE_INSERIR: 'Inserir',
      TITLE_JULGADO: 'Julgado',
      TITLE_ARQUIVOS: 'Arquivos',
      TITLE_QTDE_DIAS: 'Qtde Dias',
      TITLE_JULGAMENTO: 'Julgamento',
      TITLE_SUBSTITUICAO: 'Substituição',
      TITLE_VISUALIZAR: 'Visualizar',
      TITLE_SANCAO_APLICADA: 'Sanção Aplicada',
      TITLE_NARRACAO_FATOS: 'Narração dos Fatos',
      TITLE_VISUALIZAR_ALEGACAO: 'Visualizar Alegação',
      TITLE_RECURSO_JULGMANETO: 'Recurso do Julgamento',
      TITLE_INFORMACOES_PESSOAIS: 'Informações Pessoais',
      TITLE_ACOMPANHAR_PEDIDO_SUBSTITUICAO_CANDIDATURA: 'Acompanhar Pedidos de Substituição de Candidatura',
      TITLE_DETALHAR_PEDIDO_SUBSTITUICAO_CANDIDATURA: 'Detalhar Pedido de Substituição de Candidatura',
      TITLE_VISUALIZAR_PEDIDO_SUBSTITUICAO_CANDIDATURA: 'Visualizar Pedidos de Substituição de Candidatura',
      TITLE_PEDIDO_DE_IMPUGNACAO: 'Pedido de Impugnação',
      TITLE_PENDECIAS_MEMBRO: "Pendências de Membro Chapa",
      TITLE_JULGAMENTO_COMISSAO: 'Julgamento da Comissão',
      TITLE_JULGAMENTO_DENUNCIADO: 'Julgamento Denunciado',
      TITLE_PEDIDO_DE_SUBSTITUICAO: 'Pedido de Substituição',
      TITLE_DESCRICAO_JULGAMENTO: 'Descrição do Julgamento',
      TITLE_JULGAMENTO_DENUNCIANTE: 'Julgamento Denunciante',
      TITLE_ABA_ACOMPANHAR_CHAPA: '{0} Acompanhar {1} Chapa {2}',
      TITLE_VALOR_PERCENTUAL_MULTA: 'Valor Percentual de Multa',
      TITLE_INFORMACOES_DO_SUBSTITUTO: 'Informações do Substituto',
      TITLE_ABA_PEDIDO_IMPUGNACAO: '{0}Pedido de {1}Impugnação{2}',
      TITLE_DETALHAMENTO_JULGAMENTO: 'Detalhamento do Julgamento',
      TITLE_INTERPOR_RECURSO_DOCUMENTO: 'Intepor Recurso/Documento',
      TITLE_CONFIRMACAO_DO_JULGAMENTO: 'Confirmação do Julgamento',
      TITLE_INFORMACOES_DO_SUBSTITUIDO: 'Informações do Substituído',
      TITLE_ABA_RECURSO_IMPUGNANTE: "{0} Recurso {1} Impugnante {2}",
      TITLE_PEDIDO_SUBSTITUICAO: '{0}Pedido de {1} Substituição {2}',
      TITLE_RECONSIDERACAO_JULGMANETO: 'Reconsideração do Julgamento',
      TITLE_JUSTIFICATIVA_RETIFICACAO: 'Justificativa da Retificação',
      TITLE_ABA_RECURSO_RESPONSAVEL: "{0}Recurso {1} Responsável {2}",
      TITLE_ABA_PEDIDO_SUBSTITUICAO: '{0}Pedido de {1}Substituição {2}',
      TITLE_ANALISAR_PEDIDO_IMPUGNACAO: 'Analisar Pedido de Impugnação',
      TITLE_JULGAMENTO_RECURSO_SEGUNDA_INSTANCIA: 'Julgamento do Recurso',
      TITLE_ANALISAR_PEDIDO_SUBSTITUICAO: 'Analisar Pedido de Substituição',
      TITLE_PARECER_PEDIDO_SUBSTITUICAO: 'Parecer do Pedido de Substituição',
      TITLE_VISUALIZAR_PEDIDO_IMPUGNACAO: 'Visualizar Pedidos de Impugnação',
      TITLE_ABA_ACOMPANHAR_CHAPA_QUEBRA_LINHA: '{0}Acompanhar {1} Chapa {2}',
      TITLE_ACOMPANHAR_PEDIDO_IMPUGNACAO: 'Acompanhar Pedidos de Impugnação',
      TITLE_RECURSO_PEDIDO_DE_SUBSTITUICAO: 'Recurso - Pedido de Substituição',
      TITLE_RECURSO_RECONSIDERACAO_JULGAMENTO_FINAL: '{0} do Julgamento Final',
      TITLE_ALTERAR_JULGAMENTO_FINAL: "Alterar Julgamento Final - 1ª Instância",
      TITLE_ABA_RECURSO_RECONSIDERACAO_RESPONSAVEL: '{0}{1} {2}Responsável {3}',
      TITLE_ACOMPANHAR_PEDIDO_SUBSTITUICAO: 'Acompanhar Pedido de Substituição',
      TITLE_VISUALIZAR_PEDIDO_SUBSTITUICAO: 'Visualizar Pedidos de Substituição',
      TITLE_PEDIDO_IMPUGNACAO_CANDIDATURA: 'Pedido de Impugnação de Candidatura',
      TITLE_ABA_JULGAMENTO_SEGUNDA_INSTANCIA: '{0}Julgamento {1} 2ª Instância{2}',
      TITLE_ABA_RECONSIDERACAO_IMPUGNANTE: "{0} Reconsideração {1} Impugnante {2}",
      TITLE_INTERPOR_RECONSIDERACAO_DOCUMENTO: 'Interpor Reconsideração/Documento',
      TITLE_REGISTRO_DO_JULGAMENTO_DO_RECURSO: 'Registro do Julgamento do Recurso',
      TITLE_JUSTIFICATIVA_PEDIDO_SUBSTITUICAO_DOCUMENTO: 'Justificativa / Documento',
      TITLE_ABA_JULGAMENTO_PRIMEIRA_INSTANCIA: '{0}Julgamento {1} 1ª Instância {2}',
      TITLE_ABA_RECONSIDERACAO_RESPONSAVEL: "{0} Reconsideração {1} Responsável {2}",
      TITLE_VISUALIZAR_INTERPOSICAO_DO_RECURSO: 'Visualizar Interposição do Recurso',
      TITLE_PEDIDO_DE_SUBSTITUICAO_IMPUGNACAO: 'Pedido de Substituição - Impugnação',
      TITLE_VISUALIZAR_DECLARACAO: 'Declaração para fins de participação da comissão',
      TITLE_JULGAMENTO_RECONSIDERACAO_SEGUNDA_INSTANCIA: 'Julgamento da Reconsideração',
      TITLE_INTEPOR_RECURSO_PEDIDO_IMPUGNACAO: 'Interpor Recurso - Pedido de Impugnação',
      TITLE_TOTAL_PEDIDOS_IMPUGNACAO_ESTADO: 'Total de Pedidos de Impugnação por Estado',
      TITLE_RECURSO_JULGMANETO_RESPONSAVEL: 'Recurso do Julgamento - Responsável da Chapa',
      TITLE_RECURSO_JULGMANETO_IMPUGNANTE: 'Recurso do Julgamento - Responsável Impugnante',
      TITLE_VISUALIZAR_DECLARACAO_CHAPA: 'Declaração para fins de participação da comissão',
      TITLE_RECONSIDERACAO_PEDIDO_DE_SUBSTITUICAO: 'Reconsideração - Pedido de Substituição',
      TITLE_VISUALIZAR_INTERPOSICAO_DA_SUBSTITUICAO: 'Visualizar Interposição da Substituição',
      TITLE_PARECER_RECURSO_PEDIDO_SUBSTITUICAO: 'Parecer do Recurso do Pedido de Substituição',
      TITLE_REGISTRO_DO_JULGAMENTO_DA_RECONSIDERACAO: 'Registro do Julgamento da Reconsideração',
      TITLE_CONFIRMAR_DEFERIMENTO_SUBSTITUICAO: "Confirmar Deferimento do Pedido de Substituição",
      TITLE_VISUALIZAR_JULGAMENTO_PEDIDO_IMPUGNACAO: 'Visualizar Parecer do Pedidos de Impugnação',
      TITLE_VISUALIZAR_PARECER_PEDIDO_SUBSTITUICAO: 'Visualizar Parecer do Pedido de Substituição',
      TITLE_PARECER_PEDIDO_SUBSTITUICAO_DOCUMENTO: 'Parecer do Pedido de Substituição / Documento',
      TITLE_INTEPOR_RECURSO_RECONSIDERACAO_PEDIDO_IMPUGNACAO: 'Interpor {0} - Pedido de Impugnação',
      TITLE_JULGAMENTO_FINAL_CHAPA_PRIMEIRA_INSTANCIA: 'Julgamento Final das Chapas - 1ª instância',
      TITLE_ANALISAR_RECURSO_RECONSIDERACAO_PEDIDO_IMPUGNACAO: 'Analisar {0} - Pedido de Impugnação',
      TITLE_CONFIRMAR_INDEFERIMENTO_SUBSTITUICAO: 'Confirmar Indeferimento do Pedido de Substituição',
      TITLE_INTEPOR_RECONSIDERACAO_PEDIDO_IMPUGNACAO: 'Interpor Reconsideração - Pedido de Impugnação',
      TITLE_CONFIRMAR_JULGAMENTO_RECURSO_IMPUGNACAO: "Confirmar Julgamento do Recurso Pedido Impugnação",
      TITLE_RECONSIDERACAO_JULGMANETO_RESPONSAVEL: 'Reconsideração do Julgamento - Responsável da Chapa',
      TITLE_RECONSIDERACAO_JULGMANETO_IMPUGNANTE: 'Reconsideração do Julgamento - Responsável Impugnante',
      TITLE_JULGAMENTO_FINAL_CHAPA_PRIMEIRA_INSTANCIA_N: 'Julgamento Final das Chapas - 1ª instância:{0}',
      TITLE_JULGAMENTO_IMPUGNACAO_SEGUNDA_INSTANCIA: 'Julgamento {0} do Pedido de Impugnação - 2ª instância',
      TITLE_RECURSO_RECONSIDERACAO_IMPUGNACAO_PRIMEIRA_INSTANCIA: '{0} do Pedido de Impugnação 1ª instância',
      TITLE_TOTAL_PEDIDOS_IMPUGNACAO_RESULTADO_ESTADO: 'Total de Pedidos de Impugnação de Resultado por Estado',
      TITLE_JULGAMENTO_IMPUGNACAO_PRIMEIRA_INSTANCIA: 'Julgamento do Recurso do Pedido de Impugnação - 1ª instância',
      TITLE_PARECER_RECURSO_PEDIDO_SUBSTITUICAO_DOCUMENTO: 'Parecer do Recurso do Pedido de Substituição / Documento',
      TITLE_VISUALIZAR_PARECER_RECURSO_PEDIDO_SUBSTITUICAO: 'Visualizar Parecer do Recurso do Pedido de Substituição',
      TITLE_JULGAMENTO_SUBSTITUICAO_SEGUNDA_INSTANCIA: 'Julgamento do Recurso do Pedido de Substituição - 2ª instância',
      TITLE_CONFIRMAR_DEFERIMENTO_JULGAMENTO_RECURSO_SUBST: "Confirmar Deferimento do Recurso do Pedido de Substituição",
      TITLE_NAO_EXISTE_DEFESA_IMPUGNACAO: 'Prezado(a), não existe nenhuma defesa cadastrada para esse pedido de impugnação.',
      TITLE_JULGAMENTO_SUBSTITUICAO_PRIMEIRA_INSTANCIA: 'Julgamento do Pedido de Substituição de Candidatura - 1ª instância',
      TITLE_CONFIRMAR_INDEFERIMENTO_JULGAMENTO_RECURSO_SUBST: "Confirmar Indeferimento do Recurso do Pedido de Substituição",
      TITLE_VISUALIZAR_PARECER_RECONSIDERACAO_PEDIDO_SUBSTITUICAO: 'Visualizar Parecer da Reconsideração do Pedido de Substituição',
      TITLE_CONFIRMAR_DEFERIMENTO_JULGAMENTO_RECONSIDERACAO_SUBST: "Confirmar Deferimento da Reconsideração do Pedido de Substituição",
      TITLE_CONFIRMAR_INDEFERIMENTO_JULGAMENTO_RECONSIDERACAO_SUBST: "Confirmar Indeferimento da Reconsideração do Pedido de Substituição",
      TITLE_JULGAMENTO_SUBSTITUICAO_SEGUNDA_INSTANCIA_RECONSIDERACAO: 'Julgamento da Reconsideração do Pedido de Substituição - 2ª instância',
      TITLE_CADASTRAR_CONTRARRAZAO: "Cadastrar Contrarrazão",
      TITLE_VISUALIZAR_RECURSO: "Visualizar Recurso",
      TITLE_VISUALIZAR_RECONSIDERACAO: "Visualizar Reconsideração",
      TITLE_ARQUITETO_URBANISTA: 'Arquiteto(a) e Urbanista',
      TITLE_EMPRESA_ARQUITETURA_URBANISMO: 'Empresa de Arquitetura e Urbanismo',
      TITLE_CADASTRAR_FINALIZCAO_MANDATO: "Cadastrar Tipo de Finalização de Mandato",
      TITLE_ALTERAR_FINALIZCAO_MANDATO: "Alterar Tipo de Finalização de Mandato",
      TITLE_PESQUISAR_DIPLOMA_TERMO: 'Pesquisar diploma/termo de posse',
      TITLE_RESULTADOS: "Resultados",
      TITLE_DADOS: 'Dados',
      TITLE_DATA_REALIZACAO_ELEICAO: 'Data da realização das eleições gerais',
      TITLE_DADOS_RESOLUCAO: 'Dados da Resolução',
      TITLE_DADOS_CONSELHEIRO: 'Dados do Conselheiro Eleito',
      TITLE_DATA_EMISSAO: 'Data da emissão do diploma',
      TITLE_DATA_EMISSAO_DO_TERMO : 'Data da emissão do Termo de Posse',
      TITLE_DADOS_COORDENADOR: 'Dados da assinatura do Coordenador',
      TITLE_DADOS_PRESIDENTE: 'Dados da assinatura do Presidente',
      TITLE_PESQUISAR_DIPLMA_TERMO: 'Pesquisar diploma/termo de posse',
      
      // Message
      MSG_CARREGANDO_DADOS: ' Carregando informações ...',
      MSG_CPF_NAO_ENCONTRADO: "CPF não encontrado!",
      MSG_DESEJA_SAIR_SISTEMA: 'Deseja sair do Sistema?',
      MSG_SUCESSO_EXCLUSAO: 'Registro excluído com sucesso!',
      MSG_CPF_DUPLICADO: "O CPF informado já está sendo utilizado",
      MSG_NAO_HOUVE_INTERPOSICAO: 'Não houve Interposição de {0}!',
      MSG_OBEDECER_VIGENCIA: 'Opção “Obedecer Vigência” desmarcada',
      MSG_CHAPA_EXCLUIDA_COM_SUCESSO: "Chapa excluída com sucesso!",
      MSG_PERMISSAO_UPLOAD_1: 'Permissão de Upload: um (1) arquivo!',
      MSG_PERMISSAO_UPLOAD_JULGAMENTO_ADMISSIBILIDADE: 'Permissão de Upload: cinco (5) arquivos',
      MSG_PENDENCIA_ETICO_DISCIPLINAR_PROFISSIONAL: 'Profissional possui infração ético-disciplinar aplicada, pendente',
      MSG_PENDENCIA_INFRACAO_PROFISSIONAL: 'Profissional em cumprimento de decisão por infração no exercício da profissão',
      MSG_IMPEDIMENTO_PENDENCIA_MEMBRO: 'Não é possível salvar, existem pendências nos membros',
      MSG_MAJORITARIAMENTE_CONSELHEIROS: 'Os membros devem ser majoritariamente "Conselheiros"',
      MSG_NAO_MAJORITARIAMENTE_CONSELHEIROS: 'Os membros devem ser majoritariamente "Não Conselheiros"',
      MSG_CONFIRMA_ALTERAR_MEMBROS: 'Deseja realmente realizar a alteração dos membros da comissão?',
      MSG_REGRA_ENVIO_INCLUIR_INFORMACAO_COMISSAO_ELEITORAL_01: "Caso esta atividade secundária não esteja parametrizada, o sistema enviará o E-mail ao lado, dois (2) dias antes da sua data fim.",
      MSG_DESEJA_REALMENTE_ALTERAR_DADOS: "Deseja realmente alterar os dados?",
      MSG_DESEJA_REALMENTE_VOLTAR_DADOS_NAO_SALVOS_SERAO_PERDIDOS: "Deseja realmente voltar? Dados não salvos serão perdidos!",
      MSG_CABECALHO_NAO_PODE_SER_DESATIVADO: "Cabeçalho não pode ser desativado!<br> Pois ele está sendo utilizado por um Corpo de E-Mail.<br>{0}",
      MSG_RODAPE_NAO_PODE_SER_DESATIVADO: "Rodapé não pode ser desativado!<br> Pois ele está sendo utilizado por um Corpo de E-Mail.<br>{0}",
      MSG_EXIBICAO_CALENDARIOS_PARAMETRIZADOS_CONCLUIDOS: "Apenas serão exibidos os anos com a parametrização concluída, referente a informações da quantidade de membros da comissão eleitoral.",
      MSG_ARQUIVO_RODAPE_NAO_FOI_INCLUIDO: "Arquivo do Rodapé não foi incluído!<br>Caso não queira incluir o rodapé, por gentileza, desabilite a opção “Ativar”",
      MSG_ARQUIVO_CABECALHO_NAO_FOI_INCLUIDO: "Arquivo do Cabeçalho não foi incluído! Caso não queira incluir o cabeçalho, por gentileza, desabilite a opção “Ativar”",
      MSG_ERRO_COMUNICACAO_TENTE_MAIS_TARDE: "Erro de comunicação, tente mais tarde!",
      MSG_MAXIMO_TAMANHO_PERMITIDO_ARQUIVOS_CABECALHO_RODAPE: "Para os arquivos do Cabeçalho ou do Rodapé, o tamanho máximo permitido é de 10 MB.",
      MSG_PUBLICAR_DOCUMENTO: 'Deseja realmente publicar este documento?',
      MSG_DOCUMENTO_PUBLICADO: 'Documentos gerados e enviados para publicação!',
      MSG_VALIDA_COORDENADOR_CONSELHEIRO: "O candidato escolhido deve ser conselheiro",
      MSG_VALIDA_COORDENADOR_NAO_CONSELHEIRO: "O candidato escolhido não pode ser conselheiro",
      MSG_VALIDA_COORDENADOR_SUB_CONSELHEIRO: "O substituto deve ser conselheiro(a)",
      MSG_VALIDA_COORDENADOR_SUB_NAO_CONSELHEIRO: "O substituto não pode ser conselheiro(a)",
      MSG_SISTEMA_ELEITORAL_NAO_POSSUI_ELEICAO_COM_CHAPA: "O Sistema Eleitoral não possui eleição com chapas criadas!",
      MSG_VOCE_NAO_TEM_POSSUI_PERMISSAO: "Caro(a) sr.(a), você não tem possui permissão de acesso a essa funcionalidade",
      MSG_DESEJA_REALMENTE_EXCLUIR_CHAPA_SELECIONADA: "Deseja realmente excluir a chapa selecionada?",
      MSG_OPCAO_ATIVAR_EMAIL_ENCONTRASE_DESABILITADA: "A opção Ativar E-Mail encontra-se desabilitada!<br/>Para cadastro ou alteração, por gentileza, habilitar a opção.",
      MSG_DESEJA_REALMENTE_ALTERAR_DECLARACAO: 'Já existe Declaração preenchida e enviada por um membro da Comissão! Deseja realmente Alterar?',
      MSG_DESEJA_REALMENTE_ALTERAR_DECLARACAO_CHAPA: 'Já existe Declaração preenchida e enviada por um membro da Chapa! Deseja realmente Alterar?',
      MSG_ARQUIVO_PUBLICADO_SUCESSO: "Arquivo publicado com sucesso!",
      MSG_DADOS_INCLUIDOS_COM_SUCESSO: "Dados incluídos com sucesso!",
      MSG_DADOS_ALTERADOS_COM_SUCESSO: "Dados alterados com sucesso!",
      MSG_QTD_MAXIMA_UPLOAD_5: 'Tamanho máximo de 5 arquivos excedido!',
      MSG_CHAPA_SEM_MEMBROS_PENDENCIA: 'Chapa sem membros com pendência',
      MSG_DADOS_CADASTRADOS_COM_SUCESSO: "Dados cadastrados com sucesso!",
      MSG_ERRO_PUBLICACAO_DOCUMENTO_ELEICAO: "Erro ao publicar o arquivo!",
      MSG_CONFIRMA_EXCLUSAO_ARQUIVO: 'Deseja realmente excluir o arquivo?',
      MSG_PENDENCIA_REGISTRO_PROFISSIONAL: 'Profissional sem registro ativo',
      MSG_DENUNCIA_JULGADA_COM_EXITO: 'Prezado(a), denúncia nº {0} julgada com êxito!',
      MSG_DENUNCIA_ALTERADA_COM_EXITO: 'Prezado(a), denúncia nº {0} foi alterada com êxito!',
      MSG_AGUARDE_PARECER_FINAL_RELATOR_DENUNCIA: 'Prezado(a), aguarde o parecer final do relator para julgar a denúncia.',
      MSG_CONFIRMAR_SUBTITUICAO_MEMBRO_CONVITE_ACEITE: "O CPF que o senhor quer substituir já aceitou o convite de participação da Chapa!</br> Deseja realmente substituir o profissional?",
      MSG_INFORME_AO_MENOS_UM_RESPONSAVEL: "Caro(a) Sr.(a), informe ao menos um (1) responsável pela chapa!",
      MSG_INFORMATIVO_ATUALIZACAO_CHAPA_ELEITORAL: 'Lembrando que durante o período de registro de candidatura de chapa, o senhor (a) poderá alterar a composição dos membros da sua chapa eleitoral.',
      MSG_DESEJA_REALMENTE_SAIR: "Deseja realmente sair da interface? Dados não salvos serão perdidos!",
      MSG_CONFIRMACAO_SERA_DADA_QUANDO_TITULAR_E_SUPLENTE_COMFIRMAREM: "A Confirmação será dada quando o Titular e Suplente Confirmarem",
      TXT_REGRA_DECLARACAO: "Após inserir os membros da comissão, o sistema deverá apresentar para os respectivos membros – em seu ambiente profissional – a declaração para participação da comissão.",
      MSG_ALERTA_ATIVIDADE_CRIAR_CHAPA: "A Atividade de Criar Chapa, foi iniciada e a proporção de conselheiro já foi exibida aos profissionais!",
      MSG_DESEJA_ALTERAR_PROPORCAO: 'Deseja realmente realizar uma Alteração na proporção?',
      MSG_DESEJA_ATUALIZAR_PROPORCAO: 'Deseja realmente realizar uma nova atualização?',
      MSG_AVISO_NUMERO_MAXIMO_RESPONSAVEIS: "Só é permitido a inclusão de até {0} responsáveis!",
      MSG_VALOR_PERCENTUAL_MULTA_EXCEDE_LIMITE_300: 'Prezado(a), o valor percentual da multa excede o limite de 300 %. Deseja continuar?',
      MSG_CHAPA_SEM_INDICACAO_DE_SUBSTITUICAO_DE_MEMBROS: 'Chapa sem indicação de substituição de membros!',
      MSG_NAO_EXISTE_ELEICAO_VIGENTE: "Não existe eleição vigente.",
      MSG_NAO_HA_PEDIDO_DE_IMPUGNACAO_CADASTRADO: 'Não há pedido de impugnação de resultado cadastrado.',
      MSG_EXTRATO_EM_EXECUCAO: "A geração do extrato ainda está em execução!",
      MGS_N_HOUVE_CONTRARRAZAO_CADASTRADA: 'Não Houve Contrarrazão Cadastrada!',
      MSG_PENDENCIA_ANUNIADADE_PROFISSIONAL: 'Pendências de Anuidade com o CAU',
      MSG_SUCESSO_ALTERAR_MEMBROS: 'Alteração de membros realizado com sucesso!',
      MSG_CHAPA_DEFERIDA_COM_SUCESSO: 'A Chapa foi julgada Deferida com sucesso!',
      MSG_DESEJA_REALMENTE_PUBLICAR_ARQUIVO: "Deseja realmente publicar arquivo?",
      MSG_SUCESSO_CADASTRAR_MEMBROS: 'Cadastro de membros realizado com sucesso!',
      MSG_PEDIDO_DEFERIMENTO_SUCESSO: "Pedido de Substituição deferido com sucesso!",
      MSG_CHAPA_INDDEFERIDA_COM_SUCESSO: 'A Chapa foi julgada Indeferida com sucesso!',
      MSG_PEDIDO_INDEFERIMENTO_SUCESSO: "Pedido de Substituição indeferido com sucesso!",
      MSG_JULGADO_PROCEDENTE: "Pedido de Impugnação foi julgado Procedente com sucesso!",
      MSG_CALENDARIO_CONCLUIDO: 'Cadastro do Calendário Eleitoral concluído com sucesso!',
      MSG_VISUALIZAR_DECLARACAO: "Para visualização, por gentileza selecionar Declaração.",
      MSG_DESABILITAR_OPCAO_MAJORITARIA: 'Deseja realmente desabilitar a opção Majoritário?',
      MSG_JULGADO_IMPROCEDENTE: "Pedido de Impugnação foi julgado Improcedente com sucesso!",
      MSG_DESEJA_REALMENTE_EXCLUIR_MEMBRO_CHAPA: "Deseja realmente excluir membro da chapa?",
      MSG_DEFINICAO_EMAIL_REALIZADA_COM_SUCESSO: "Definição de e-mail realizada com sucesso!",
      MSG_NAO_HA_MEMBROS_INDICADOS_RECURSO: 'Não há membros/posição indicados para recurso',
      MSG_NAO_HA_MEMBROS_INDICADOS_RECONSIDERACAO: 'Não há membros/posição indicados para reconsideração',
      MSG_CONFIRMACAO_EXCLUSAO_MEMBRO_PENDENCIA: 'Deseja realmente excluir membro com pendência?',
      MSG_ATUALIZAR_NUMERO_PROFISSIONAIS: 'Deseja realmente Atualizar o número de profissionais',
      MSG_CPF_NOME_NAO_ENCONTRADO_SICCAU: 'CPF Ou nome não encontrado na Base de Dados do SICCAU!',
      MSG_DADOS_ABA_INFORMACAO_NAO_SALVOS: 'Os dados da Aba Informações Iniciais devem ser salvos.',
      MSG_TAMANHO_MAXIMO_1000_CARACTERES: "Prezado(a) tamanho máximo de 1000 caracteres excedidos.",
      MSG_TAMANHO_MAXIMO_CARACTERES: "Limite máximo de caracteres atingido.",
      MSG_CONFIRMA_MUDAR_ABA: "Deseja realmente mudar de Aba?</br> Dados não salvos serão perdidos!",
      MSG_INFORMACAO_COMISSAO_MEMBRO_CONCLUIDO: 'Informações da Comissão Eleitoral concluída com sucesso!',
      MSG_HINT_ANO_ELEICAO: "Apenas serão exibidos os anos com calendário concluídos no Sistema Eleitoral!",
      MSG_DESEJA_REALMENTE_DEFINIR_EMAILS_SELECIONADOS: "Deseja realmente definir os e-mails selecionados?",
      MSG_NAO_HOUVE_INTERPOSICAO_RECURSO: 'Não houve interposição de recurso para este pedido de impugnação!',
      MSG_RECURSO_PEDIDO_SUBST_DEFERIDO_COM_SUCESSO: "Recurso do Pedido de Substituição deferido com sucesso!",
      MSG_RECURSO_PEDIDO_SUBST_INDEFERIDO_COM_SUCESSO: "Recurso do Pedido de Substituição indeferido com sucesso!",
      MSG_CONFIRMA_JULGAR_CHAPA_INDEFERIDA: 'Prezado(a), o senhor tem certeza que deseja julgar indeferida a chapa?',
      MSG_JULGAMENTO_FINAL_DEPOIS_DATA_FIM: 'Data Fim para o Julgamento foi finalizada!Deseja realizar o julgamento?',
      MSG_FIM_JULGAMENTO_SUBSTITUICAO: "Data Fim para o Julgamento foi finalizada!<br>Deseja realizar o julgamento?",
      MSG_NAO_EXISTE_ALEGACOES_IMPUGNACAO_RESULTADO: "Não há alegações de pedido de impugnação de resultado cadastrado",
      MSG_SUCESSO_JULGAMENTO_RECURSO_PROCEDENTE: "Recurso do Pedido de Impugnação foi julgado procedente com sucesso!",
      MSG_SUCESSO_JULGAMENTO_RECURSO_IMPROCEDENTE: "Recurso do Pedido de Impugnação foi julgado improcedente com sucesso!",
      MSG_NAO_HOUVE_INTERPOSICAO_RECONSIDERACAO: 'Não houve interposição de reconsideração para este pedido de impugnação!',
      MSG_NAO_HOUVE_INTERPOSICAO_RECURSO_SUBSTITUICAO: 'Não houve interposição de recurso para este pedido de substituição!',
      MSG_ATIVIDADE_SUBATIVIDADE_COM_MESMO_NOME: 'Existe Atividade/SubAtividade com o mesmo nome! <br> Deseja Salvar os Dados?',
      MSG_CONFIRMACAO_DEFERIMENTO_CHAPA_JULGAMENTO_FINAL: 'Prezado(a) , o senhor tem certeza que deseja julgar Deferida a chapa?',
      MSG_SELECIONE_ICONE_PARA_DETALHAR_PENDENCIAS_PROFISSIONAL: "Selecione o ícone para detalhar as pendências do profissional.",
      MSG_DESABILITAR_DIAS_UTEIS: 'Ao desabilitar, os dias serão contabilizados em dias corridos.<br>Deseja realmente desabilitar?',
      MSG_PREZADO_DEFERIMENTO_JULGAMENTO: "Prezado(a), o sr.(a) tem certeza que deseja deferir o pedido de substituição de número ",
      MSG_JULGAMENTO_FINAL_ANTES_DATA_INICIO: 'Data de Início para o Julgamento ainda não foi Iniciada! Deseja iniciar o julgamento?',
      MSG_INICIO_JULGAMENTO_SUBSTITUICAO: "Data de Início para o Julgamento ainda não foi Iniciada!<br>Deseja iniciar o julgamento?",
      MSG_DESEJA_REALMENTE_VOLTAR_DADOS_NAO_PUBLICADOS_SERAO_PERDIDOS: "Deseja realmente voltar? Dados não publicados serão perdidos!",
      MSG_FIM_JULGAMENTO_RECURSO_SUBSTITUICAO: "Data Fim para o Julgamento 2ª Instância foi finalizada! Deseja realizar o julgamento?",
      MSG_PREZADO_INDEFERIMENTO_JULGAMENTO: "Prezado(a), o sr.(a) tem certeza que deseja indeferir o pedido de substituição de número ",
      MSG_NAO_HOUVE_INTERPOSICAO_RECONSIDERACAO_SUBSTITUICAO: 'Não houve interposição de reconsideração para este pedido de substituição!',
      MSG_INICIO_JULGAMENTO_RECURSO_SUBSTITUICAO: "Data de Início para o Julgamento 2ª Instância, ainda não foi Iniciada! Deseja iniciar o julgamento?",
      MSG_HABILITAR_ABA_PRAZO: 'Sr.(a) usuário(a) a Aba Prazo somente será habilitada, após preenchimento da Aba Período e acionamento da opção "Avançar"',
      MSG_PREZADO_DEFERIMENTO_JULGAMENTO_RECURSO_SUBST: "Prezado(a), o sr.(a) tem certeza que deseja deferir o recurso do pedido de substituição de número ",
      MSG_PREZADO_INDEFERIMENTO_JULGAMENTO_RECURSO_SUBST: "Prezado(a), o sr.(a) tem certeza que deseja indeferir o recurso do pedido de substituição de número ",
      MSG_CONFIRMACAO_JULGAMENTO_RECURSO_IMPUGNACAO: "Prezado(a), o senhor(a) tem certeza que deseja julgar {0} o recurso do pedido de impugnação de número {1}?",
      MSG_RODAPE_DOCUMENTO_COMISSAO_MEMBRO_NAO_PREENCHIDO: 'Rodapé não foi preenchido! <br>Caso não queira incluir o rodapé, por gentileza, desabilite a opção "Ativar"',
      MSG_PREZADO_DEFERIMENTO_JULGAMENTO_RECONSIDERACAO_SUBST: "Prezado(a), o sr.(a) tem certeza que deseja deferir a reconsideração do pedido de substituição de número ",
      MSG_NAO_POSSUI_CALENDARIO_CONCLUIDO: 'O Sistema Eleitoral não possui Calendário com status igual a Concluído. Por gentileza, concluir Calendário da eleição desejada!',
      MSG_CONFIRMACAO_ALTERAR_NUMERO_MEMBROS: "Prezado, ao alterar a quantidade de membros, os membros deverão ser cadastrados novamente.</br> Deseja confirmar a operação?",
      MSG_PREZADO_INDEFERIMENTO_JULGAMENTO_RECONSIDERACAO_SUBST: "Prezado(a), o sr.(a) tem certeza que deseja indeferir a reconsideração do pedido de substituição de número ",
      MSG_CABECALHO_DOCUMENTO_COMISSAO_MEMBRO_NAO_PREENCHIDO: 'Cabeçalho não foi preenchido! <br>Caso não queira incluir o cabeçalho, por gentileza, desabilite a opção "Ativar"',
      MSG_TEXTO_FINAL_DOCUMENTO_COMISSAO_MEMBRO_NAO_PREENCHIDO: 'Texto Final não foi preenchido! <br>Caso não queira incluir o texto final, por gentileza, desabilite a opção "Ativar"',
      MSG_SOLICITACAO_AGENDADA_ZERO_HORAS_HOJE_AGUARDAR_ATUALIZACAO: 'A sua solicitação está sendo executada. Quando' +
        ' finalizar, estará disponível na aba Extrato. Por favor, aguardar em torno de 60 minutos.',
      MSG_TEXTO_INICIAL_DOCUMENTO_COMISSAO_MEMBRO_NAO_PREENCHIDO: 'Texto Inicial não foi preenchido! <br>Caso não queira incluir o texto inicial, por gentileza, desabilite a opção "Ativar"',
      MSG_CONFIRMA_MUDAR_ABA_AGUARDANDO_CONCLUSAO: "Caro(a) sr.(a), foi solicitado uma alteração, porém não foi informado o novo CPF ! </br> Deseja realmente sair da tela atual, os dados não serão alterados e salvos na base de dados?",
      MSG_SOLICITACAO_SENDO_EXECUTADA_AGUARDAR_ATUALIZACAO: 'A sua solicitação está sendo executada. Quando finalizar, estará disponível na aba Extrato. Por favor, aguardar em torno de 60 minutos.',
      MSG_CONFIRMAR_JULGAMENTO_INDEFERIDO_SEM_POSSIBILIDADE_DE_SUBSTITUICAO: 'O Sistema Eleitoral detectou que não foi selecionado nenhum membro!<br> A chapa será indeferida sem possibilidade de substituição.<br> Deseja confirmar a operação?',
      MSG_HINT_INFORMATIVO_DOCUMENTO_DENUNCIA: 'São permitidos até 5 arquivos de 25 MB nos formatos: pdf, zip, rar, doc, docx, xls, xlsx, mp4, avi, wmv, mp3, wav, jpg, jpeg ou png.',
      MSG_NAO_HOUVE_CADASTRO_ALEGACAO: 'Não houve cadastro de alegações finais dentro do prazo de envio.',
      MSG_PLATAFORMA_ELEITORAL_ALTERADO: "Dados da Plataforma Eleitoral alterados com sucesso!",
      MSG_NAO_HOUVE_APRESENTACAO_DEFESA_DENUNCIA: 'Não houve apresentação de defesa para esta denúncia.',
      MSG_EXISTE_JULGAMENTO: "Prezado (a), já existe julgamento de admissibilidade cadastrado para essa denúncia",
      MSG_JULGAMENTO_SUCESSO: "Prezado (a), a denúncia nº {0} foi julgada com sucesso.",
      MSG_NAO_HOUVE_APRESENTACAO_RECURSO_ADMISSIBILIDADE: 'Não houve apresentação  de recurso de admissibilidade para essa denúncia. ',
      MSG_NECESSARIO_ALTERAR_ALGUM_VALOR_PARA_HABILITAR_BOTAO: 'É necessário alterar alguma informação do formulário para habilitar o botão',
      MSG_EXCLUSAO_COM_SUCESSO: 'Exclusão realizada com sucesso!',

      MSG_NAO_HOUVE_CADASTRO_CONTRARRAZAO_DENUNCIADO: 'Não houve cadastro de contrarrazão para o recurso do denunciante.',
      MSG_NAO_HOUVE_CADASTRO_CONTRARRAZAO_DENUNCIANTE: 'Não houve cadastro de contrarrazão para o recurso do denunciado.',
      MSG_NAO_HOUVE_APRESENTACAO_RECURSO_RECONSIDERACAO: 'Não houve apresentação de recurso ou reconsideração pelo denunciante.',
      MSG_NAO_HOUVE_APRESENTACAO_RECURSO_RECONSIDERACAO_DENUNCIADO: 'Não houve apresentação de recurso ou reconsideração pelo denunciado',

      MSG_HINT_UPLOAD_RELATOR: 'São permitidos até cinco (5) arquivos de 25 MB nos formatos: pdf, zip, rar, doc, docx, xls, xlsx, mp4, avi, wmv, mp3, wav, jpg, jpeg pi png.',
      MSG_HINT_RELATOR: '',
      MSG_RELATOR_SUCESSO: "Prezado (a), o relator foi indicado com sucesso para a denúncia nº {0}",
      MSG_JULGAMENTO_RECURSO_ADMISSIBILIDADE: 'Prezado (a), o recurso de admissibilidade da denúncia nº{0} foi julgada com sucesso.',
      MSG_REGISTRO_SALVO: 'Registro salvo com sucesso!',
      MSG_EXCLUSAO_REGISTRO: 'Deseja realmente excluir o registro?',
      MSG_EXCLUSAO_EFETUADA_SUCESSO: 'Exclusão efetuada com sucesso!',
      MSG_EXCLUSAO_NAO_EFETUADA: 'Não foi possível excluir o registro!',
      MSG_CONFIRMAR_MEMBROS: 'Confirma o cadastro de membro(s)?',
      MSG_CANCELAR_MEMBROS:'Tem certeza que deseja cancelar? As ações realizadas não serão armazenadas.',
      //Validation

      DEBUG: 'DEBUG',
      LABEL_BTN_INCLUIR: 'Incluir',
      LABEL_BTN_LOAD: 'Aguarde...',
      MSG_CANCELAR_TITULO: 'Deseja realmente cancelar?',
      MSG_CANCELAR_CONTEUDO: 'Todos os dados preenchidos será(ão) perdido(s).',

      TITLE_CONFIRMAR_JULGAR_DEFERIMENTO: 'Confirmar Julgamento',
      MSG_CONFIRMAR_JULGAR_DEFERIMENTO: 'Prezado(a), o senhor tem certeza que deseja deferir {0}?<br />O senhor estará deferindo a Chapa!',
      MSG_CONFIRMAR_JULGAR_INDEFERIMENTO: 'Prezado(a), o senhor tem certeza que deseja indeferir {0}?<br />O senhor estará indeferindo a Chapa!',
      MSG_SUCESSO_JULGAR_DEFERIMENTO: 'A Chapa foi julgada Deferida com sucesso!',
      MSG_SUCESSO_JULGAR_INDEFERIMENTO: 'A Chapa foi julgada Indeferindo com sucesso!',
      MSG_CONFIRMAR_SEM_MEMBRO_INDICACAO: 'O Sistema Eleitoral detectou que não foi selecionado nenhum membro! <br />A chapa será indeferida sem possibilidade de substituição.<br />Deseja confirmar a operação?',
      MSG_CONFIRMAR_EXCLUIR_TODOS_MEMBROS_INDICADOS: "Deseja realmente excluir TODOS os membros indicados?",

      MSG_ERRO_JULGAR_TIPO: 'Erro: O Parametro [JulgarTipo] do componente é diferente de: RECURSO, SUBSTITUICAO ou RECURSO_SUBSTITUICAO.',

      MSG_CONFIRMACAO_EXCLUSAO_MEMBRO_JULGAR: 'Deseja realmente excluir membro sinalizado anteriormente?',

      MSG_LISTA_MEMBROS_COMPOEM_CHAPA: 'Lista dos membros que compõem a chapa em questão',

      MSG_SUCESSO_SALVAR_JULGAMENTO_PRIMEIRA_INSTANCIA_ALEGACAO_INPUGNACAO_RESULTADO: "Prezado(a) Arquiteto(a) e Urbanista o julgamento em 1ª instancia foi cadastrado com êxito para a alegação do pedido de impugnação de resultado nº {0}.",
      MSG_SUCESSO_SALVAR_JULGAMENTO_SEGUNDA_INSTANCIA_ALEGACAO_INPUGNACAO_RESULTADO: "Prezado (a) o julgamento em 2ª instancia foi cadastrado com êxito para o pedido de impugnação de resultado nº {0}",
      MSG_CONFIRMAR_CANCELAR: "Deseja realmente cancelar?<br> Todos os dados preenchidos será(ão) perdido(s).",
      MSG_HINT_DOCUMENTO_JUGAMENTO_ALEGACAO_IMPUGNACAO_RESULTADO: "Formatos permitidos: PDF \n Tamanho máximo permitido: 15 MB",

      MSG_SUCESSO_SALVAR_CONTRARRAZAO_INPUGNACAO_RESULTADO: "Prezado(a) Arquiteto(a) e Urbanista a contrarrazao foi cadastrado com êxito para a alegação do pedido de impugnação de resultado nº {0}.",
      MSG_CHAPA_NAO_ATENDEU_MINIMO_CRITERIOS_REPRESENTATIVIDADE: 'A chapa não atendeu o mínimo de critérios de representatividade.',
      MSG_CHAPA_NAO_ATENDEU_MINIMO_COTISTAS_REPRESENTATIVIDADE: 'A chapa não atendeu a quantidade mínima de cotistas da representatividade.',
      MSG_HINT_INFORMATIVO_NUMERO_CHAPA: 'Para que seja armazenado o número de chapa inserido é necessário acionar o botão "Enter".',
      MSG_ARQUIVO_TAMANHO_MAXIMO: 'O tamanho máximo permitido é de 10 MB.',
      MSG_ARQUIVO_NAO_SUPORTADO_NOTICIA: 'Formato do arquivo inválido. Somente serão aceitos arquivos no formato de JPEG, JPG e PNG',
      MSG_CAMPOS_OBRIGATORIOS: 'Campo(s) obrigatório(s) não preenchido(s)',
      
      // Validation
      required: 'Campo de preenchimento obrigatório.',
      pattern: 'Caracter(es) informado(s) não permitido.'
    };
  }

  /**
   * Retorna a 'descrição' conforme a 'chave' informada.
   *
   * @param key
   * @returns
   */
  getDescription(key: string): string {
    return this.resource[key];
  }

  /**
   * Retorna a 'mensagem' conforme a 'chave' informada.
   *
   * @param key
   * @returns
   */
  getMessage(key: string): string {
    return this.getDescription(key);
  }
}
